package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
)

// FindAFLPlayerMatchByID is the resolver for the findAFLPlayerMatchByID field.
func (r *entityResolver) FindAFLPlayerMatchByID(ctx context.Context, id string) (*AFLPlayerMatch, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, err
	}
	pm, err := r.Queries.GetPlayerMatchByID(ctx, parsed)
	if err != nil {
		return nil, err
	}
	player, err := LoadersFromCtx(ctx).PlayerByPlayerSeasonID.Load(ctx, pm.PlayerSeasonID)
	if err != nil {
		return nil, err
	}
	return convertPlayerMatch(pm, *player), nil
}

// FindAFLPlayerSeasonByID is the resolver for the findAFLPlayerSeasonByID field.
func (r *entityResolver) FindAFLPlayerSeasonByID(ctx context.Context, id string) (*AFLPlayerSeason, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, err
	}
	// Validate the ID exists; field resolvers handle the nested data.
	_, err = r.Queries.GetPlayerSeasonByID(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return &AFLPlayerSeason{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
