// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AFLBye struct {
	ID   string   `json:"id"`
	Club *AFLClub `json:"club"`
}

type AFLClub struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type AFLClubMatch struct {
	ID            string            `json:"id"`
	ClubSeasonID  string            `json:"clubSeasonId"`
	Club          *AFLClub          `json:"club"`
	RushedBehinds int               `json:"rushedBehinds"`
	Score         int               `json:"score"`
	PlayerMatches []*AFLPlayerMatch `json:"playerMatches"`
	MatchID       string            `json:"matchId"`
	Match         *AFLMatch         `json:"match,omitempty"`
}

type AFLClubSeason struct {
	ID                string             `json:"id"`
	Club              *AFLClub           `json:"club"`
	Season            *AFLSeason         `json:"season"`
	Played            int                `json:"played"`
	Won               int                `json:"won"`
	Lost              int                `json:"lost"`
	Drawn             int                `json:"drawn"`
	For               int                `json:"for"`
	Against           int                `json:"against"`
	Percentage        float64            `json:"percentage"`
	PremiershipPoints int                `json:"premiershipPoints"`
	PlayerSeasons     []*AFLPlayerSeason `json:"playerSeasons"`
}

type AFLLiveRound struct {
	Round     *AFLRound `json:"round"`
	StartDate string    `json:"startDate"`
}

type AFLMatch struct {
	ID            string        `json:"id"`
	Venue         *string       `json:"venue,omitempty"`
	StartTime     *string       `json:"startTime,omitempty"`
	Result        *string       `json:"result,omitempty"`
	DataStatus    string        `json:"dataStatus"`
	Round         *AFLRound     `json:"round"`
	HomeClubMatch *AFLClubMatch `json:"homeClubMatch,omitempty"`
	AwayClubMatch *AFLClubMatch `json:"awayClubMatch,omitempty"`
}

type AFLPlayer struct {
	ID                 string           `json:"id"`
	Name               string           `json:"name"`
	LatestPlayerSeason *AFLPlayerSeason `json:"latestPlayerSeason,omitempty"`
}

func (AFLPlayer) IsEntity() {}

type AFLPlayerMatch struct {
	ID             string        `json:"id"`
	PlayerSeasonID string        `json:"playerSeasonId"`
	ClubMatchID    string        `json:"clubMatchId"`
	ClubMatch      *AFLClubMatch `json:"clubMatch,omitempty"`
	Player         *AFLPlayer    `json:"player"`
	Status         string        `json:"status"`
	Kicks          int           `json:"kicks"`
	Handballs      int           `json:"handballs"`
	Marks          int           `json:"marks"`
	Hitouts        int           `json:"hitouts"`
	Tackles        int           `json:"tackles"`
	Goals          int           `json:"goals"`
	Behinds        int           `json:"behinds"`
	Disposals      int           `json:"disposals"`
	Score          int           `json:"score"`
}

func (AFLPlayerMatch) IsEntity() {}

type AFLPlayerSeason struct {
	ID         string            `json:"id"`
	Player     *AFLPlayer        `json:"player"`
	ClubSeason *AFLClubSeason    `json:"clubSeason"`
	Matches    []*AFLPlayerMatch `json:"matches"`
	// Aggregated stats for this player season. Both parameters are optional:
	// - upToRoundId: only final matches whose start time is before the earliest
	//   match in the given round. IDs are treated as opaque — the server resolves
	//   ordering internally via match start times, never by ID arithmetic.
	// - lastN: restrict to the most recent N qualifying matches.
	// Combining both gives the last N matches up to a nominated round, useful for
	// a rolling form window. Returns null if the player has no qualifying matches.
	Stats *AFLStatSummary `json:"stats,omitempty"`
}

func (AFLPlayerSeason) IsEntity() {}

type AFLPlayerSeasonConnection struct {
	Nodes    []*AFLPlayerSeason `json:"nodes"`
	PageInfo *PageInfo          `json:"pageInfo"`
}

type AFLPlayerSeasonFilter struct {
	Query *string `json:"query,omitempty"`
}

type AFLRound struct {
	ID      string      `json:"id"`
	Name    string      `json:"name"`
	Season  *AFLSeason  `json:"season"`
	Matches []*AFLMatch `json:"matches"`
	Byes    []*AFLBye   `json:"byes"`
}

func (AFLRound) IsEntity() {}

type AFLSeason struct {
	ID            string                     `json:"id"`
	Name          string                     `json:"name"`
	Ladder        []*AFLClubSeason           `json:"ladder"`
	Rounds        []*AFLRound                `json:"rounds"`
	PlayerSeasons *AFLPlayerSeasonConnection `json:"playerSeasons"`
}

func (AFLSeason) IsEntity() {}

// Aggregated per-stat values over a set of matches. The same shape is returned
// regardless of aggregation method or the entity being aggregated (player season,
// club season, …), making it reusable wherever summary stats are needed.
type AFLStatSummary struct {
	Goals     float64 `json:"goals"`
	Kicks     float64 `json:"kicks"`
	Handballs float64 `json:"handballs"`
	Marks     float64 `json:"marks"`
	Tackles   float64 `json:"tackles"`
	Hitouts   float64 `json:"hitouts"`
	// Number of matches included in the aggregation.
	Games int `json:"games"`
}

type AddAFLPlayerInput struct {
	Name         string `json:"name"`
	ClubSeasonID string `json:"clubSeasonId"`
}

type AddAFLPlayerSeasonInput struct {
	PlayerID     string `json:"playerId"`
	ClubSeasonID string `json:"clubSeasonId"`
}

type ImportAFLMatchStatsResult struct {
	MatchID          string                `json:"matchId"`
	HomeClubName     string                `json:"homeClubName"`
	AwayClubName     string                `json:"awayClubName"`
	HomePlayerCount  int                   `json:"homePlayerCount"`
	AwayPlayerCount  int                   `json:"awayPlayerCount"`
	UnmatchedPlayers []*UnmatchedAFLPlayer `json:"unmatchedPlayers"`
	Match            *AFLMatch             `json:"match"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
	TotalCount  *int    `json:"totalCount,omitempty"`
}

type Query struct {
}

type ResolveAFLPlayerMatchInput struct {
	ClubMatchID    string  `json:"clubMatchId"`
	PlayerSeasonID string  `json:"playerSeasonId"`
	Kicks          int     `json:"kicks"`
	Handballs      int     `json:"handballs"`
	Marks          int     `json:"marks"`
	Hitouts        int     `json:"hitouts"`
	Tackles        int     `json:"tackles"`
	Goals          int     `json:"goals"`
	Behinds        int     `json:"behinds"`
	ParsedName     *string `json:"parsedName,omitempty"`
}

type UnmatchedAFLPlayer struct {
	ParsedName  string `json:"parsedName"`
	ClubMatchID string `json:"clubMatchId"`
	Kicks       int    `json:"kicks"`
	Handballs   int    `json:"handballs"`
	Marks       int    `json:"marks"`
	Hitouts     int    `json:"hitouts"`
	Tackles     int    `json:"tackles"`
	Goals       int    `json:"goals"`
	Behinds     int    `json:"behinds"`
}

type UpdateAFLPlayerMatchInput struct {
	PlayerSeasonID string `json:"playerSeasonId"`
	ClubMatchID    string `json:"clubMatchId"`
	Kicks          *int   `json:"kicks,omitempty"`
	Handballs      *int   `json:"handballs,omitempty"`
	Marks          *int   `json:"marks,omitempty"`
	Hitouts        *int   `json:"hitouts,omitempty"`
	Tackles        *int   `json:"tackles,omitempty"`
	Goals          *int   `json:"goals,omitempty"`
	Behinds        *int   `json:"behinds,omitempty"`
}

// Aggregation method to apply over a set of matches.
type AFLStatSummaryMethod string

const (
	AFLStatSummaryMethodMean   AFLStatSummaryMethod = "MEAN"
	AFLStatSummaryMethodMedian AFLStatSummaryMethod = "MEDIAN"
)

var AllAFLStatSummaryMethod = []AFLStatSummaryMethod{
	AFLStatSummaryMethodMean,
	AFLStatSummaryMethodMedian,
}

func (e AFLStatSummaryMethod) IsValid() bool {
	switch e {
	case AFLStatSummaryMethodMean, AFLStatSummaryMethodMedian:
		return true
	}
	return false
}

func (e AFLStatSummaryMethod) String() string {
	return string(e)
}

func (e *AFLStatSummaryMethod) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AFLStatSummaryMethod(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AFLStatSummaryMethod", str)
	}
	return nil
}

func (e AFLStatSummaryMethod) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AFLStatSummaryMethod) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AFLStatSummaryMethod) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
