// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type AFLClub struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type AFLClubMatch struct {
	ID            string            `json:"id"`
	Club          *AFLClub          `json:"club"`
	RushedBehinds int               `json:"rushedBehinds"`
	Score         int               `json:"score"`
	PlayerMatches []*AFLPlayerMatch `json:"playerMatches"`
}

type AFLClubSeason struct {
	ID                string   `json:"id"`
	Club              *AFLClub `json:"club"`
	Played            int      `json:"played"`
	Won               int      `json:"won"`
	Lost              int      `json:"lost"`
	Drawn             int      `json:"drawn"`
	For               int      `json:"for"`
	Against           int      `json:"against"`
	PremiershipPoints int      `json:"premiershipPoints"`
}

type AFLLiveRound struct {
	Round     *AFLRound `json:"round"`
	StartDate string    `json:"startDate"`
}

type AFLMatch struct {
	ID                string        `json:"id"`
	Venue             *string       `json:"venue,omitempty"`
	StartTime         *string       `json:"startTime,omitempty"`
	Result            *string       `json:"result,omitempty"`
	StatsImportStatus string        `json:"statsImportStatus"`
	StatsImportedAt   *string       `json:"statsImportedAt,omitempty"`
	Round             *AFLRound     `json:"round"`
	HomeClubMatch     *AFLClubMatch `json:"homeClubMatch,omitempty"`
	AwayClubMatch     *AFLClubMatch `json:"awayClubMatch,omitempty"`
}

type AFLPlayer struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type AFLPlayerMatch struct {
	ID             string     `json:"id"`
	PlayerSeasonID string     `json:"playerSeasonId"`
	Player         *AFLPlayer `json:"player"`
	Status         string     `json:"status"`
	Kicks          int        `json:"kicks"`
	Handballs      int        `json:"handballs"`
	Marks          int        `json:"marks"`
	Hitouts        int        `json:"hitouts"`
	Tackles        int        `json:"tackles"`
	Goals          int        `json:"goals"`
	Behinds        int        `json:"behinds"`
	Disposals      int        `json:"disposals"`
	Score          int        `json:"score"`
}

func (AFLPlayerMatch) IsEntity() {}

type AFLPlayerSeason struct {
	ID         string            `json:"id"`
	Player     *AFLPlayer        `json:"player"`
	ClubSeason *AFLClubSeason    `json:"clubSeason"`
	Matches    []*AFLPlayerMatch `json:"matches"`
}

func (AFLPlayerSeason) IsEntity() {}

type AFLRound struct {
	ID      string      `json:"id"`
	Name    string      `json:"name"`
	Season  *AFLSeason  `json:"season"`
	Matches []*AFLMatch `json:"matches"`
}

type AFLSeason struct {
	ID     string           `json:"id"`
	Name   string           `json:"name"`
	Ladder []*AFLClubSeason `json:"ladder"`
	Rounds []*AFLRound      `json:"rounds"`
}

type ImportAFLMatchStatsResult struct {
	MatchID          string   `json:"matchId"`
	HomeClubName     string   `json:"homeClubName"`
	AwayClubName     string   `json:"awayClubName"`
	HomePlayerCount  int      `json:"homePlayerCount"`
	AwayPlayerCount  int      `json:"awayPlayerCount"`
	UnmatchedPlayers []string `json:"unmatchedPlayers"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateAFLPlayerMatchInput struct {
	PlayerSeasonID string  `json:"playerSeasonId"`
	ClubMatchID    string  `json:"clubMatchId"`
	Status         *string `json:"status,omitempty"`
	Kicks          *int    `json:"kicks,omitempty"`
	Handballs      *int    `json:"handballs,omitempty"`
	Marks          *int    `json:"marks,omitempty"`
	Hitouts        *int    `json:"hitouts,omitempty"`
	Tackles        *int    `json:"tackles,omitempty"`
	Goals          *int    `json:"goals,omitempty"`
	Behinds        *int    `json:"behinds,omitempty"`
}
