package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"xffl/services/afl/internal/domain"
)

// UpdateAFLPlayerMatch is the resolver for the updateAFLPlayerMatch field.
func (r *mutationResolver) UpdateAFLPlayerMatch(ctx context.Context, input UpdateAFLPlayerMatchInput) (*AFLPlayerMatch, error) {
	playerSeasonID, err := fromID(input.PlayerSeasonID)
	if err != nil {
		return nil, err
	}
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return nil, err
	}

	pm, err := r.Commands.UpdatePlayerMatch(ctx, domain.UpsertPlayerMatchParams{
		ClubMatchID:    clubMatchID,
		PlayerSeasonID: playerSeasonID,
		Status:         input.Status,
		Kicks:          input.Kicks,
		Handballs:      input.Handballs,
		Marks:          input.Marks,
		Hitouts:        input.Hitouts,
		Tackles:        input.Tackles,
		Goals:          input.Goals,
		Behinds:        input.Behinds,
	})
	if err != nil {
		return nil, err
	}

	player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
	if err != nil {
		return nil, err
	}

	return convertPlayerMatch(pm, player), nil
}

// ImportAFLMatchStats is the resolver for the importAFLMatchStats field.
func (r *mutationResolver) ImportAFLMatchStats(ctx context.Context, matchID string) (*ImportAFLMatchStatsResult, error) {
	id, err := fromID(matchID)
	if err != nil {
		return nil, err
	}
	result, err := r.DataOps.ImportAFLStats(ctx, id)
	if err != nil {
		return nil, err
	}
	unmatched := result.UnmatchedPlayers
	if unmatched == nil {
		unmatched = []string{}
	}
	return &ImportAFLMatchStatsResult{
		MatchID:          toID(result.MatchID),
		HomeClubName:     result.HomeClubName,
		AwayClubName:     result.AwayClubName,
		HomePlayerCount:  result.HomePlayerCount,
		AwayPlayerCount:  result.AwayPlayerCount,
		UnmatchedPlayers: unmatched,
	}, nil
}

// MarkAFLMatchStatsComplete is the resolver for the markAFLMatchStatsComplete field.
func (r *mutationResolver) MarkAFLMatchStatsComplete(ctx context.Context, matchID string, complete bool) (*AFLMatch, error) {
	id, err := fromID(matchID)
	if err != nil {
		return nil, err
	}
	match, err := r.DataOps.MarkMatchStatsFinal(ctx, id, complete)
	if err != nil {
		return nil, err
	}
	return convertMatch(match), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
