package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"xffl/services/afl/internal/application"
	"xffl/services/afl/internal/domain"
)

// AddAFLPlayer is the resolver for the addAFLPlayer field.
func (r *mutationResolver) AddAFLPlayer(ctx context.Context, input AddAFLPlayerInput) (*AFLPlayerSeason, error) {
	clubSeasonID, err := fromID(input.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	ps, err := r.DataOps.AddAFLPlayer(ctx, application.AddAFLPlayerParams{
		Name:         input.Name,
		ClubSeasonID: clubSeasonID,
	})
	if err != nil {
		return nil, err
	}
	return &AFLPlayerSeason{ID: toID(ps.ID)}, nil
}

// UpdateAFLPlayerMatch is the resolver for the updateAFLPlayerMatch field.
func (r *mutationResolver) UpdateAFLPlayerMatch(ctx context.Context, input UpdateAFLPlayerMatchInput) (*AFLPlayerMatch, error) {
	playerSeasonID, err := fromID(input.PlayerSeasonID)
	if err != nil {
		return nil, err
	}
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return nil, err
	}

	pm, err := r.Commands.UpdatePlayerMatch(ctx, domain.UpsertPlayerMatchParams{
		ClubMatchID:    clubMatchID,
		PlayerSeasonID: playerSeasonID,
		Status:         input.Status,
		Kicks:          input.Kicks,
		Handballs:      input.Handballs,
		Marks:          input.Marks,
		Hitouts:        input.Hitouts,
		Tackles:        input.Tackles,
		Goals:          input.Goals,
		Behinds:        input.Behinds,
	})
	if err != nil {
		return nil, err
	}

	player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
	if err != nil {
		return nil, err
	}

	return convertPlayerMatch(pm, player), nil
}

// ImportAFLMatchStats is the resolver for the importAFLMatchStats field.
func (r *mutationResolver) ImportAFLMatchStats(ctx context.Context, matchID string) (*ImportAFLMatchStatsResult, error) {
	id, err := fromID(matchID)
	if err != nil {
		return nil, err
	}
	result, err := r.DataOps.ImportAFLStats(ctx, id)
	if err != nil {
		return nil, err
	}
	unmatched := make([]*UnmatchedAFLPlayer, len(result.UnmatchedPlayers))
	for i, u := range result.UnmatchedPlayers {
		candidates := make([]*AFLPlayerCandidate, len(u.Candidates))
		for j, c := range u.Candidates {
			candidates[j] = &AFLPlayerCandidate{
				PlayerSeasonID: toID(c.Candidate.PlayerSeasonID),
				Name:           c.Candidate.Name,
				Confidence:     c.Confidence,
			}
		}
		unmatched[i] = &UnmatchedAFLPlayer{
			ParsedName:  u.ParsedName,
			ClubMatchID: toID(u.ClubMatchID),
			Kicks:       u.Kicks,
			Handballs:   u.Handballs,
			Marks:       u.Marks,
			Hitouts:     u.Hitouts,
			Tackles:     u.Tackles,
			Goals:       u.Goals,
			Behinds:     u.Behinds,
			Candidates:  candidates,
		}
	}
	return &ImportAFLMatchStatsResult{
		MatchID:          toID(result.MatchID),
		HomeClubName:     result.HomeClubName,
		AwayClubName:     result.AwayClubName,
		HomePlayerCount:  result.HomePlayerCount,
		AwayPlayerCount:  result.AwayPlayerCount,
		UnmatchedPlayers: unmatched,
	}, nil
}

// MarkAFLMatchStatsComplete is the resolver for the markAFLMatchStatsComplete field.
func (r *mutationResolver) MarkAFLMatchStatsComplete(ctx context.Context, matchID string, complete bool) (*AFLMatch, error) {
	id, err := fromID(matchID)
	if err != nil {
		return nil, err
	}
	match, err := r.DataOps.MarkMatchStatsFinal(ctx, id, complete)
	if err != nil {
		return nil, err
	}
	return convertMatch(match), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
