package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
)

// Players is the resolver for the players field.
func (r *aFLClubResolver) Players(ctx context.Context, obj *AFLClub) ([]*AFLPlayer, error) {
	clubID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	players, err := r.Queries.GetPlayers(ctx, clubID)
	if err != nil {
		return nil, err
	}
	return convertPlayers(players), nil
}

// PlayerMatches is the resolver for the playerMatches field.
func (r *aFLClubMatchResolver) PlayerMatches(ctx context.Context, obj *AFLClubMatch) ([]*AFLPlayerMatch, error) {
	cmID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	pms, err := r.Queries.GetPlayerMatches(ctx, cmID)
	if err != nil {
		return nil, err
	}
	result := make([]*AFLPlayerMatch, len(pms))
	for i, pm := range pms {
		player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		result[i] = convertPlayerMatch(pm, player)
	}
	return result, nil
}

// HomeClubMatch is the resolver for the homeClubMatch field.
func (r *aFLMatchResolver) HomeClubMatch(ctx context.Context, obj *AFLMatch) (*AFLClubMatch, error) {
	matchID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	match, err := r.Queries.GetMatch(ctx, matchID)
	if err != nil {
		return nil, err
	}
	if match.Home.ID == 0 {
		return nil, nil
	}
	cm, err := r.Queries.GetClubMatch(ctx, match.Home.ID)
	if err != nil {
		return nil, err
	}
	club, err := r.Queries.GetClubForClubSeason(ctx, cm.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	return convertClubMatch(cm, club), nil
}

// AwayClubMatch is the resolver for the awayClubMatch field.
func (r *aFLMatchResolver) AwayClubMatch(ctx context.Context, obj *AFLMatch) (*AFLClubMatch, error) {
	matchID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	match, err := r.Queries.GetMatch(ctx, matchID)
	if err != nil {
		return nil, err
	}
	if match.Away.ID == 0 {
		return nil, nil
	}
	cm, err := r.Queries.GetClubMatch(ctx, match.Away.ID)
	if err != nil {
		return nil, err
	}
	club, err := r.Queries.GetClubForClubSeason(ctx, cm.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	return convertClubMatch(cm, club), nil
}

// Season is the resolver for the season field.
func (r *aFLRoundResolver) Season(ctx context.Context, obj *AFLRound) (*AFLSeason, error) {
	roundID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	round, err := r.Queries.GetRound(ctx, roundID)
	if err != nil {
		return nil, err
	}
	season, err := r.Queries.GetSeason(ctx, round.SeasonID)
	if err != nil {
		return nil, err
	}
	return convertSeason(season), nil
}

// Matches is the resolver for the matches field.
func (r *aFLRoundResolver) Matches(ctx context.Context, obj *AFLRound) ([]*AFLMatch, error) {
	roundID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	matches, err := r.Queries.GetMatches(ctx, roundID)
	if err != nil {
		return nil, err
	}
	return convertMatches(matches), nil
}

// Ladder is the resolver for the ladder field.
func (r *aFLSeasonResolver) Ladder(ctx context.Context, obj *AFLSeason) ([]*AFLClubSeason, error) {
	seasonID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	clubSeasons, err := r.Queries.GetClubSeasons(ctx, seasonID)
	if err != nil {
		return nil, err
	}
	result := make([]*AFLClubSeason, len(clubSeasons))
	for i, cs := range clubSeasons {
		club, err := r.Queries.GetClub(ctx, cs.ClubID)
		if err != nil {
			return nil, err
		}
		result[i] = convertClubSeason(cs, club)
	}
	return result, nil
}

// Rounds is the resolver for the rounds field.
func (r *aFLSeasonResolver) Rounds(ctx context.Context, obj *AFLSeason) ([]*AFLRound, error) {
	seasonID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	rounds, err := r.Queries.GetRounds(ctx, seasonID)
	if err != nil {
		return nil, err
	}
	return convertRounds(rounds), nil
}

// AflClubs is the resolver for the aflClubs field.
func (r *queryResolver) AflClubs(ctx context.Context) ([]*AFLClub, error) {
	clubs, err := r.Queries.GetClubs(ctx)
	if err != nil {
		return nil, err
	}
	return convertClubs(clubs), nil
}

// AflClub is the resolver for the aflClub field.
func (r *queryResolver) AflClub(ctx context.Context, id string) (*AFLClub, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid club id: %w", err)
	}
	club, err := r.Queries.GetClub(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return convertClub(club), nil
}

// AflSeasons is the resolver for the aflSeasons field.
func (r *queryResolver) AflSeasons(ctx context.Context) ([]*AFLSeason, error) {
	seasons, err := r.Queries.GetSeasons(ctx)
	if err != nil {
		return nil, err
	}
	return convertSeasons(seasons), nil
}

// AflSeason is the resolver for the aflSeason field.
func (r *queryResolver) AflSeason(ctx context.Context, id string) (*AFLSeason, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid season id: %w", err)
	}
	season, err := r.Queries.GetSeason(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return convertSeason(season), nil
}

// AflLatestRound is the resolver for the aflLatestRound field.
func (r *queryResolver) AflLatestRound(ctx context.Context) (*AFLRound, error) {
	round, err := r.Queries.GetLatestRound(ctx)
	if err != nil {
		return nil, err
	}
	return convertRound(round), nil
}

// AFLClub returns AFLClubResolver implementation.
func (r *Resolver) AFLClub() AFLClubResolver { return &aFLClubResolver{r} }

// AFLClubMatch returns AFLClubMatchResolver implementation.
func (r *Resolver) AFLClubMatch() AFLClubMatchResolver { return &aFLClubMatchResolver{r} }

// AFLMatch returns AFLMatchResolver implementation.
func (r *Resolver) AFLMatch() AFLMatchResolver { return &aFLMatchResolver{r} }

// AFLRound returns AFLRoundResolver implementation.
func (r *Resolver) AFLRound() AFLRoundResolver { return &aFLRoundResolver{r} }

// AFLSeason returns AFLSeasonResolver implementation.
func (r *Resolver) AFLSeason() AFLSeasonResolver { return &aFLSeasonResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type aFLClubResolver struct{ *Resolver }
type aFLClubMatchResolver struct{ *Resolver }
type aFLMatchResolver struct{ *Resolver }
type aFLRoundResolver struct{ *Resolver }
type aFLSeasonResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
