package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
)

// UpdateAFLPlayerMatch is the resolver for the updateAFLPlayerMatch field.
func (r *mutationResolver) UpdateAFLPlayerMatch(ctx context.Context, input UpdateAFLPlayerMatchInput) (*AFLPlayerMatch, error) {
	return nil, fmt.Errorf("not implemented: UpdateAFLPlayerMatch")
}

// AflClubs is the resolver for the aflClubs field.
func (r *queryResolver) AflClubs(ctx context.Context) ([]*AFLClub, error) {
	clubs, err := r.Queries.GetClubs(ctx)
	if err != nil {
		return nil, err
	}
	return convertClubs(clubs), nil
}

// AflClub is the resolver for the aflClub field.
func (r *queryResolver) AflClub(ctx context.Context, id string) (*AFLClub, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid club id: %w", err)
	}
	club, err := r.Queries.GetClub(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return convertClub(club), nil
}

// AflSeasons is the resolver for the aflSeasons field.
func (r *queryResolver) AflSeasons(ctx context.Context) ([]*AFLSeason, error) {
	seasons, err := r.Queries.GetSeasons(ctx)
	if err != nil {
		return nil, err
	}
	return convertSeasons(seasons), nil
}

// AflSeason is the resolver for the aflSeason field.
func (r *queryResolver) AflSeason(ctx context.Context, id string) (*AFLSeason, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid season id: %w", err)
	}
	season, err := r.Queries.GetSeason(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return convertSeason(season), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
