// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Club struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type Query struct {
}
