// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Club struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Abbreviation string `json:"abbreviation"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type Query struct {
}
