// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club.sql

package sqlcgen

import (
	"context"
)

const findAllClubs = `-- name: FindAllClubs :many
SELECT id, name
FROM ffl.club
WHERE deleted_at IS NULL
ORDER BY name
`

type FindAllClubsRow struct {
	ID   int32
	Name string
}

func (q *Queries) FindAllClubs(ctx context.Context) ([]FindAllClubsRow, error) {
	rows, err := q.db.Query(ctx, findAllClubs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllClubsRow{}
	for rows.Next() {
		var i FindAllClubsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findClubByID = `-- name: FindClubByID :one
SELECT id, name
FROM ffl.club
WHERE id = $1 AND deleted_at IS NULL
`

type FindClubByIDRow struct {
	ID   int32
	Name string
}

func (q *Queries) FindClubByID(ctx context.Context, id int32) (FindClubByIDRow, error) {
	row := q.db.QueryRow(ctx, findClubByID, id)
	var i FindClubByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const findClubsByIDs = `-- name: FindClubsByIDs :many
SELECT id, name
FROM ffl.club
WHERE id = ANY($1::int[]) AND deleted_at IS NULL
`

type FindClubsByIDsRow struct {
	ID   int32
	Name string
}

func (q *Queries) FindClubsByIDs(ctx context.Context, ids []int32) ([]FindClubsByIDsRow, error) {
	rows, err := q.db.Query(ctx, findClubsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindClubsByIDsRow{}
	for rows.Next() {
		var i FindClubsByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
