// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club_match.sql

package sqlcgen

import (
	"context"
)

const findClubMatchByID = `-- name: FindClubMatchByID :one
SELECT id, match_id, club_season_id, data_status, drv_score
FROM ffl.club_match
WHERE id = $1 AND deleted_at IS NULL
`

type FindClubMatchByIDRow struct {
	ID           int32
	MatchID      int32
	ClubSeasonID int32
	DataStatus   string
	DrvScore     *int32
}

func (q *Queries) FindClubMatchByID(ctx context.Context, id int32) (FindClubMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, findClubMatchByID, id)
	var i FindClubMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.ClubSeasonID,
		&i.DataStatus,
		&i.DrvScore,
	)
	return i, err
}

const findClubMatchesByMatchID = `-- name: FindClubMatchesByMatchID :many
SELECT id, match_id, club_season_id, data_status, drv_score
FROM ffl.club_match
WHERE match_id = $1 AND deleted_at IS NULL
`

type FindClubMatchesByMatchIDRow struct {
	ID           int32
	MatchID      int32
	ClubSeasonID int32
	DataStatus   string
	DrvScore     *int32
}

func (q *Queries) FindClubMatchesByMatchID(ctx context.Context, matchID int32) ([]FindClubMatchesByMatchIDRow, error) {
	rows, err := q.db.Query(ctx, findClubMatchesByMatchID, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindClubMatchesByMatchIDRow{}
	for rows.Next() {
		var i FindClubMatchesByMatchIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.ClubSeasonID,
			&i.DataStatus,
			&i.DrvScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClubMatchDataStatus = `-- name: UpdateClubMatchDataStatus :exec
UPDATE ffl.club_match
SET data_status = $2,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateClubMatchDataStatusParams struct {
	ID         int32
	DataStatus string
}

func (q *Queries) UpdateClubMatchDataStatus(ctx context.Context, arg UpdateClubMatchDataStatusParams) error {
	_, err := q.db.Exec(ctx, updateClubMatchDataStatus, arg.ID, arg.DataStatus)
	return err
}

const updateClubMatchScore = `-- name: UpdateClubMatchScore :exec
UPDATE ffl.club_match
SET drv_score = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateClubMatchScoreParams struct {
	ID       int32
	DrvScore *int32
}

func (q *Queries) UpdateClubMatchScore(ctx context.Context, arg UpdateClubMatchScoreParams) error {
	_, err := q.db.Exec(ctx, updateClubMatchScore, arg.ID, arg.DrvScore)
	return err
}
