// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club_match.sql

package sqlcgen

import (
	"context"
)

const countFinalClubMatchesByMatchID = `-- name: CountFinalClubMatchesByMatchID :one
SELECT COUNT(*) FROM ffl.club_match
WHERE match_id = $1 AND data_status = 'final' AND deleted_at IS NULL
`

func (q *Queries) CountFinalClubMatchesByMatchID(ctx context.Context, matchID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countFinalClubMatchesByMatchID, matchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findClubMatchByID = `-- name: FindClubMatchByID :one
SELECT id, match_id, club_season_id, data_status, notes, drv_score
FROM ffl.club_match
WHERE id = $1 AND deleted_at IS NULL
`

type FindClubMatchByIDRow struct {
	ID           int32
	MatchID      int32
	ClubSeasonID int32
	DataStatus   string
	Notes        *string
	DrvScore     *int32
}

func (q *Queries) FindClubMatchByID(ctx context.Context, id int32) (FindClubMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, findClubMatchByID, id)
	var i FindClubMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.ClubSeasonID,
		&i.DataStatus,
		&i.Notes,
		&i.DrvScore,
	)
	return i, err
}

const findClubMatchesByIDs = `-- name: FindClubMatchesByIDs :many
SELECT id, match_id, club_season_id, data_status, notes, drv_score
FROM ffl.club_match
WHERE id = ANY($1::int[]) AND deleted_at IS NULL
`

type FindClubMatchesByIDsRow struct {
	ID           int32
	MatchID      int32
	ClubSeasonID int32
	DataStatus   string
	Notes        *string
	DrvScore     *int32
}

func (q *Queries) FindClubMatchesByIDs(ctx context.Context, dollar_1 []int32) ([]FindClubMatchesByIDsRow, error) {
	rows, err := q.db.Query(ctx, findClubMatchesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindClubMatchesByIDsRow{}
	for rows.Next() {
		var i FindClubMatchesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.ClubSeasonID,
			&i.DataStatus,
			&i.Notes,
			&i.DrvScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findClubMatchesByMatchID = `-- name: FindClubMatchesByMatchID :many
SELECT id, match_id, club_season_id, data_status, notes, drv_score
FROM ffl.club_match
WHERE match_id = $1 AND deleted_at IS NULL
ORDER BY CASE WHEN side = 'home' THEN 0 ELSE 1 END
`

type FindClubMatchesByMatchIDRow struct {
	ID           int32
	MatchID      int32
	ClubSeasonID int32
	DataStatus   string
	Notes        *string
	DrvScore     *int32
}

func (q *Queries) FindClubMatchesByMatchID(ctx context.Context, matchID int32) ([]FindClubMatchesByMatchIDRow, error) {
	rows, err := q.db.Query(ctx, findClubMatchesByMatchID, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindClubMatchesByMatchIDRow{}
	for rows.Next() {
		var i FindClubMatchesByMatchIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.ClubSeasonID,
			&i.DataStatus,
			&i.Notes,
			&i.DrvScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRulesIDByClubMatchID = `-- name: GetRulesIDByClubMatchID :one
SELECT s.rules_id
FROM ffl.club_match cm
JOIN ffl.match m  ON m.id = cm.match_id
JOIN ffl.round r  ON r.id = m.round_id
JOIN ffl.season s ON s.id = r.season_id
WHERE cm.id = $1 AND cm.deleted_at IS NULL
`

func (q *Queries) GetRulesIDByClubMatchID(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getRulesIDByClubMatchID, id)
	var rules_id string
	err := row.Scan(&rules_id)
	return rules_id, err
}

const updateClubMatchDataStatus = `-- name: UpdateClubMatchDataStatus :exec
UPDATE ffl.club_match
SET data_status = $2,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateClubMatchDataStatusParams struct {
	ID         int32
	DataStatus string
}

func (q *Queries) UpdateClubMatchDataStatus(ctx context.Context, arg UpdateClubMatchDataStatusParams) error {
	_, err := q.db.Exec(ctx, updateClubMatchDataStatus, arg.ID, arg.DataStatus)
	return err
}

const updateClubMatchNotes = `-- name: UpdateClubMatchNotes :exec
UPDATE ffl.club_match
SET notes      = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateClubMatchNotesParams struct {
	ID    int32
	Notes *string
}

func (q *Queries) UpdateClubMatchNotes(ctx context.Context, arg UpdateClubMatchNotesParams) error {
	_, err := q.db.Exec(ctx, updateClubMatchNotes, arg.ID, arg.Notes)
	return err
}

const updateClubMatchPremiershipPoints = `-- name: UpdateClubMatchPremiershipPoints :exec
UPDATE ffl.club_match
SET drv_premiership_points = $2,
    updated_at             = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateClubMatchPremiershipPointsParams struct {
	ID                   int32
	DrvPremiershipPoints *int32
}

func (q *Queries) UpdateClubMatchPremiershipPoints(ctx context.Context, arg UpdateClubMatchPremiershipPointsParams) error {
	_, err := q.db.Exec(ctx, updateClubMatchPremiershipPoints, arg.ID, arg.DrvPremiershipPoints)
	return err
}

const updateClubMatchScore = `-- name: UpdateClubMatchScore :exec
UPDATE ffl.club_match
SET drv_score = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateClubMatchScoreParams struct {
	ID       int32
	DrvScore *int32
}

func (q *Queries) UpdateClubMatchScore(ctx context.Context, arg UpdateClubMatchScoreParams) error {
	_, err := q.db.Exec(ctx, updateClubMatchScore, arg.ID, arg.DrvScore)
	return err
}
