// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club_season.sql

package sqlcgen

import (
	"context"
)

const findClubSeasonByID = `-- name: FindClubSeasonByID :one
SELECT id, club_id, season_id,
       drv_played, drv_won, drv_lost, drv_drawn,
       drv_for, drv_against, drv_premiership_points
FROM ffl.club_season
WHERE id = $1 AND deleted_at IS NULL
`

type FindClubSeasonByIDRow struct {
	ID                   int32
	ClubID               int32
	SeasonID             int32
	DrvPlayed            *int32
	DrvWon               *int32
	DrvLost              *int32
	DrvDrawn             *int32
	DrvFor               *int32
	DrvAgainst           *int32
	DrvPremiershipPoints *int32
}

func (q *Queries) FindClubSeasonByID(ctx context.Context, id int32) (FindClubSeasonByIDRow, error) {
	row := q.db.QueryRow(ctx, findClubSeasonByID, id)
	var i FindClubSeasonByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClubID,
		&i.SeasonID,
		&i.DrvPlayed,
		&i.DrvWon,
		&i.DrvLost,
		&i.DrvDrawn,
		&i.DrvFor,
		&i.DrvAgainst,
		&i.DrvPremiershipPoints,
	)
	return i, err
}

const findClubSeasonsBySeasonID = `-- name: FindClubSeasonsBySeasonID :many
SELECT id, club_id, season_id,
       drv_played, drv_won, drv_lost, drv_drawn,
       drv_for, drv_against, drv_premiership_points
FROM ffl.club_season
WHERE season_id = $1 AND deleted_at IS NULL
ORDER BY drv_premiership_points DESC, (drv_for - drv_against) DESC
`

type FindClubSeasonsBySeasonIDRow struct {
	ID                   int32
	ClubID               int32
	SeasonID             int32
	DrvPlayed            *int32
	DrvWon               *int32
	DrvLost              *int32
	DrvDrawn             *int32
	DrvFor               *int32
	DrvAgainst           *int32
	DrvPremiershipPoints *int32
}

func (q *Queries) FindClubSeasonsBySeasonID(ctx context.Context, seasonID int32) ([]FindClubSeasonsBySeasonIDRow, error) {
	rows, err := q.db.Query(ctx, findClubSeasonsBySeasonID, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindClubSeasonsBySeasonIDRow{}
	for rows.Next() {
		var i FindClubSeasonsBySeasonIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubID,
			&i.SeasonID,
			&i.DrvPlayed,
			&i.DrvWon,
			&i.DrvLost,
			&i.DrvDrawn,
			&i.DrvFor,
			&i.DrvAgainst,
			&i.DrvPremiershipPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
