// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: league.sql

package sqlcgen

import (
	"context"
)

const createLeague = `-- name: CreateLeague :one
INSERT INTO ffl.league (name) VALUES ($1) RETURNING id, name
`

type CreateLeagueRow struct {
	ID   int32
	Name string
}

func (q *Queries) CreateLeague(ctx context.Context, name string) (CreateLeagueRow, error) {
	row := q.db.QueryRow(ctx, createLeague, name)
	var i CreateLeagueRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const findAllLeagues = `-- name: FindAllLeagues :many
SELECT id, name FROM ffl.league WHERE deleted_at IS NULL ORDER BY id
`

type FindAllLeaguesRow struct {
	ID   int32
	Name string
}

func (q *Queries) FindAllLeagues(ctx context.Context) ([]FindAllLeaguesRow, error) {
	rows, err := q.db.Query(ctx, findAllLeagues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllLeaguesRow{}
	for rows.Next() {
		var i FindAllLeaguesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
