// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FflClub struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Name      string
}

type FflClubMatch struct {
	ID                   int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	MatchID              int32
	ClubSeasonID         int32
	DataStatus           string
	DrvScore             *int32
	DrvPremiershipPoints *int32
}

type FflClubSeason struct {
	ID                   int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	ClubID               int32
	SeasonID             int32
	DrvPlayed            *int32
	DrvWon               *int32
	DrvLost              *int32
	DrvDrawn             *int32
	DrvFor               *int32
	DrvAgainst           *int32
	DrvExtraPoints       *int32
	DrvPremiershipPoints *int32
}

type FflLeague struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Name      string
}

type FflMatch struct {
	ID              int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	RoundID         int32
	MatchStyle      *string
	HomeClubMatchID *int32
	AwayClubMatchID *int32
	Clubs           []byte
	Venue           *string
	StartDt         pgtype.Timestamptz
	DrvResult       *string
}

type FflPlayer struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	AflPlayerID int32
}

type FflPlayerMatch struct {
	ID                  int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	ClubMatchID         int32
	PlayerSeasonID      int32
	AflPlayerMatchID    *int32
	Status              *string
	Position            *string
	BackupPositions     *string
	InterchangePosition *string
	DrvScore            *int32
}

type FflPlayerSeason struct {
	ID                int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	PlayerID          int32
	ClubSeasonID      int32
	FromRoundID       *int32
	ToRoundID         *int32
	AflPlayerSeasonID *int32
	Notes             *string
	CostCents         *int32
}

type FflRound struct {
	ID         int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	SeasonID   int32
	Name       string
	AflRoundID *int32
}

type FflSeason struct {
	ID          int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	LeagueID    int32
	Name        string
	AflSeasonID *int32
}
