// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_match.sql

package sqlcgen

import (
	"context"
)

const allAFLStatusesFinal = `-- name: AllAFLStatusesFinal :one
SELECT NOT EXISTS (
    SELECT 1 FROM ffl.player_match
    WHERE club_match_id = $1
      AND (drv_afl_status IS NULL OR drv_afl_status NOT IN ('played', 'dnp'))
      AND deleted_at IS NULL
) AS result
`

func (q *Queries) AllAFLStatusesFinal(ctx context.Context, clubMatchID int32) (bool, error) {
	row := q.db.QueryRow(ctx, allAFLStatusesFinal, clubMatchID)
	var result bool
	err := row.Scan(&result)
	return result, err
}

const deletePlayerMatchByID = `-- name: DeletePlayerMatchByID :exec
DELETE FROM ffl.player_match
WHERE id = $1
`

func (q *Queries) DeletePlayerMatchByID(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePlayerMatchByID, id)
	return err
}

const deletePlayerMatchesByClubMatchID = `-- name: DeletePlayerMatchesByClubMatchID :exec
DELETE FROM ffl.player_match
WHERE club_match_id = $1
`

func (q *Queries) DeletePlayerMatchesByClubMatchID(ctx context.Context, clubMatchID int32) error {
	_, err := q.db.Exec(ctx, deletePlayerMatchesByClubMatchID, clubMatchID)
	return err
}

const findPlayerMatchByID = `-- name: FindPlayerMatchByID :one
SELECT id, club_match_id, player_season_id,
       position, status, drv_afl_status, backup_positions, interchange_position, display_order, drv_score, afl_player_match_id
FROM ffl.player_match
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerMatchByIDRow struct {
	ID                  int32
	ClubMatchID         int32
	PlayerSeasonID      int32
	Position            *string
	Status              *string
	DrvAflStatus        *string
	BackupPositions     *string
	InterchangePosition *string
	DisplayOrder        int32
	DrvScore            *int32
	AflPlayerMatchID    *int32
}

func (q *Queries) FindPlayerMatchByID(ctx context.Context, id int32) (FindPlayerMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerMatchByID, id)
	var i FindPlayerMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClubMatchID,
		&i.PlayerSeasonID,
		&i.Position,
		&i.Status,
		&i.DrvAflStatus,
		&i.BackupPositions,
		&i.InterchangePosition,
		&i.DisplayOrder,
		&i.DrvScore,
		&i.AflPlayerMatchID,
	)
	return i, err
}

const findPlayerMatchByPlayerSeasonAndRound = `-- name: FindPlayerMatchByPlayerSeasonAndRound :one
SELECT pm.id, pm.club_match_id, pm.player_season_id,
       pm.position, pm.status, pm.drv_afl_status, pm.backup_positions, pm.interchange_position, pm.display_order, pm.drv_score, pm.afl_player_match_id
FROM ffl.player_match pm
JOIN ffl.club_match cm ON pm.club_match_id = cm.id
JOIN ffl.match m ON cm.match_id = m.id
WHERE pm.player_season_id = $1 AND m.round_id = $2 AND pm.deleted_at IS NULL
`

type FindPlayerMatchByPlayerSeasonAndRoundParams struct {
	PlayerSeasonID int32
	RoundID        int32
}

type FindPlayerMatchByPlayerSeasonAndRoundRow struct {
	ID                  int32
	ClubMatchID         int32
	PlayerSeasonID      int32
	Position            *string
	Status              *string
	DrvAflStatus        *string
	BackupPositions     *string
	InterchangePosition *string
	DisplayOrder        int32
	DrvScore            *int32
	AflPlayerMatchID    *int32
}

func (q *Queries) FindPlayerMatchByPlayerSeasonAndRound(ctx context.Context, arg FindPlayerMatchByPlayerSeasonAndRoundParams) (FindPlayerMatchByPlayerSeasonAndRoundRow, error) {
	row := q.db.QueryRow(ctx, findPlayerMatchByPlayerSeasonAndRound, arg.PlayerSeasonID, arg.RoundID)
	var i FindPlayerMatchByPlayerSeasonAndRoundRow
	err := row.Scan(
		&i.ID,
		&i.ClubMatchID,
		&i.PlayerSeasonID,
		&i.Position,
		&i.Status,
		&i.DrvAflStatus,
		&i.BackupPositions,
		&i.InterchangePosition,
		&i.DisplayOrder,
		&i.DrvScore,
		&i.AflPlayerMatchID,
	)
	return i, err
}

const findPlayerMatchesByClubMatchID = `-- name: FindPlayerMatchesByClubMatchID :many
SELECT id, club_match_id, player_season_id,
       position, status, drv_afl_status, backup_positions, interchange_position, display_order, drv_score, afl_player_match_id
FROM ffl.player_match
WHERE club_match_id = $1 AND deleted_at IS NULL
ORDER BY display_order
`

type FindPlayerMatchesByClubMatchIDRow struct {
	ID                  int32
	ClubMatchID         int32
	PlayerSeasonID      int32
	Position            *string
	Status              *string
	DrvAflStatus        *string
	BackupPositions     *string
	InterchangePosition *string
	DisplayOrder        int32
	DrvScore            *int32
	AflPlayerMatchID    *int32
}

func (q *Queries) FindPlayerMatchesByClubMatchID(ctx context.Context, clubMatchID int32) ([]FindPlayerMatchesByClubMatchIDRow, error) {
	rows, err := q.db.Query(ctx, findPlayerMatchesByClubMatchID, clubMatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerMatchesByClubMatchIDRow{}
	for rows.Next() {
		var i FindPlayerMatchesByClubMatchIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubMatchID,
			&i.PlayerSeasonID,
			&i.Position,
			&i.Status,
			&i.DrvAflStatus,
			&i.BackupPositions,
			&i.InterchangePosition,
			&i.DisplayOrder,
			&i.DrvScore,
			&i.AflPlayerMatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayerMatchesByPlayerSeasonID = `-- name: FindPlayerMatchesByPlayerSeasonID :many
SELECT id, club_match_id, player_season_id,
       position, status, drv_afl_status, backup_positions, interchange_position, display_order, drv_score, afl_player_match_id
FROM ffl.player_match
WHERE player_season_id = $1 AND deleted_at IS NULL
ORDER BY id
`

type FindPlayerMatchesByPlayerSeasonIDRow struct {
	ID                  int32
	ClubMatchID         int32
	PlayerSeasonID      int32
	Position            *string
	Status              *string
	DrvAflStatus        *string
	BackupPositions     *string
	InterchangePosition *string
	DisplayOrder        int32
	DrvScore            *int32
	AflPlayerMatchID    *int32
}

func (q *Queries) FindPlayerMatchesByPlayerSeasonID(ctx context.Context, playerSeasonID int32) ([]FindPlayerMatchesByPlayerSeasonIDRow, error) {
	rows, err := q.db.Query(ctx, findPlayerMatchesByPlayerSeasonID, playerSeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerMatchesByPlayerSeasonIDRow{}
	for rows.Next() {
		var i FindPlayerMatchesByPlayerSeasonIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubMatchID,
			&i.PlayerSeasonID,
			&i.Position,
			&i.Status,
			&i.DrvAflStatus,
			&i.BackupPositions,
			&i.InterchangePosition,
			&i.DisplayOrder,
			&i.DrvScore,
			&i.AflPlayerMatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAFLPlayerMatchID = `-- name: UpdateAFLPlayerMatchID :exec
UPDATE ffl.player_match
SET afl_player_match_id = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateAFLPlayerMatchIDParams struct {
	ID               int32
	AflPlayerMatchID *int32
}

func (q *Queries) UpdateAFLPlayerMatchID(ctx context.Context, arg UpdateAFLPlayerMatchIDParams) error {
	_, err := q.db.Exec(ctx, updateAFLPlayerMatchID, arg.ID, arg.AflPlayerMatchID)
	return err
}

const updateDrvAFLStatus = `-- name: UpdateDrvAFLStatus :exec
UPDATE ffl.player_match
SET drv_afl_status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateDrvAFLStatusParams struct {
	ID           int32
	DrvAflStatus *string
}

func (q *Queries) UpdateDrvAFLStatus(ctx context.Context, arg UpdateDrvAFLStatusParams) error {
	_, err := q.db.Exec(ctx, updateDrvAFLStatus, arg.ID, arg.DrvAflStatus)
	return err
}

const updatePlayerMatchDisplayOrder = `-- name: UpdatePlayerMatchDisplayOrder :exec
UPDATE ffl.player_match
SET display_order = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdatePlayerMatchDisplayOrderParams struct {
	ID           int32
	DisplayOrder int32
}

func (q *Queries) UpdatePlayerMatchDisplayOrder(ctx context.Context, arg UpdatePlayerMatchDisplayOrderParams) error {
	_, err := q.db.Exec(ctx, updatePlayerMatchDisplayOrder, arg.ID, arg.DisplayOrder)
	return err
}

const updatePlayerMatchPosition = `-- name: UpdatePlayerMatchPosition :exec
UPDATE ffl.player_match
SET position = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdatePlayerMatchPositionParams struct {
	ID       int32
	Position *string
}

func (q *Queries) UpdatePlayerMatchPosition(ctx context.Context, arg UpdatePlayerMatchPositionParams) error {
	_, err := q.db.Exec(ctx, updatePlayerMatchPosition, arg.ID, arg.Position)
	return err
}

const updatePlayerMatchStatus = `-- name: UpdatePlayerMatchStatus :exec
UPDATE ffl.player_match
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdatePlayerMatchStatusParams struct {
	ID     int32
	Status *string
}

func (q *Queries) UpdatePlayerMatchStatus(ctx context.Context, arg UpdatePlayerMatchStatusParams) error {
	_, err := q.db.Exec(ctx, updatePlayerMatchStatus, arg.ID, arg.Status)
	return err
}

const upsertPlayerMatch = `-- name: UpsertPlayerMatch :one
INSERT INTO ffl.player_match (club_match_id, player_season_id, position, status, drv_afl_status, backup_positions, interchange_position, display_order, drv_score)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (player_season_id, club_match_id)
DO UPDATE SET
    position = COALESCE($3, ffl.player_match.position),
    status = COALESCE($4, ffl.player_match.status),
    drv_afl_status = COALESCE($5, ffl.player_match.drv_afl_status),
    backup_positions = $6,
    interchange_position = $7,
    display_order = $8,
    drv_score = COALESCE($9, ffl.player_match.drv_score),
    updated_at = CURRENT_TIMESTAMP
WHERE ffl.player_match.deleted_at IS NULL
RETURNING id, club_match_id, player_season_id, position, status, drv_afl_status, backup_positions, interchange_position, display_order, drv_score, afl_player_match_id
`

type UpsertPlayerMatchParams struct {
	ClubMatchID         int32
	PlayerSeasonID      int32
	Position            *string
	Status              *string
	DrvAflStatus        *string
	BackupPositions     *string
	InterchangePosition *string
	DisplayOrder        int32
	DrvScore            *int32
}

type UpsertPlayerMatchRow struct {
	ID                  int32
	ClubMatchID         int32
	PlayerSeasonID      int32
	Position            *string
	Status              *string
	DrvAflStatus        *string
	BackupPositions     *string
	InterchangePosition *string
	DisplayOrder        int32
	DrvScore            *int32
	AflPlayerMatchID    *int32
}

func (q *Queries) UpsertPlayerMatch(ctx context.Context, arg UpsertPlayerMatchParams) (UpsertPlayerMatchRow, error) {
	row := q.db.QueryRow(ctx, upsertPlayerMatch,
		arg.ClubMatchID,
		arg.PlayerSeasonID,
		arg.Position,
		arg.Status,
		arg.DrvAflStatus,
		arg.BackupPositions,
		arg.InterchangePosition,
		arg.DisplayOrder,
		arg.DrvScore,
	)
	var i UpsertPlayerMatchRow
	err := row.Scan(
		&i.ID,
		&i.ClubMatchID,
		&i.PlayerSeasonID,
		&i.Position,
		&i.Status,
		&i.DrvAflStatus,
		&i.BackupPositions,
		&i.InterchangePosition,
		&i.DisplayOrder,
		&i.DrvScore,
		&i.AflPlayerMatchID,
	)
	return i, err
}
