// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_match.sql

package sqlcgen

import (
	"context"
)

const findPlayerMatchByID = `-- name: FindPlayerMatchByID :one
SELECT id, club_match_id, player_season_id,
       position, status, backup_positions, interchange_position, drv_score, afl_player_match_id
FROM ffl.player_match
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerMatchByIDRow struct {
	ID                  int32
	ClubMatchID         int32
	PlayerSeasonID      int32
	Position            *string
	Status              *string
	BackupPositions     *string
	InterchangePosition *string
	DrvScore            *int32
	AflPlayerMatchID    *int32
}

func (q *Queries) FindPlayerMatchByID(ctx context.Context, id int32) (FindPlayerMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerMatchByID, id)
	var i FindPlayerMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClubMatchID,
		&i.PlayerSeasonID,
		&i.Position,
		&i.Status,
		&i.BackupPositions,
		&i.InterchangePosition,
		&i.DrvScore,
		&i.AflPlayerMatchID,
	)
	return i, err
}

const findPlayerMatchesByClubMatchID = `-- name: FindPlayerMatchesByClubMatchID :many
SELECT id, club_match_id, player_season_id,
       position, status, backup_positions, interchange_position, drv_score, afl_player_match_id
FROM ffl.player_match
WHERE club_match_id = $1 AND deleted_at IS NULL
`

type FindPlayerMatchesByClubMatchIDRow struct {
	ID                  int32
	ClubMatchID         int32
	PlayerSeasonID      int32
	Position            *string
	Status              *string
	BackupPositions     *string
	InterchangePosition *string
	DrvScore            *int32
	AflPlayerMatchID    *int32
}

func (q *Queries) FindPlayerMatchesByClubMatchID(ctx context.Context, clubMatchID int32) ([]FindPlayerMatchesByClubMatchIDRow, error) {
	rows, err := q.db.Query(ctx, findPlayerMatchesByClubMatchID, clubMatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerMatchesByClubMatchIDRow{}
	for rows.Next() {
		var i FindPlayerMatchesByClubMatchIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubMatchID,
			&i.PlayerSeasonID,
			&i.Position,
			&i.Status,
			&i.BackupPositions,
			&i.InterchangePosition,
			&i.DrvScore,
			&i.AflPlayerMatchID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayerMatch = `-- name: UpsertPlayerMatch :one
INSERT INTO ffl.player_match (club_match_id, player_season_id, position, status, backup_positions, interchange_position, drv_score)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (player_season_id, club_match_id)
DO UPDATE SET
    position = COALESCE($3, ffl.player_match.position),
    status = COALESCE($4, ffl.player_match.status),
    backup_positions = $5,
    interchange_position = $6,
    drv_score = COALESCE($7, ffl.player_match.drv_score),
    updated_at = CURRENT_TIMESTAMP
WHERE ffl.player_match.deleted_at IS NULL
RETURNING id, club_match_id, player_season_id, position, status, backup_positions, interchange_position, drv_score, afl_player_match_id
`

type UpsertPlayerMatchParams struct {
	ClubMatchID         int32
	PlayerSeasonID      int32
	Position            *string
	Status              *string
	BackupPositions     *string
	InterchangePosition *string
	DrvScore            *int32
}

type UpsertPlayerMatchRow struct {
	ID                  int32
	ClubMatchID         int32
	PlayerSeasonID      int32
	Position            *string
	Status              *string
	BackupPositions     *string
	InterchangePosition *string
	DrvScore            *int32
	AflPlayerMatchID    *int32
}

func (q *Queries) UpsertPlayerMatch(ctx context.Context, arg UpsertPlayerMatchParams) (UpsertPlayerMatchRow, error) {
	row := q.db.QueryRow(ctx, upsertPlayerMatch,
		arg.ClubMatchID,
		arg.PlayerSeasonID,
		arg.Position,
		arg.Status,
		arg.BackupPositions,
		arg.InterchangePosition,
		arg.DrvScore,
	)
	var i UpsertPlayerMatchRow
	err := row.Scan(
		&i.ID,
		&i.ClubMatchID,
		&i.PlayerSeasonID,
		&i.Position,
		&i.Status,
		&i.BackupPositions,
		&i.InterchangePosition,
		&i.DrvScore,
		&i.AflPlayerMatchID,
	)
	return i, err
}
