// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package sqlcgen

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO ffl.player (afl_player_id)
VALUES ($1)
RETURNING id, afl_player_id
`

type CreatePlayerRow struct {
	ID          int32
	AflPlayerID int32
}

func (q *Queries) CreatePlayer(ctx context.Context, aflPlayerID int32) (CreatePlayerRow, error) {
	row := q.db.QueryRow(ctx, createPlayer, aflPlayerID)
	var i CreatePlayerRow
	err := row.Scan(&i.ID, &i.AflPlayerID)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
UPDATE ffl.player
SET deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeletePlayer(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const findAllPlayers = `-- name: FindAllPlayers :many
SELECT id, afl_player_id
FROM ffl.player
WHERE deleted_at IS NULL
ORDER BY id
`

type FindAllPlayersRow struct {
	ID          int32
	AflPlayerID int32
}

func (q *Queries) FindAllPlayers(ctx context.Context) ([]FindAllPlayersRow, error) {
	rows, err := q.db.Query(ctx, findAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllPlayersRow{}
	for rows.Next() {
		var i FindAllPlayersRow
		if err := rows.Scan(&i.ID, &i.AflPlayerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayerByAFLPlayerID = `-- name: FindPlayerByAFLPlayerID :one
SELECT id, afl_player_id
FROM ffl.player
WHERE afl_player_id = $1 AND deleted_at IS NULL
`

type FindPlayerByAFLPlayerIDRow struct {
	ID          int32
	AflPlayerID int32
}

func (q *Queries) FindPlayerByAFLPlayerID(ctx context.Context, aflPlayerID int32) (FindPlayerByAFLPlayerIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerByAFLPlayerID, aflPlayerID)
	var i FindPlayerByAFLPlayerIDRow
	err := row.Scan(&i.ID, &i.AflPlayerID)
	return i, err
}

const findPlayerByID = `-- name: FindPlayerByID :one
SELECT id, afl_player_id
FROM ffl.player
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerByIDRow struct {
	ID          int32
	AflPlayerID int32
}

func (q *Queries) FindPlayerByID(ctx context.Context, id int32) (FindPlayerByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerByID, id)
	var i FindPlayerByIDRow
	err := row.Scan(&i.ID, &i.AflPlayerID)
	return i, err
}
