// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package sqlcgen

import (
	"context"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO ffl.player (name)
VALUES ($1)
RETURNING id, name
`

type CreatePlayerRow struct {
	ID   int32
	Name string
}

func (q *Queries) CreatePlayer(ctx context.Context, name string) (CreatePlayerRow, error) {
	row := q.db.QueryRow(ctx, createPlayer, name)
	var i CreatePlayerRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
UPDATE ffl.player
SET deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeletePlayer(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const findAllPlayers = `-- name: FindAllPlayers :many
SELECT id, name
FROM ffl.player
WHERE deleted_at IS NULL
ORDER BY name
`

type FindAllPlayersRow struct {
	ID   int32
	Name string
}

func (q *Queries) FindAllPlayers(ctx context.Context) ([]FindAllPlayersRow, error) {
	rows, err := q.db.Query(ctx, findAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllPlayersRow{}
	for rows.Next() {
		var i FindAllPlayersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayerByID = `-- name: FindPlayerByID :one
SELECT id, name
FROM ffl.player
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerByIDRow struct {
	ID   int32
	Name string
}

func (q *Queries) FindPlayerByID(ctx context.Context, id int32) (FindPlayerByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerByID, id)
	var i FindPlayerByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE ffl.player
SET name = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name
`

type UpdatePlayerParams struct {
	ID   int32
	Name string
}

type UpdatePlayerRow struct {
	ID   int32
	Name string
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (UpdatePlayerRow, error) {
	row := q.db.QueryRow(ctx, updatePlayer, arg.ID, arg.Name)
	var i UpdatePlayerRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
