// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_season.sql

package sqlcgen

import (
	"context"
)

const createPlayerSeason = `-- name: CreatePlayerSeason :one
INSERT INTO ffl.player_season (player_id, club_season_id, from_round_id, afl_player_season_id, cost_cents)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (player_id, club_season_id) DO UPDATE
  SET to_round_id = NULL,
      from_round_id = EXCLUDED.from_round_id,
      afl_player_season_id = EXCLUDED.afl_player_season_id,
      cost_cents = EXCLUDED.cost_cents,
      updated_at = CURRENT_TIMESTAMP
RETURNING id, player_id, club_season_id, afl_player_season_id, from_round_id, to_round_id, notes, cost_cents
`

type CreatePlayerSeasonParams struct {
	PlayerID          int32
	ClubSeasonID      int32
	FromRoundID       *int32
	AflPlayerSeasonID *int32
	CostCents         *int32
}

type CreatePlayerSeasonRow struct {
	ID                int32
	PlayerID          int32
	ClubSeasonID      int32
	AflPlayerSeasonID *int32
	FromRoundID       *int32
	ToRoundID         *int32
	Notes             *string
	CostCents         *int32
}

func (q *Queries) CreatePlayerSeason(ctx context.Context, arg CreatePlayerSeasonParams) (CreatePlayerSeasonRow, error) {
	row := q.db.QueryRow(ctx, createPlayerSeason,
		arg.PlayerID,
		arg.ClubSeasonID,
		arg.FromRoundID,
		arg.AflPlayerSeasonID,
		arg.CostCents,
	)
	var i CreatePlayerSeasonRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.ClubSeasonID,
		&i.AflPlayerSeasonID,
		&i.FromRoundID,
		&i.ToRoundID,
		&i.Notes,
		&i.CostCents,
	)
	return i, err
}

const deletePlayerSeason = `-- name: DeletePlayerSeason :exec
UPDATE ffl.player_season
SET deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeletePlayerSeason(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePlayerSeason, id)
	return err
}

const findPlayerSeasonByID = `-- name: FindPlayerSeasonByID :one
SELECT id, player_id, club_season_id, afl_player_season_id, from_round_id, to_round_id, notes, cost_cents
FROM ffl.player_season
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerSeasonByIDRow struct {
	ID                int32
	PlayerID          int32
	ClubSeasonID      int32
	AflPlayerSeasonID *int32
	FromRoundID       *int32
	ToRoundID         *int32
	Notes             *string
	CostCents         *int32
}

func (q *Queries) FindPlayerSeasonByID(ctx context.Context, id int32) (FindPlayerSeasonByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerSeasonByID, id)
	var i FindPlayerSeasonByIDRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.ClubSeasonID,
		&i.AflPlayerSeasonID,
		&i.FromRoundID,
		&i.ToRoundID,
		&i.Notes,
		&i.CostCents,
	)
	return i, err
}

const findPlayerSeasonsByAFLPlayerSeasonID = `-- name: FindPlayerSeasonsByAFLPlayerSeasonID :many
SELECT id, player_id, club_season_id, afl_player_season_id, from_round_id, to_round_id, notes, cost_cents
FROM ffl.player_season
WHERE afl_player_season_id = $1 AND deleted_at IS NULL
`

type FindPlayerSeasonsByAFLPlayerSeasonIDRow struct {
	ID                int32
	PlayerID          int32
	ClubSeasonID      int32
	AflPlayerSeasonID *int32
	FromRoundID       *int32
	ToRoundID         *int32
	Notes             *string
	CostCents         *int32
}

func (q *Queries) FindPlayerSeasonsByAFLPlayerSeasonID(ctx context.Context, aflPlayerSeasonID *int32) ([]FindPlayerSeasonsByAFLPlayerSeasonIDRow, error) {
	rows, err := q.db.Query(ctx, findPlayerSeasonsByAFLPlayerSeasonID, aflPlayerSeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerSeasonsByAFLPlayerSeasonIDRow{}
	for rows.Next() {
		var i FindPlayerSeasonsByAFLPlayerSeasonIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.ClubSeasonID,
			&i.AflPlayerSeasonID,
			&i.FromRoundID,
			&i.ToRoundID,
			&i.Notes,
			&i.CostCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayerSeasonsByClubSeasonID = `-- name: FindPlayerSeasonsByClubSeasonID :many
SELECT id, player_id, club_season_id, afl_player_season_id, from_round_id, to_round_id, notes, cost_cents
FROM ffl.player_season
WHERE club_season_id = $1 AND deleted_at IS NULL
ORDER BY to_round_id IS NOT NULL, id
`

type FindPlayerSeasonsByClubSeasonIDRow struct {
	ID                int32
	PlayerID          int32
	ClubSeasonID      int32
	AflPlayerSeasonID *int32
	FromRoundID       *int32
	ToRoundID         *int32
	Notes             *string
	CostCents         *int32
}

func (q *Queries) FindPlayerSeasonsByClubSeasonID(ctx context.Context, clubSeasonID int32) ([]FindPlayerSeasonsByClubSeasonIDRow, error) {
	rows, err := q.db.Query(ctx, findPlayerSeasonsByClubSeasonID, clubSeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerSeasonsByClubSeasonIDRow{}
	for rows.Next() {
		var i FindPlayerSeasonsByClubSeasonIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.ClubSeasonID,
			&i.AflPlayerSeasonID,
			&i.FromRoundID,
			&i.ToRoundID,
			&i.Notes,
			&i.CostCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayersByPlayerSeasonIDs = `-- name: FindPlayersByPlayerSeasonIDs :many
SELECT ps.id AS player_season_id, p.id AS player_id, p.afl_player_id
FROM ffl.player_season ps
JOIN ffl.player p ON p.id = ps.player_id
WHERE ps.id = ANY($1::int[]) AND ps.deleted_at IS NULL
`

type FindPlayersByPlayerSeasonIDsRow struct {
	PlayerSeasonID int32
	PlayerID       int32
	AflPlayerID    int32
}

func (q *Queries) FindPlayersByPlayerSeasonIDs(ctx context.Context, playerSeasonIds []int32) ([]FindPlayersByPlayerSeasonIDsRow, error) {
	rows, err := q.db.Query(ctx, findPlayersByPlayerSeasonIDs, playerSeasonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayersByPlayerSeasonIDsRow{}
	for rows.Next() {
		var i FindPlayersByPlayerSeasonIDsRow
		if err := rows.Scan(&i.PlayerSeasonID, &i.PlayerID, &i.AflPlayerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPlayerSeasonEndRound = `-- name: SetPlayerSeasonEndRound :exec
UPDATE ffl.player_season
SET to_round_id = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND deleted_at IS NULL
`

type SetPlayerSeasonEndRoundParams struct {
	ToRoundID *int32
	ID        int32
}

func (q *Queries) SetPlayerSeasonEndRound(ctx context.Context, arg SetPlayerSeasonEndRoundParams) error {
	_, err := q.db.Exec(ctx, setPlayerSeasonEndRound, arg.ToRoundID, arg.ID)
	return err
}

const updatePlayerSeason = `-- name: UpdatePlayerSeason :one
UPDATE ffl.player_season
SET notes = $1,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND deleted_at IS NULL
RETURNING id, player_id, club_season_id, afl_player_season_id, from_round_id, to_round_id, notes, cost_cents
`

type UpdatePlayerSeasonParams struct {
	Notes *string
	ID    int32
}

type UpdatePlayerSeasonRow struct {
	ID                int32
	PlayerID          int32
	ClubSeasonID      int32
	AflPlayerSeasonID *int32
	FromRoundID       *int32
	ToRoundID         *int32
	Notes             *string
	CostCents         *int32
}

func (q *Queries) UpdatePlayerSeason(ctx context.Context, arg UpdatePlayerSeasonParams) (UpdatePlayerSeasonRow, error) {
	row := q.db.QueryRow(ctx, updatePlayerSeason, arg.Notes, arg.ID)
	var i UpdatePlayerSeasonRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.ClubSeasonID,
		&i.AflPlayerSeasonID,
		&i.FromRoundID,
		&i.ToRoundID,
		&i.Notes,
		&i.CostCents,
	)
	return i, err
}
