// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	AllAFLStatusesFinal(ctx context.Context, clubMatchID int32) (bool, error)
	CountFinalClubMatchesByMatchID(ctx context.Context, matchID int32) (int64, error)
	CreateClub(ctx context.Context, name string) (CreateClubRow, error)
	CreateClubMatch(ctx context.Context, arg CreateClubMatchParams) (CreateClubMatchRow, error)
	CreateClubSeason(ctx context.Context, arg CreateClubSeasonParams) (CreateClubSeasonRow, error)
	CreateLeague(ctx context.Context, name string) (CreateLeagueRow, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (CreateMatchRow, error)
	CreatePlayer(ctx context.Context, aflPlayerID int32) (CreatePlayerRow, error)
	CreatePlayerSeason(ctx context.Context, arg CreatePlayerSeasonParams) (CreatePlayerSeasonRow, error)
	CreateRound(ctx context.Context, arg CreateRoundParams) (CreateRoundRow, error)
	CreateSeason(ctx context.Context, arg CreateSeasonParams) (CreateSeasonRow, error)
	DeletePlayer(ctx context.Context, id int32) error
	DeletePlayerMatchByID(ctx context.Context, id int32) error
	DeletePlayerMatchesByClubMatchID(ctx context.Context, clubMatchID int32) error
	DeletePlayerSeason(ctx context.Context, id int32) error
	FindAllClubs(ctx context.Context) ([]FindAllClubsRow, error)
	FindAllLeagues(ctx context.Context) ([]FindAllLeaguesRow, error)
	FindAllPlayers(ctx context.Context) ([]FindAllPlayersRow, error)
	FindAllSeasons(ctx context.Context) ([]FindAllSeasonsRow, error)
	FindClubByID(ctx context.Context, id int32) (FindClubByIDRow, error)
	FindClubByName(ctx context.Context, name string) (FindClubByNameRow, error)
	FindClubMatchByID(ctx context.Context, id int32) (FindClubMatchByIDRow, error)
	FindClubMatchesByIDs(ctx context.Context, dollar_1 []int32) ([]FindClubMatchesByIDsRow, error)
	FindClubMatchesByMatchID(ctx context.Context, matchID int32) ([]FindClubMatchesByMatchIDRow, error)
	FindClubSeasonByClubAndSeason(ctx context.Context, arg FindClubSeasonByClubAndSeasonParams) (FindClubSeasonByClubAndSeasonRow, error)
	FindClubSeasonByID(ctx context.Context, id int32) (FindClubSeasonByIDRow, error)
	FindClubSeasonsBySeasonID(ctx context.Context, seasonID int32) ([]FindClubSeasonsBySeasonIDRow, error)
	FindClubsByIDs(ctx context.Context, ids []int32) ([]FindClubsByIDsRow, error)
	FindFinalFflMatchesBySeasonID(ctx context.Context, seasonID int32) ([]FindFinalFflMatchesBySeasonIDRow, error)
	FindMatchByID(ctx context.Context, id int32) (FindMatchByIDRow, error)
	FindMatchesByIDs(ctx context.Context, ids []int32) ([]FindMatchesByIDsRow, error)
	FindMatchesByRoundID(ctx context.Context, roundID int32) ([]FindMatchesByRoundIDRow, error)
	FindPlayerByAFLPlayerID(ctx context.Context, aflPlayerID int32) (FindPlayerByAFLPlayerIDRow, error)
	FindPlayerByID(ctx context.Context, id int32) (FindPlayerByIDRow, error)
	FindPlayerMatchByID(ctx context.Context, id int32) (FindPlayerMatchByIDRow, error)
	FindPlayerMatchByPlayerSeasonAndRound(ctx context.Context, arg FindPlayerMatchByPlayerSeasonAndRoundParams) (FindPlayerMatchByPlayerSeasonAndRoundRow, error)
	FindPlayerMatchesByClubMatchID(ctx context.Context, clubMatchID int32) ([]FindPlayerMatchesByClubMatchIDRow, error)
	FindPlayerMatchesByPlayerSeasonID(ctx context.Context, playerSeasonID int32) ([]FindPlayerMatchesByPlayerSeasonIDRow, error)
	FindPlayerSeasonByID(ctx context.Context, id int32) (FindPlayerSeasonByIDRow, error)
	FindPlayerSeasonsByAFLPlayerSeasonID(ctx context.Context, aflPlayerSeasonID int32) ([]FindPlayerSeasonsByAFLPlayerSeasonIDRow, error)
	FindPlayerSeasonsByClubSeasonID(ctx context.Context, clubSeasonID int32) ([]FindPlayerSeasonsByClubSeasonIDRow, error)
	FindPlayerSeasonsByIDs(ctx context.Context, ids []int32) ([]FindPlayerSeasonsByIDsRow, error)
	FindPlayersByPlayerSeasonIDs(ctx context.Context, playerSeasonIds []int32) ([]FindPlayersByPlayerSeasonIDsRow, error)
	FindRoundByAFLRoundID(ctx context.Context, aflRoundID int32) (FindRoundByAFLRoundIDRow, error)
	FindRoundByID(ctx context.Context, id int32) (FindRoundByIDRow, error)
	FindRoundsBySeasonID(ctx context.Context, seasonID int32) ([]FindRoundsBySeasonIDRow, error)
	FindSeasonByID(ctx context.Context, id int32) (FindSeasonByIDRow, error)
	GetRulesIDByClubMatchID(ctx context.Context, id int32) (string, error)
	SetPlayerSeasonEndRound(ctx context.Context, arg SetPlayerSeasonEndRoundParams) error
	UpdateAFLPlayerMatchID(ctx context.Context, arg UpdateAFLPlayerMatchIDParams) error
	UpdateClubMatchDataStatus(ctx context.Context, arg UpdateClubMatchDataStatusParams) error
	UpdateClubMatchNotes(ctx context.Context, arg UpdateClubMatchNotesParams) error
	UpdateClubMatchPremiershipPoints(ctx context.Context, arg UpdateClubMatchPremiershipPointsParams) error
	UpdateClubMatchScore(ctx context.Context, arg UpdateClubMatchScoreParams) error
	UpdateDrvAFLStatus(ctx context.Context, arg UpdateDrvAFLStatusParams) error
	UpdateFflClubSeason(ctx context.Context, arg UpdateFflClubSeasonParams) error
	UpdateFflMatchResult(ctx context.Context, arg UpdateFflMatchResultParams) error
	UpdatePlayerMatchDisplayOrder(ctx context.Context, arg UpdatePlayerMatchDisplayOrderParams) error
	UpdatePlayerMatchPosition(ctx context.Context, arg UpdatePlayerMatchPositionParams) error
	UpdatePlayerMatchStatus(ctx context.Context, arg UpdatePlayerMatchStatusParams) error
	UpdatePlayerSeason(ctx context.Context, arg UpdatePlayerSeasonParams) (UpdatePlayerSeasonRow, error)
	UpsertPlayerMatch(ctx context.Context, arg UpsertPlayerMatchParams) (UpsertPlayerMatchRow, error)
}

var _ Querier = (*Queries)(nil)
