// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: round.sql

package sqlcgen

import (
	"context"
)

const findRoundByAFLRoundID = `-- name: FindRoundByAFLRoundID :one
SELECT id, name, season_id, afl_round_id
FROM ffl.round
WHERE afl_round_id = $1 AND deleted_at IS NULL
`

type FindRoundByAFLRoundIDRow struct {
	ID         int32
	Name       string
	SeasonID   int32
	AflRoundID *int32
}

func (q *Queries) FindRoundByAFLRoundID(ctx context.Context, aflRoundID *int32) (FindRoundByAFLRoundIDRow, error) {
	row := q.db.QueryRow(ctx, findRoundByAFLRoundID, aflRoundID)
	var i FindRoundByAFLRoundIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SeasonID,
		&i.AflRoundID,
	)
	return i, err
}

const findRoundByID = `-- name: FindRoundByID :one
SELECT id, name, season_id, afl_round_id
FROM ffl.round
WHERE id = $1 AND deleted_at IS NULL
`

type FindRoundByIDRow struct {
	ID         int32
	Name       string
	SeasonID   int32
	AflRoundID *int32
}

func (q *Queries) FindRoundByID(ctx context.Context, id int32) (FindRoundByIDRow, error) {
	row := q.db.QueryRow(ctx, findRoundByID, id)
	var i FindRoundByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.SeasonID, &i.AflRoundID)
	return i, err
}

const findRoundsBySeasonID = `-- name: FindRoundsBySeasonID :many
SELECT r.id, r.name, r.season_id, r.afl_round_id
FROM ffl.round r
LEFT JOIN ffl.match m ON m.round_id = r.id AND m.deleted_at IS NULL
WHERE r.season_id = $1 AND r.deleted_at IS NULL
GROUP BY r.id, r.name, r.season_id, r.afl_round_id
ORDER BY MIN(m.start_dt) NULLS LAST, r.id
`

type FindRoundsBySeasonIDRow struct {
	ID         int32
	Name       string
	SeasonID   int32
	AflRoundID *int32
}

func (q *Queries) FindRoundsBySeasonID(ctx context.Context, seasonID int32) ([]FindRoundsBySeasonIDRow, error) {
	rows, err := q.db.Query(ctx, findRoundsBySeasonID, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRoundsBySeasonIDRow{}
	for rows.Next() {
		var i FindRoundsBySeasonIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SeasonID, &i.AflRoundID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
