// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: round.sql

package sqlcgen

import (
	"context"
)

const createRound = `-- name: CreateRound :one
INSERT INTO ffl.round (season_id, name, afl_round_id, round_type)
VALUES ($1, $2, $3, $4)
RETURNING id, name, season_id, afl_round_id, round_type
`

type CreateRoundParams struct {
	SeasonID   int32
	Name       string
	AflRoundID int32
	RoundType  string
}

type CreateRoundRow struct {
	ID         int32
	Name       string
	SeasonID   int32
	AflRoundID int32
	RoundType  string
}

func (q *Queries) CreateRound(ctx context.Context, arg CreateRoundParams) (CreateRoundRow, error) {
	row := q.db.QueryRow(ctx, createRound,
		arg.SeasonID,
		arg.Name,
		arg.AflRoundID,
		arg.RoundType,
	)
	var i CreateRoundRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SeasonID,
		&i.AflRoundID,
		&i.RoundType,
	)
	return i, err
}

const findRoundByAFLRoundID = `-- name: FindRoundByAFLRoundID :one
SELECT id, name, season_id, afl_round_id
FROM ffl.round
WHERE afl_round_id = $1 AND deleted_at IS NULL
`

type FindRoundByAFLRoundIDRow struct {
	ID         int32
	Name       string
	SeasonID   int32
	AflRoundID int32
}

func (q *Queries) FindRoundByAFLRoundID(ctx context.Context, aflRoundID int32) (FindRoundByAFLRoundIDRow, error) {
	row := q.db.QueryRow(ctx, findRoundByAFLRoundID, aflRoundID)
	var i FindRoundByAFLRoundIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SeasonID,
		&i.AflRoundID,
	)
	return i, err
}

const findRoundByID = `-- name: FindRoundByID :one
SELECT id, name, season_id, afl_round_id, round_type
FROM ffl.round
WHERE id = $1 AND deleted_at IS NULL
`

type FindRoundByIDRow struct {
	ID         int32
	Name       string
	SeasonID   int32
	AflRoundID int32
	RoundType  string
}

func (q *Queries) FindRoundByID(ctx context.Context, id int32) (FindRoundByIDRow, error) {
	row := q.db.QueryRow(ctx, findRoundByID, id)
	var i FindRoundByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SeasonID,
		&i.AflRoundID,
		&i.RoundType,
	)
	return i, err
}

const findRoundsBySeasonID = `-- name: FindRoundsBySeasonID :many
SELECT r.id, r.name, r.season_id, r.afl_round_id, r.round_type
FROM ffl.round r
LEFT JOIN ffl.match m ON m.round_id = r.id AND m.deleted_at IS NULL
WHERE r.season_id = $1 AND r.deleted_at IS NULL
GROUP BY r.id, r.name, r.season_id, r.afl_round_id, r.round_type
ORDER BY MIN(m.start_dt) NULLS LAST, r.id
`

type FindRoundsBySeasonIDRow struct {
	ID         int32
	Name       string
	SeasonID   int32
	AflRoundID int32
	RoundType  string
}

func (q *Queries) FindRoundsBySeasonID(ctx context.Context, seasonID int32) ([]FindRoundsBySeasonIDRow, error) {
	rows, err := q.db.Query(ctx, findRoundsBySeasonID, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRoundsBySeasonIDRow{}
	for rows.Next() {
		var i FindRoundsBySeasonIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SeasonID,
			&i.AflRoundID,
			&i.RoundType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRound = `-- name: SoftDeleteRound :exec
UPDATE ffl.round
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRound(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteRound, id)
	return err
}

const updateRound = `-- name: UpdateRound :exec
UPDATE ffl.round
SET name = $2, afl_round_id = $3, round_type = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateRoundParams struct {
	ID         int32
	Name       string
	AflRoundID int32
	RoundType  string
}

func (q *Queries) UpdateRound(ctx context.Context, arg UpdateRoundParams) error {
	_, err := q.db.Exec(ctx, updateRound,
		arg.ID,
		arg.Name,
		arg.AflRoundID,
		arg.RoundType,
	)
	return err
}
