// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: round.sql

package sqlcgen

import (
	"context"
)

const findLatestRound = `-- name: FindLatestRound :one
SELECT r.id, r.name, r.season_id
FROM ffl.round r
JOIN ffl.season s ON s.id = r.season_id AND s.deleted_at IS NULL
WHERE r.deleted_at IS NULL
ORDER BY s.id DESC, r.id DESC
LIMIT 1
`

type FindLatestRoundRow struct {
	ID       int32
	Name     string
	SeasonID int32
}

func (q *Queries) FindLatestRound(ctx context.Context) (FindLatestRoundRow, error) {
	row := q.db.QueryRow(ctx, findLatestRound)
	var i FindLatestRoundRow
	err := row.Scan(&i.ID, &i.Name, &i.SeasonID)
	return i, err
}

const findRoundByAFLRoundID = `-- name: FindRoundByAFLRoundID :one
SELECT id, name, season_id, afl_round_id
FROM ffl.round
WHERE afl_round_id = $1 AND deleted_at IS NULL
`

type FindRoundByAFLRoundIDRow struct {
	ID         int32
	Name       string
	SeasonID   int32
	AflRoundID *int32
}

func (q *Queries) FindRoundByAFLRoundID(ctx context.Context, aflRoundID *int32) (FindRoundByAFLRoundIDRow, error) {
	row := q.db.QueryRow(ctx, findRoundByAFLRoundID, aflRoundID)
	var i FindRoundByAFLRoundIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SeasonID,
		&i.AflRoundID,
	)
	return i, err
}

const findRoundByID = `-- name: FindRoundByID :one
SELECT id, name, season_id
FROM ffl.round
WHERE id = $1 AND deleted_at IS NULL
`

type FindRoundByIDRow struct {
	ID       int32
	Name     string
	SeasonID int32
}

func (q *Queries) FindRoundByID(ctx context.Context, id int32) (FindRoundByIDRow, error) {
	row := q.db.QueryRow(ctx, findRoundByID, id)
	var i FindRoundByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.SeasonID)
	return i, err
}

const findRoundsBySeasonID = `-- name: FindRoundsBySeasonID :many
SELECT id, name, season_id
FROM ffl.round
WHERE season_id = $1 AND deleted_at IS NULL
ORDER BY id
`

type FindRoundsBySeasonIDRow struct {
	ID       int32
	Name     string
	SeasonID int32
}

func (q *Queries) FindRoundsBySeasonID(ctx context.Context, seasonID int32) ([]FindRoundsBySeasonIDRow, error) {
	rows, err := q.db.Query(ctx, findRoundsBySeasonID, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRoundsBySeasonIDRow{}
	for rows.Next() {
		var i FindRoundsBySeasonIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SeasonID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
