// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: season.sql

package sqlcgen

import (
	"context"
)

const findAllSeasons = `-- name: FindAllSeasons :many
SELECT id, name, league_id, afl_season_id
FROM ffl.season
WHERE deleted_at IS NULL
ORDER BY name
`

type FindAllSeasonsRow struct {
	ID          int32
	Name        string
	LeagueID    int32
	AflSeasonID *int32
}

func (q *Queries) FindAllSeasons(ctx context.Context) ([]FindAllSeasonsRow, error) {
	rows, err := q.db.Query(ctx, findAllSeasons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllSeasonsRow{}
	for rows.Next() {
		var i FindAllSeasonsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LeagueID,
			&i.AflSeasonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSeasonByID = `-- name: FindSeasonByID :one
SELECT id, name, league_id, afl_season_id
FROM ffl.season
WHERE id = $1 AND deleted_at IS NULL
`

type FindSeasonByIDRow struct {
	ID          int32
	Name        string
	LeagueID    int32
	AflSeasonID *int32
}

func (q *Queries) FindSeasonByID(ctx context.Context, id int32) (FindSeasonByIDRow, error) {
	row := q.db.QueryRow(ctx, findSeasonByID, id)
	var i FindSeasonByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LeagueID,
		&i.AflSeasonID,
	)
	return i, err
}
