-- Auto-generated by resolve_squads.py -- do not edit manually
-- Source: dev/import/ffl/squads_review.csv
BEGIN;

-- Cheetahs

INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 460, 'Lachlan McAndrew'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 460);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 169, 'Darcy Fogarty'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 169);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 774, 'Will Ashcroft'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 774);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 450, 'Lachie Neale'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 450);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 587, 'Nick Haynes'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 587);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 582, 'Nic Newman'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 582);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 100, 'Caleb Serong'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 100);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 708, 'Tanner Bruhn'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 708);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 533, 'Matt Rowell'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 533);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 56, 'Ben King'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 56);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 440, 'Kieren Briggs'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 440);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 135, 'Clayton Oliver'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 135);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 490, 'Lloyd Meek'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 490);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 760, 'Tristan Xerri'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 760);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 246, 'Harry Sheezel'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 246);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 138, 'Colby McKercher'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 138);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 590, 'Nick Larkey'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 590);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 759, 'Trent Rivers'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 759);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 367, 'Jayden Short'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 367);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 676, 'Sam Lalor'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 676);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 301, 'Jack Sinclair'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 301);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 264, 'Hugo Garcia'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 264);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 535, 'Mattaes Phillipou'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 535);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 205, 'Errol Gulden'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 205);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 346, 'James Rowbottom'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 346);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 269, 'Isaac Heeney'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 269);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 122, 'Charlie Curnow'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 122);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 715, 'Tim English'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 715);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 3, 'Aaron Naughton'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 3);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 658, 'Ryley Sanders'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 658);

INSERT INTO ffl.player_season (player_id, club_season_id, from_round_id, afl_player_season_id)
SELECT
    fp.id,
    (SELECT cs.id FROM ffl.club_season cs
     JOIN ffl.club c ON cs.club_id = c.id
     JOIN ffl.season s ON cs.season_id = s.id
     WHERE c.name = 'Cheetahs' AND s.name = 'FFL 2026'),
    (SELECT r.id FROM ffl.round r
     JOIN ffl.season s ON r.season_id = s.id
     WHERE r.name = 'Round 1' AND s.name = 'FFL 2026'),
    (SELECT aps.id FROM afl.player_season aps
     JOIN afl.club_season acs ON aps.club_season_id = acs.id
     JOIN afl.season asn ON acs.season_id = asn.id
     WHERE aps.player_id = fp.afl_player_id AND asn.name = 'AFL 2026')
FROM (VALUES
    (460),
    (169),
    (774),
    (450),
    (587),
    (582),
    (100),
    (708),
    (533),
    (56),
    (440),
    (135),
    (490),
    (760),
    (246),
    (138),
    (590),
    (759),
    (367),
    (676),
    (301),
    (264),
    (535),
    (205),
    (346),
    (269),
    (122),
    (715),
    (3),
    (658)
) AS v(afl_player_id)
JOIN ffl.player fp ON fp.afl_player_id = v.afl_player_id
ON CONFLICT (player_id, club_season_id) DO NOTHING;

-- The Howling Cows

INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 397, 'Jordan Dawson'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 397);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 644, 'Riley Thilthorpe'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 644);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 317, 'Jacob Weitering'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 317);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 168, 'Darcy Cameron'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 168);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 586, 'Nick Daicos'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 586);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 352, 'Jamie Elliott'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 352);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 786, 'Will Setterfield'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 786);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 525, 'Mason Redman'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 525);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 509, 'Luke Ryan'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 509);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 756, 'Tom Stewart'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 756);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 757, 'Touk Miller'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 757);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 596, 'Noah Anderson'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 596);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 132, 'Christian Petracca'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 132);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 392, 'John Noble'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 392);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 722, 'Toby Greene'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 722);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 236, 'Harry Himmelberg'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 236);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 379, 'Jesse Hogan'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 379);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 287, 'Jack Gunston'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 287);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 302, 'Jack Steele'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 302);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 401, 'Jordon Sweet'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 401);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 804, 'Zak Butters'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 804);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 143, 'Connor Rozee'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 143);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 611, 'Ollie Wines'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 611);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 725, 'Toby Nankervis'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 725);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 312, 'Jacob Hopper'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 312);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 651, 'Rowan Marshall'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 651);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 330, 'Jake Lloyd'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 330);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 583, 'Nick Blakey'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 583);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 286, 'Jack Graham'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 286);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 517, 'Marcus Bontempelli'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 517);

INSERT INTO ffl.player_season (player_id, club_season_id, from_round_id, afl_player_season_id)
SELECT
    fp.id,
    (SELECT cs.id FROM ffl.club_season cs
     JOIN ffl.club c ON cs.club_id = c.id
     JOIN ffl.season s ON cs.season_id = s.id
     WHERE c.name = 'The Howling Cows' AND s.name = 'FFL 2026'),
    (SELECT r.id FROM ffl.round r
     JOIN ffl.season s ON r.season_id = s.id
     WHERE r.name = 'Round 1' AND s.name = 'FFL 2026'),
    (SELECT aps.id FROM afl.player_season aps
     JOIN afl.club_season acs ON aps.club_season_id = acs.id
     JOIN afl.season asn ON acs.season_id = asn.id
     WHERE aps.player_id = fp.afl_player_id AND asn.name = 'AFL 2026')
FROM (VALUES
    (397),
    (644),
    (317),
    (168),
    (586),
    (352),
    (786),
    (525),
    (509),
    (756),
    (757),
    (596),
    (132),
    (392),
    (722),
    (236),
    (379),
    (287),
    (302),
    (401),
    (804),
    (143),
    (611),
    (725),
    (312),
    (651),
    (330),
    (583),
    (286),
    (517)
) AS v(afl_player_id)
JOIN ffl.player fp ON fp.afl_player_id = v.afl_player_id
ON CONFLICT (player_id, club_season_id) DO NOTHING;

-- Ruiboys

INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 633, 'Reilly OBrien'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 633);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 711, 'Taylor Walker'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 711);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 256, 'Henry Smith'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 256);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 263, 'Hugh McCluggage'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 263);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 182, 'Dayne Zorko'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 182);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 228, 'Harris Andrews'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 228);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 221, 'George Hewett'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 221);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 150, 'Cooper Lord'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 150);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 576, 'Ned Long'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 576);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 404, 'Josh Daicos'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 404);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 427, 'Jye Caldwell'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 427);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 504, 'Luke Jackson'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 504);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 729, 'Tom Atkins'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 729);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 373, 'Jeremy Cameron'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 373);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 11, 'Alex Davies'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 11);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 338, 'Jamarra Ugle-Hagan'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 338);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 445, 'Lachie Ash'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 445);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 140, 'Connor Idun'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 140);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 436, 'Karl Amon'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 436);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 753, 'Tom Powell'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 753);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 544, 'Max Gawn'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 544);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 788, 'Willem Drew'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 788);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 560, 'Mitch Georgiades'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 560);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 718, 'Tim Taranto'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 718);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 294, 'Jack Macrae'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 294);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 518, 'Marcus Windhager'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 518);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 108, 'Callum Wilkie'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 108);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 540, 'Matthew Kennedy'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 540);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 665, 'Sam Darcy'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 665);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 42, 'Bailey Dale'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 42);

INSERT INTO ffl.player_season (player_id, club_season_id, from_round_id, afl_player_season_id)
SELECT
    fp.id,
    (SELECT cs.id FROM ffl.club_season cs
     JOIN ffl.club c ON cs.club_id = c.id
     JOIN ffl.season s ON cs.season_id = s.id
     WHERE c.name = 'Ruiboys' AND s.name = 'FFL 2026'),
    (SELECT r.id FROM ffl.round r
     JOIN ffl.season s ON r.season_id = s.id
     WHERE r.name = 'Round 1' AND s.name = 'FFL 2026'),
    (SELECT aps.id FROM afl.player_season aps
     JOIN afl.club_season acs ON aps.club_season_id = acs.id
     JOIN afl.season asn ON acs.season_id = asn.id
     WHERE aps.player_id = fp.afl_player_id AND asn.name = 'AFL 2026')
FROM (VALUES
    (633),
    (711),
    (256),
    (263),
    (182),
    (228),
    (221),
    (150),
    (576),
    (404),
    (427),
    (504),
    (729),
    (373),
    (11),
    (338),
    (445),
    (140),
    (436),
    (753),
    (544),
    (788),
    (560),
    (718),
    (294),
    (518),
    (108),
    (540),
    (665),
    (42)
) AS v(afl_player_id)
JOIN ffl.player fp ON fp.afl_player_id = v.afl_player_id
ON CONFLICT (player_id, club_season_id) DO NOTHING;

-- Slashers

INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 407, 'Josh Dunkley'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 407);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 494, 'Logan Morris'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 494);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 516, 'Marc Pittonet'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 516);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 622, 'Patrick Cripps'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 622);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 683, 'Sam Walsh'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 683);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 238, 'Harry McKay'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 238);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 321, 'Jagga Smith'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 321);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 800, 'Zach Merrett'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 800);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 175, 'Darcy Parish'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 175);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 23, 'Andrew McGrath'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 23);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 21, 'Andrew Brayshaw'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 21);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 626, 'Patrick Voss'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 626);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 47, 'Bailey Smith'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 47);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 548, 'Max Holmes'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 548);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 355, 'Jarrod Witts'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 355);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 212, 'Finn Callaghan'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 212);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 453, 'Lachie Whitfield'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 453);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 1, 'Aaron Cadman'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 1);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 323, 'Jai Newcombe'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 323);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 145, 'Conor Nash'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 145);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 347, 'James Sicily'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 347);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 133, 'Christian Salem'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 133);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 737, 'Tom De Koning'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 737);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 570, 'Nasiah Wanganeen-Milera'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 570);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 673, 'Sam Flanders'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 673);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 88, 'Brodie Grundy'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 88);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 336, 'Jake Waterman'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 336);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 746, 'Tom Liberatore'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 746);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 196, 'Ed Richards'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 196);
INSERT INTO ffl.player (afl_player_id, drv_name)
SELECT 389, 'Joel Freijah'
WHERE NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = 389);

INSERT INTO ffl.player_season (player_id, club_season_id, from_round_id, afl_player_season_id)
SELECT
    fp.id,
    (SELECT cs.id FROM ffl.club_season cs
     JOIN ffl.club c ON cs.club_id = c.id
     JOIN ffl.season s ON cs.season_id = s.id
     WHERE c.name = 'Slashers' AND s.name = 'FFL 2026'),
    (SELECT r.id FROM ffl.round r
     JOIN ffl.season s ON r.season_id = s.id
     WHERE r.name = 'Round 1' AND s.name = 'FFL 2026'),
    (SELECT aps.id FROM afl.player_season aps
     JOIN afl.club_season acs ON aps.club_season_id = acs.id
     JOIN afl.season asn ON acs.season_id = asn.id
     WHERE aps.player_id = fp.afl_player_id AND asn.name = 'AFL 2026')
FROM (VALUES
    (407),
    (494),
    (516),
    (622),
    (683),
    (238),
    (321),
    (800),
    (175),
    (23),
    (21),
    (626),
    (47),
    (548),
    (355),
    (212),
    (453),
    (1),
    (323),
    (145),
    (347),
    (133),
    (737),
    (570),
    (673),
    (88),
    (336),
    (746),
    (196),
    (389)
) AS v(afl_player_id)
JOIN ffl.player fp ON fp.afl_player_id = v.afl_player_id
ON CONFLICT (player_id, club_season_id) DO NOTHING;

COMMIT;
