-- Auto-generated by resolve_squads.py -- do not edit manually
-- Source: dev/import/ffl/squads_review.csv
BEGIN;

-- Cheetahs

INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Lachlan McAndrew'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Darcy Fogarty'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Will Ashcroft'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Lachie Neale'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Nick Haynes'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Nic Newman'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Caleb Serong'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Tanner Bruhn'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Matt Rowell'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Ben King'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Kieren Briggs'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Clayton Oliver'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Lloyd Meek'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Tristan Xerri'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Harry Sheezel'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Colby McKercher'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Nick Larkey'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Trent Rivers'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jayden Short'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Sam Lalor'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jack Sinclair'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Hugo Garcia'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Mattaes Phillipou'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Errol Gulden'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'James Rowbottom'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Isaac Heeney'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Charlie Curnow'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Tim English'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Aaron Naughton'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Ryley Sanders'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);

INSERT INTO ffl.player_season (player_id, club_season_id, from_round_id, afl_player_season_id)
SELECT
    fp.id,
    (SELECT cs.id FROM ffl.club_season cs JOIN ffl.club c ON cs.club_id = c.id JOIN ffl.season s ON cs.season_id = s.id WHERE c.name = 'Cheetahs' AND s.name = 'FFL 2026'),
    (SELECT r.id FROM ffl.round r JOIN ffl.season s ON r.season_id = s.id WHERE r.name = 'Round 1' AND s.name = 'FFL 2026'),
    (SELECT aps.id FROM afl.player_season aps JOIN afl.club_season acs ON aps.club_season_id = acs.id JOIN afl.season asn ON acs.season_id = asn.id WHERE aps.player_id = fp.afl_player_id AND asn.name = 'AFL 2026')
FROM (VALUES
    ('Lachlan McAndrew'),
    ('Darcy Fogarty'),
    ('Will Ashcroft'),
    ('Lachie Neale'),
    ('Nick Haynes'),
    ('Nic Newman'),
    ('Caleb Serong'),
    ('Tanner Bruhn'),
    ('Matt Rowell'),
    ('Ben King'),
    ('Kieren Briggs'),
    ('Clayton Oliver'),
    ('Lloyd Meek'),
    ('Tristan Xerri'),
    ('Harry Sheezel'),
    ('Colby McKercher'),
    ('Nick Larkey'),
    ('Trent Rivers'),
    ('Jayden Short'),
    ('Sam Lalor'),
    ('Jack Sinclair'),
    ('Hugo Garcia'),
    ('Mattaes Phillipou'),
    ('Errol Gulden'),
    ('James Rowbottom'),
    ('Isaac Heeney'),
    ('Charlie Curnow'),
    ('Tim English'),
    ('Aaron Naughton'),
    ('Ryley Sanders')
) AS v(afl_player_name)
JOIN afl.player ap ON ap.name = v.afl_player_name
JOIN ffl.player fp ON fp.afl_player_id = ap.id
ON CONFLICT (player_id, club_season_id) DO NOTHING;

-- The Howling Cows

INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jordan Dawson'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Riley Thilthorpe'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jacob Weitering'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Darcy Cameron'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Nick Daicos'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jamie Elliott'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Will Setterfield'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Mason Redman'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Luke Ryan'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Tom Stewart'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Touk Miller'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Noah Anderson'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Christian Petracca'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'John Noble'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Toby Greene'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Harry Himmelberg'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jesse Hogan'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jack Gunston'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jack Steele'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jordon Sweet'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Zak Butters'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Connor Rozee'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Ollie Wines'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Toby Nankervis'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jacob Hopper'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Rowan Marshall'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jake Lloyd'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Nick Blakey'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jack Graham'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Marcus Bontempelli'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);

INSERT INTO ffl.player_season (player_id, club_season_id, from_round_id, afl_player_season_id)
SELECT
    fp.id,
    (SELECT cs.id FROM ffl.club_season cs JOIN ffl.club c ON cs.club_id = c.id JOIN ffl.season s ON cs.season_id = s.id WHERE c.name = 'The Howling Cows' AND s.name = 'FFL 2026'),
    (SELECT r.id FROM ffl.round r JOIN ffl.season s ON r.season_id = s.id WHERE r.name = 'Round 1' AND s.name = 'FFL 2026'),
    (SELECT aps.id FROM afl.player_season aps JOIN afl.club_season acs ON aps.club_season_id = acs.id JOIN afl.season asn ON acs.season_id = asn.id WHERE aps.player_id = fp.afl_player_id AND asn.name = 'AFL 2026')
FROM (VALUES
    ('Jordan Dawson'),
    ('Riley Thilthorpe'),
    ('Jacob Weitering'),
    ('Darcy Cameron'),
    ('Nick Daicos'),
    ('Jamie Elliott'),
    ('Will Setterfield'),
    ('Mason Redman'),
    ('Luke Ryan'),
    ('Tom Stewart'),
    ('Touk Miller'),
    ('Noah Anderson'),
    ('Christian Petracca'),
    ('John Noble'),
    ('Toby Greene'),
    ('Harry Himmelberg'),
    ('Jesse Hogan'),
    ('Jack Gunston'),
    ('Jack Steele'),
    ('Jordon Sweet'),
    ('Zak Butters'),
    ('Connor Rozee'),
    ('Ollie Wines'),
    ('Toby Nankervis'),
    ('Jacob Hopper'),
    ('Rowan Marshall'),
    ('Jake Lloyd'),
    ('Nick Blakey'),
    ('Jack Graham'),
    ('Marcus Bontempelli')
) AS v(afl_player_name)
JOIN afl.player ap ON ap.name = v.afl_player_name
JOIN ffl.player fp ON fp.afl_player_id = ap.id
ON CONFLICT (player_id, club_season_id) DO NOTHING;

-- Ruiboys

INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Reilly OBrien'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Taylor Walker'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Henry Smith'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Hugh McCluggage'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Dayne Zorko'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Harris Andrews'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'George Hewett'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Cooper Lord'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Ned Long'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Josh Daicos'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jye Caldwell'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Luke Jackson'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Tom Atkins'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jeremy Cameron'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Alex Davies'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jamarra Ugle-Hagan'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Lachie Ash'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Connor Idun'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Karl Amon'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Tom Powell'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Max Gawn'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Willem Drew'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Mitch Georgiades'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Tim Taranto'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jack Macrae'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Marcus Windhager'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Callum Wilkie'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Matthew Kennedy'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Sam Darcy'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Bailey Dale'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);

INSERT INTO ffl.player_season (player_id, club_season_id, from_round_id, afl_player_season_id)
SELECT
    fp.id,
    (SELECT cs.id FROM ffl.club_season cs JOIN ffl.club c ON cs.club_id = c.id JOIN ffl.season s ON cs.season_id = s.id WHERE c.name = 'Ruiboys' AND s.name = 'FFL 2026'),
    (SELECT r.id FROM ffl.round r JOIN ffl.season s ON r.season_id = s.id WHERE r.name = 'Round 1' AND s.name = 'FFL 2026'),
    (SELECT aps.id FROM afl.player_season aps JOIN afl.club_season acs ON aps.club_season_id = acs.id JOIN afl.season asn ON acs.season_id = asn.id WHERE aps.player_id = fp.afl_player_id AND asn.name = 'AFL 2026')
FROM (VALUES
    ('Reilly OBrien'),
    ('Taylor Walker'),
    ('Henry Smith'),
    ('Hugh McCluggage'),
    ('Dayne Zorko'),
    ('Harris Andrews'),
    ('George Hewett'),
    ('Cooper Lord'),
    ('Ned Long'),
    ('Josh Daicos'),
    ('Jye Caldwell'),
    ('Luke Jackson'),
    ('Tom Atkins'),
    ('Jeremy Cameron'),
    ('Alex Davies'),
    ('Jamarra Ugle-Hagan'),
    ('Lachie Ash'),
    ('Connor Idun'),
    ('Karl Amon'),
    ('Tom Powell'),
    ('Max Gawn'),
    ('Willem Drew'),
    ('Mitch Georgiades'),
    ('Tim Taranto'),
    ('Jack Macrae'),
    ('Marcus Windhager'),
    ('Callum Wilkie'),
    ('Matthew Kennedy'),
    ('Sam Darcy'),
    ('Bailey Dale')
) AS v(afl_player_name)
JOIN afl.player ap ON ap.name = v.afl_player_name
JOIN ffl.player fp ON fp.afl_player_id = ap.id
ON CONFLICT (player_id, club_season_id) DO NOTHING;

-- Slashers

INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Josh Dunkley'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Logan Morris'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Marc Pittonet'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Patrick Cripps'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Sam Walsh'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Harry McKay'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jagga Smith'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Zach Merrett'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Darcy Parish'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Andrew McGrath'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Andrew Brayshaw'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Patrick Voss'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Bailey Smith'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Max Holmes'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jarrod Witts'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Finn Callaghan'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Lachie Whitfield'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Aaron Cadman'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jai Newcombe'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Conor Nash'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'James Sicily'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Christian Salem'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Tom De Koning'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Nasiah Wanganeen-Milera'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Sam Flanders'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Brodie Grundy'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Jake Waterman'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Tom Liberatore'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Ed Richards'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);
INSERT INTO ffl.player (afl_player_id)
SELECT ap.id FROM afl.player ap WHERE ap.name = 'Joel Freijah'
AND NOT EXISTS (SELECT 1 FROM ffl.player WHERE afl_player_id = ap.id);

INSERT INTO ffl.player_season (player_id, club_season_id, from_round_id, afl_player_season_id)
SELECT
    fp.id,
    (SELECT cs.id FROM ffl.club_season cs JOIN ffl.club c ON cs.club_id = c.id JOIN ffl.season s ON cs.season_id = s.id WHERE c.name = 'Slashers' AND s.name = 'FFL 2026'),
    (SELECT r.id FROM ffl.round r JOIN ffl.season s ON r.season_id = s.id WHERE r.name = 'Round 1' AND s.name = 'FFL 2026'),
    (SELECT aps.id FROM afl.player_season aps JOIN afl.club_season acs ON aps.club_season_id = acs.id JOIN afl.season asn ON acs.season_id = asn.id WHERE aps.player_id = fp.afl_player_id AND asn.name = 'AFL 2026')
FROM (VALUES
    ('Josh Dunkley'),
    ('Logan Morris'),
    ('Marc Pittonet'),
    ('Patrick Cripps'),
    ('Sam Walsh'),
    ('Harry McKay'),
    ('Jagga Smith'),
    ('Zach Merrett'),
    ('Darcy Parish'),
    ('Andrew McGrath'),
    ('Andrew Brayshaw'),
    ('Patrick Voss'),
    ('Bailey Smith'),
    ('Max Holmes'),
    ('Jarrod Witts'),
    ('Finn Callaghan'),
    ('Lachie Whitfield'),
    ('Aaron Cadman'),
    ('Jai Newcombe'),
    ('Conor Nash'),
    ('James Sicily'),
    ('Christian Salem'),
    ('Tom De Koning'),
    ('Nasiah Wanganeen-Milera'),
    ('Sam Flanders'),
    ('Brodie Grundy'),
    ('Jake Waterman'),
    ('Tom Liberatore'),
    ('Ed Richards'),
    ('Joel Freijah')
) AS v(afl_player_name)
JOIN afl.player ap ON ap.name = v.afl_player_name
JOIN ffl.player fp ON fp.afl_player_id = ap.id
ON CONFLICT (player_id, club_season_id) DO NOTHING;

COMMIT;
