// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FFLClub struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	DeletedAt *string `json:"deletedAt,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
