// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Query struct {
}

type SearchDocument struct {
	ID     string         `json:"id"`
	Source string         `json:"source"`
	Type   string         `json:"type"`
	Data   map[string]any `json:"data"`
}

type SearchResult struct {
	Total     int               `json:"total"`
	Documents []*SearchDocument `json:"documents"`
}
