package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"xffl/services/search/internal/domain"
)

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, q *string, source *string, typeArg *string) (*SearchResult, error) {
	query := domain.SearchQuery{}
	if q != nil {
		query.Q = *q
	}
	if source != nil {
		query.Source = *source
	}
	if typeArg != nil {
		query.Type = *typeArg
	}

	result, err := r.Repo.Search(ctx, query)
	if err != nil {
		return nil, err
	}

	docs := make([]*SearchDocument, len(result.Documents))
	for i, d := range result.Documents {
		docs[i] = &SearchDocument{
			ID:     d.ID,
			Source: d.Source,
			Type:   d.Type,
			Data:   d.Data,
		}
	}

	return &SearchResult{
		Total:     result.Total,
		Documents: docs,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
