// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bye.sql

package sqlcgen

import (
	"context"
)

const findByeByRoundAndClub = `-- name: FindByeByRoundAndClub :one
SELECT id, round_id, club_season_id
FROM afl.bye
WHERE round_id = $1 AND club_season_id = $2 AND deleted_at IS NULL
`

type FindByeByRoundAndClubParams struct {
	RoundID      int32
	ClubSeasonID int32
}

type FindByeByRoundAndClubRow struct {
	ID           int32
	RoundID      int32
	ClubSeasonID int32
}

func (q *Queries) FindByeByRoundAndClub(ctx context.Context, arg FindByeByRoundAndClubParams) (FindByeByRoundAndClubRow, error) {
	row := q.db.QueryRow(ctx, findByeByRoundAndClub, arg.RoundID, arg.ClubSeasonID)
	var i FindByeByRoundAndClubRow
	err := row.Scan(&i.ID, &i.RoundID, &i.ClubSeasonID)
	return i, err
}

const findByesByRoundID = `-- name: FindByesByRoundID :many
SELECT id, round_id, club_season_id
FROM afl.bye
WHERE round_id = $1 AND deleted_at IS NULL
`

type FindByesByRoundIDRow struct {
	ID           int32
	RoundID      int32
	ClubSeasonID int32
}

func (q *Queries) FindByesByRoundID(ctx context.Context, roundID int32) ([]FindByesByRoundIDRow, error) {
	rows, err := q.db.Query(ctx, findByesByRoundID, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindByesByRoundIDRow{}
	for rows.Next() {
		var i FindByesByRoundIDRow
		if err := rows.Scan(&i.ID, &i.RoundID, &i.ClubSeasonID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBye = `-- name: UpsertBye :one
INSERT INTO afl.bye (round_id, club_season_id)
VALUES ($1, $2)
ON CONFLICT (round_id, club_season_id)
DO UPDATE SET updated_at = CURRENT_TIMESTAMP
WHERE afl.bye.deleted_at IS NULL
RETURNING id, round_id, club_season_id
`

type UpsertByeParams struct {
	RoundID      int32
	ClubSeasonID int32
}

type UpsertByeRow struct {
	ID           int32
	RoundID      int32
	ClubSeasonID int32
}

func (q *Queries) UpsertBye(ctx context.Context, arg UpsertByeParams) (UpsertByeRow, error) {
	row := q.db.QueryRow(ctx, upsertBye, arg.RoundID, arg.ClubSeasonID)
	var i UpsertByeRow
	err := row.Scan(&i.ID, &i.RoundID, &i.ClubSeasonID)
	return i, err
}
