// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: club_match.sql

package sqlcgen

import (
	"context"
)

const findClubMatchByID = `-- name: FindClubMatchByID :one
SELECT id, match_id, club_season_id, rushed_behinds, drv_score
FROM afl.club_match
WHERE id = $1 AND deleted_at IS NULL
`

type FindClubMatchByIDRow struct {
	ID            int32
	MatchID       int32
	ClubSeasonID  int32
	RushedBehinds *int32
	DrvScore      *int32
}

func (q *Queries) FindClubMatchByID(ctx context.Context, id int32) (FindClubMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, findClubMatchByID, id)
	var i FindClubMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.ClubSeasonID,
		&i.RushedBehinds,
		&i.DrvScore,
	)
	return i, err
}

const findClubMatchesByMatchID = `-- name: FindClubMatchesByMatchID :many
SELECT id, match_id, club_season_id, rushed_behinds, drv_score
FROM afl.club_match
WHERE match_id = $1 AND deleted_at IS NULL
`

type FindClubMatchesByMatchIDRow struct {
	ID            int32
	MatchID       int32
	ClubSeasonID  int32
	RushedBehinds *int32
	DrvScore      *int32
}

func (q *Queries) FindClubMatchesByMatchID(ctx context.Context, matchID int32) ([]FindClubMatchesByMatchIDRow, error) {
	rows, err := q.db.Query(ctx, findClubMatchesByMatchID, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindClubMatchesByMatchIDRow{}
	for rows.Next() {
		var i FindClubMatchesByMatchIDRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.ClubSeasonID,
			&i.RushedBehinds,
			&i.DrvScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRoundIDByClubMatchID = `-- name: FindRoundIDByClubMatchID :one
SELECT m.round_id
FROM afl.match m
JOIN afl.club_match cm ON cm.match_id = m.id
WHERE cm.id = $1 AND cm.deleted_at IS NULL AND m.deleted_at IS NULL
`

func (q *Queries) FindRoundIDByClubMatchID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, findRoundIDByClubMatchID, id)
	var round_id int32
	err := row.Scan(&round_id)
	return round_id, err
}

const updateClubMatchScore = `-- name: UpdateClubMatchScore :exec
UPDATE afl.club_match
SET drv_score = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateClubMatchScoreParams struct {
	ID       int32
	DrvScore *int32
}

func (q *Queries) UpdateClubMatchScore(ctx context.Context, arg UpdateClubMatchScoreParams) error {
	_, err := q.db.Exec(ctx, updateClubMatchScore, arg.ID, arg.DrvScore)
	return err
}
