// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dataops_match_source.sql

package sqlcgen

import (
	"context"
)

const findDataopsMatchSourceByMatchID = `-- name: FindDataopsMatchSourceByMatchID :one
SELECT source, external_id, match_id
FROM afl.dataops_match_source
WHERE source = $1 AND match_id = $2
`

type FindDataopsMatchSourceByMatchIDParams struct {
	Source  string
	MatchID int32
}

type FindDataopsMatchSourceByMatchIDRow struct {
	Source     string
	ExternalID string
	MatchID    int32
}

func (q *Queries) FindDataopsMatchSourceByMatchID(ctx context.Context, arg FindDataopsMatchSourceByMatchIDParams) (FindDataopsMatchSourceByMatchIDRow, error) {
	row := q.db.QueryRow(ctx, findDataopsMatchSourceByMatchID, arg.Source, arg.MatchID)
	var i FindDataopsMatchSourceByMatchIDRow
	err := row.Scan(&i.Source, &i.ExternalID, &i.MatchID)
	return i, err
}

const upsertDataopsMatchSource = `-- name: UpsertDataopsMatchSource :exec
INSERT INTO afl.dataops_match_source (source, external_id, match_id, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT (source, match_id) DO UPDATE
    SET external_id = EXCLUDED.external_id,
        updated_at  = CURRENT_TIMESTAMP
`

type UpsertDataopsMatchSourceParams struct {
	Source     string
	ExternalID string
	MatchID    int32
}

func (q *Queries) UpsertDataopsMatchSource(ctx context.Context, arg UpsertDataopsMatchSourceParams) error {
	_, err := q.db.Exec(ctx, upsertDataopsMatchSource, arg.Source, arg.ExternalID, arg.MatchID)
	return err
}
