// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dataops_player_source.sql

package sqlcgen

import (
	"context"
)

const findDataopsPlayerSource = `-- name: FindDataopsPlayerSource :one
SELECT player_season_id
FROM afl.dataops_player_source
WHERE source = $1
  AND external_season = $2
  AND external_club = $3
  AND external_player = $4
`

type FindDataopsPlayerSourceParams struct {
	Source         string
	ExternalSeason string
	ExternalClub   string
	ExternalPlayer string
}

func (q *Queries) FindDataopsPlayerSource(ctx context.Context, arg FindDataopsPlayerSourceParams) (int32, error) {
	row := q.db.QueryRow(ctx, findDataopsPlayerSource,
		arg.Source,
		arg.ExternalSeason,
		arg.ExternalClub,
		arg.ExternalPlayer,
	)
	var player_season_id int32
	err := row.Scan(&player_season_id)
	return player_season_id, err
}

const upsertDataopsPlayerSource = `-- name: UpsertDataopsPlayerSource :exec
INSERT INTO afl.dataops_player_source (source, external_season, external_club, external_player, player_season_id, updated_at)
VALUES ($1, $2, $3, $4, $5, CURRENT_TIMESTAMP)
ON CONFLICT (source, external_season, external_club, external_player) DO UPDATE
    SET player_season_id = EXCLUDED.player_season_id,
        updated_at       = CURRENT_TIMESTAMP
`

type UpsertDataopsPlayerSourceParams struct {
	Source         string
	ExternalSeason string
	ExternalClub   string
	ExternalPlayer string
	PlayerSeasonID int32
}

func (q *Queries) UpsertDataopsPlayerSource(ctx context.Context, arg UpsertDataopsPlayerSourceParams) error {
	_, err := q.db.Exec(ctx, upsertDataopsPlayerSource,
		arg.Source,
		arg.ExternalSeason,
		arg.ExternalClub,
		arg.ExternalPlayer,
		arg.PlayerSeasonID,
	)
	return err
}
