// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: historical.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAllPlayers = `-- name: FindAllPlayers :many
SELECT id, name FROM afl.player
WHERE deleted_at IS NULL
ORDER BY id
`

type FindAllPlayersRow struct {
	ID   int32
	Name string
}

func (q *Queries) FindAllPlayers(ctx context.Context) ([]FindAllPlayersRow, error) {
	rows, err := q.db.Query(ctx, findAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllPlayersRow{}
	for rows.Next() {
		var i FindAllPlayersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMatchByRoundAndHomeClubSeason = `-- name: FindMatchByRoundAndHomeClubSeason :one
SELECT m.id FROM afl.match m
JOIN afl.club_match cm ON cm.match_id = m.id AND cm.side = 'home' AND cm.deleted_at IS NULL
WHERE m.round_id = $1 AND cm.club_season_id = $2 AND m.deleted_at IS NULL
LIMIT 1
`

type FindMatchByRoundAndHomeClubSeasonParams struct {
	RoundID      int32
	ClubSeasonID int32
}

func (q *Queries) FindMatchByRoundAndHomeClubSeason(ctx context.Context, arg FindMatchByRoundAndHomeClubSeasonParams) (int32, error) {
	row := q.db.QueryRow(ctx, findMatchByRoundAndHomeClubSeason, arg.RoundID, arg.ClubSeasonID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findPlayersByExactName = `-- name: FindPlayersByExactName :many
SELECT id, name FROM afl.player
WHERE name = $1 AND deleted_at IS NULL
ORDER BY id
`

type FindPlayersByExactNameRow struct {
	ID   int32
	Name string
}

func (q *Queries) FindPlayersByExactName(ctx context.Context, name string) ([]FindPlayersByExactNameRow, error) {
	rows, err := q.db.Query(ctx, findPlayersByExactName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayersByExactNameRow{}
	for rows.Next() {
		var i FindPlayersByExactNameRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRoundBySeasonAndName = `-- name: FindRoundBySeasonAndName :one
SELECT id FROM afl.round
WHERE season_id = $1 AND name = $2 AND deleted_at IS NULL
`

type FindRoundBySeasonAndNameParams struct {
	SeasonID int32
	Name     string
}

func (q *Queries) FindRoundBySeasonAndName(ctx context.Context, arg FindRoundBySeasonAndNameParams) (int32, error) {
	row := q.db.QueryRow(ctx, findRoundBySeasonAndName, arg.SeasonID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findSeasonByLeagueAndName = `-- name: FindSeasonByLeagueAndName :one
SELECT id FROM afl.season
WHERE league_id = $1 AND name = $2 AND deleted_at IS NULL
`

type FindSeasonByLeagueAndNameParams struct {
	LeagueID int32
	Name     string
}

func (q *Queries) FindSeasonByLeagueAndName(ctx context.Context, arg FindSeasonByLeagueAndNameParams) (int32, error) {
	row := q.db.QueryRow(ctx, findSeasonByLeagueAndName, arg.LeagueID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertHistoricalMatch = `-- name: InsertHistoricalMatch :one
INSERT INTO afl.match (round_id, venue, start_dt, data_status)
VALUES ($1, $2, $3, 'final')
RETURNING id
`

type InsertHistoricalMatchParams struct {
	RoundID int32
	Venue   *string
	StartDt pgtype.Timestamptz
}

// Historical matches are complete, so data_status is 'final' (so their stats
// count in player-season averages). Scores/results are not backfilled.
func (q *Queries) InsertHistoricalMatch(ctx context.Context, arg InsertHistoricalMatchParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertHistoricalMatch, arg.RoundID, arg.Venue, arg.StartDt)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertRoundReturningID = `-- name: InsertRoundReturningID :one
INSERT INTO afl.round (season_id, name) VALUES ($1, $2)
RETURNING id
`

type InsertRoundReturningIDParams struct {
	SeasonID int32
	Name     string
}

func (q *Queries) InsertRoundReturningID(ctx context.Context, arg InsertRoundReturningIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertRoundReturningID, arg.SeasonID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertSeasonReturningID = `-- name: InsertSeasonReturningID :one
INSERT INTO afl.season (league_id, name) VALUES ($1, $2)
RETURNING id
`

type InsertSeasonReturningIDParams struct {
	LeagueID int32
	Name     string
}

func (q *Queries) InsertSeasonReturningID(ctx context.Context, arg InsertSeasonReturningIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertSeasonReturningID, arg.LeagueID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const upsertClubByName = `-- name: UpsertClubByName :one
INSERT INTO afl.club (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

func (q *Queries) UpsertClubByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, upsertClubByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const upsertClubMatchReturningID = `-- name: UpsertClubMatchReturningID :one
INSERT INTO afl.club_match (match_id, club_season_id, side)
VALUES ($1, $2, $3)
ON CONFLICT (club_season_id, match_id) DO UPDATE SET side = EXCLUDED.side
RETURNING id
`

type UpsertClubMatchReturningIDParams struct {
	MatchID      int32
	ClubSeasonID int32
	Side         string
}

func (q *Queries) UpsertClubMatchReturningID(ctx context.Context, arg UpsertClubMatchReturningIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertClubMatchReturningID, arg.MatchID, arg.ClubSeasonID, arg.Side)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const upsertClubSeasonReturningID = `-- name: UpsertClubSeasonReturningID :one
INSERT INTO afl.club_season (club_id, season_id) VALUES ($1, $2)
ON CONFLICT (club_id, season_id) DO UPDATE SET club_id = EXCLUDED.club_id
RETURNING id
`

type UpsertClubSeasonReturningIDParams struct {
	ClubID   int32
	SeasonID int32
}

func (q *Queries) UpsertClubSeasonReturningID(ctx context.Context, arg UpsertClubSeasonReturningIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, upsertClubSeasonReturningID, arg.ClubID, arg.SeasonID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const upsertLeagueByName = `-- name: UpsertLeagueByName :one

INSERT INTO afl.league (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

// Queries for the one-time historical import (cmd/afltables-import).
// Get-or-create helpers for the season→player_match scaffold, plus name lookups
// used by the interactive player resolver.
func (q *Queries) UpsertLeagueByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, upsertLeagueByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}
