// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match_source_map.sql

package sqlcgen

import (
	"context"
)

const findMatchSourceMapByMatchID = `-- name: FindMatchSourceMapByMatchID :one
SELECT source, external_id, match_id
FROM afl.match_source_map
WHERE source = $1 AND match_id = $2
`

type FindMatchSourceMapByMatchIDParams struct {
	Source  string
	MatchID int32
}

type FindMatchSourceMapByMatchIDRow struct {
	Source     string
	ExternalID string
	MatchID    int32
}

func (q *Queries) FindMatchSourceMapByMatchID(ctx context.Context, arg FindMatchSourceMapByMatchIDParams) (FindMatchSourceMapByMatchIDRow, error) {
	row := q.db.QueryRow(ctx, findMatchSourceMapByMatchID, arg.Source, arg.MatchID)
	var i FindMatchSourceMapByMatchIDRow
	err := row.Scan(&i.Source, &i.ExternalID, &i.MatchID)
	return i, err
}

const upsertMatchSourceMap = `-- name: UpsertMatchSourceMap :exec
INSERT INTO afl.match_source_map (source, external_id, match_id, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT (source, match_id) DO UPDATE
    SET external_id = EXCLUDED.external_id,
        updated_at  = CURRENT_TIMESTAMP
`

type UpsertMatchSourceMapParams struct {
	Source     string
	ExternalID string
	MatchID    int32
}

func (q *Queries) UpsertMatchSourceMap(ctx context.Context, arg UpsertMatchSourceMapParams) error {
	_, err := q.db.Exec(ctx, upsertMatchSourceMap, arg.Source, arg.ExternalID, arg.MatchID)
	return err
}
