// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: match.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findFinalMatchesBySeasonID = `-- name: FindFinalMatchesBySeasonID :many
SELECT m.id,
       m.round_id,
       COALESCE(home.id, 0)              AS home_club_match_id,
       COALESCE(home.club_season_id, 0)  AS home_club_season_id,
       COALESCE(home.drv_score, 0)       AS home_score,
       COALESCE(away.id, 0)              AS away_club_match_id,
       COALESCE(away.club_season_id, 0)  AS away_club_season_id,
       COALESCE(away.drv_score, 0)       AS away_score
FROM afl.match m
JOIN afl.round r ON r.id = m.round_id AND r.deleted_at IS NULL
LEFT JOIN afl.club_match home ON home.id = m.home_club_match_id AND home.deleted_at IS NULL
LEFT JOIN afl.club_match away ON away.id = m.away_club_match_id AND away.deleted_at IS NULL
WHERE r.season_id = $1
  AND m.data_status = 'final'
  AND m.deleted_at IS NULL
`

type FindFinalMatchesBySeasonIDRow struct {
	ID               int32
	RoundID          int32
	HomeClubMatchID  int32
	HomeClubSeasonID int32
	HomeScore        int32
	AwayClubMatchID  int32
	AwayClubSeasonID int32
	AwayScore        int32
}

func (q *Queries) FindFinalMatchesBySeasonID(ctx context.Context, seasonID int32) ([]FindFinalMatchesBySeasonIDRow, error) {
	rows, err := q.db.Query(ctx, findFinalMatchesBySeasonID, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindFinalMatchesBySeasonIDRow{}
	for rows.Next() {
		var i FindFinalMatchesBySeasonIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.HomeClubMatchID,
			&i.HomeClubSeasonID,
			&i.HomeScore,
			&i.AwayClubMatchID,
			&i.AwayClubSeasonID,
			&i.AwayScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMatchByID = `-- name: FindMatchByID :one
SELECT id, round_id,
       COALESCE(home_club_match_id, 0) AS home_club_match_id,
       COALESCE(away_club_match_id, 0) AS away_club_match_id,
       COALESCE(venue, '') AS venue,
       COALESCE(start_dt, '0001-01-01T00:00:00Z'::timestamptz) AS start_dt,
       COALESCE(drv_result, '') AS drv_result,
       data_status
FROM afl.match
WHERE id = $1 AND deleted_at IS NULL
`

type FindMatchByIDRow struct {
	ID              int32
	RoundID         int32
	HomeClubMatchID int32
	AwayClubMatchID int32
	Venue           string
	StartDt         pgtype.Timestamptz
	DrvResult       string
	DataStatus      string
}

func (q *Queries) FindMatchByID(ctx context.Context, id int32) (FindMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, findMatchByID, id)
	var i FindMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.RoundID,
		&i.HomeClubMatchID,
		&i.AwayClubMatchID,
		&i.Venue,
		&i.StartDt,
		&i.DrvResult,
		&i.DataStatus,
	)
	return i, err
}

const findMatchesByIDs = `-- name: FindMatchesByIDs :many
SELECT id, round_id,
       COALESCE(home_club_match_id, 0) AS home_club_match_id,
       COALESCE(away_club_match_id, 0) AS away_club_match_id,
       COALESCE(venue, '') AS venue,
       COALESCE(start_dt, '0001-01-01T00:00:00Z'::timestamptz) AS start_dt,
       COALESCE(drv_result, '') AS drv_result,
       data_status
FROM afl.match
WHERE id = ANY($1::int[]) AND deleted_at IS NULL
`

type FindMatchesByIDsRow struct {
	ID              int32
	RoundID         int32
	HomeClubMatchID int32
	AwayClubMatchID int32
	Venue           string
	StartDt         pgtype.Timestamptz
	DrvResult       string
	DataStatus      string
}

func (q *Queries) FindMatchesByIDs(ctx context.Context, ids []int32) ([]FindMatchesByIDsRow, error) {
	rows, err := q.db.Query(ctx, findMatchesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindMatchesByIDsRow{}
	for rows.Next() {
		var i FindMatchesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.HomeClubMatchID,
			&i.AwayClubMatchID,
			&i.Venue,
			&i.StartDt,
			&i.DrvResult,
			&i.DataStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMatchesByRoundID = `-- name: FindMatchesByRoundID :many
SELECT id, round_id,
       COALESCE(home_club_match_id, 0) AS home_club_match_id,
       COALESCE(away_club_match_id, 0) AS away_club_match_id,
       COALESCE(venue, '') AS venue,
       COALESCE(start_dt, '0001-01-01T00:00:00Z'::timestamptz) AS start_dt,
       COALESCE(drv_result, '') AS drv_result,
       data_status
FROM afl.match
WHERE round_id = $1 AND deleted_at IS NULL
`

type FindMatchesByRoundIDRow struct {
	ID              int32
	RoundID         int32
	HomeClubMatchID int32
	AwayClubMatchID int32
	Venue           string
	StartDt         pgtype.Timestamptz
	DrvResult       string
	DataStatus      string
}

func (q *Queries) FindMatchesByRoundID(ctx context.Context, roundID int32) ([]FindMatchesByRoundIDRow, error) {
	rows, err := q.db.Query(ctx, findMatchesByRoundID, roundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindMatchesByRoundIDRow{}
	for rows.Next() {
		var i FindMatchesByRoundIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RoundID,
			&i.HomeClubMatchID,
			&i.AwayClubMatchID,
			&i.Venue,
			&i.StartDt,
			&i.DrvResult,
			&i.DataStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMatchDataStatus = `-- name: UpdateMatchDataStatus :exec
UPDATE afl.match
SET data_status = $2,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateMatchDataStatusParams struct {
	ID         int32
	DataStatus string
}

func (q *Queries) UpdateMatchDataStatus(ctx context.Context, arg UpdateMatchDataStatusParams) error {
	_, err := q.db.Exec(ctx, updateMatchDataStatus, arg.ID, arg.DataStatus)
	return err
}

const updateMatchResult = `-- name: UpdateMatchResult :exec
UPDATE afl.match
SET drv_result = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateMatchResultParams struct {
	ID        int32
	DrvResult *string
}

func (q *Queries) UpdateMatchResult(ctx context.Context, arg UpdateMatchResultParams) error {
	_, err := q.db.Exec(ctx, updateMatchResult, arg.ID, arg.DrvResult)
	return err
}
