// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AflClub struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Name      string
}

type AflClubMatch struct {
	ID                   int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	MatchID              int32
	ClubSeasonID         int32
	RushedBehinds        *int32
	DrvScore             *int32
	DrvPremiershipPoints *int32
}

type AflClubSeason struct {
	ID                   int32
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	ClubID               int32
	SeasonID             int32
	DrvPlayed            *int32
	DrvWon               *int32
	DrvLost              *int32
	DrvDrawn             *int32
	DrvFor               *int32
	DrvAgainst           *int32
	DrvPremiershipPoints *int32
}

type AflDataopsMatchSource struct {
	Source     string
	ExternalID string
	MatchID    int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type AflDataopsPlayerSource struct {
	Source         string
	ExternalSeason string
	ExternalClub   string
	ExternalPlayer string
	PlayerSeasonID int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type AflLeague struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Name      string
}

type AflMatch struct {
	ID              int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	RoundID         int32
	HomeClubMatchID *int32
	AwayClubMatchID *int32
	Venue           *string
	StartDt         pgtype.Timestamptz
	DataStatus      string
	DrvResult       *string
}

type AflPlayer struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Name      string
}

type AflPlayerMatch struct {
	ID             int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	ClubMatchID    int32
	PlayerSeasonID int32
	Status         *string
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
}

type AflPlayerSeason struct {
	ID           int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	PlayerID     int32
	ClubSeasonID int32
	FromRoundID  *int32
	ToRoundID    *int32
}

type AflRound struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	SeasonID  int32
	Name      string
}

type AflSeason struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	LeagueID  int32
	Name      string
}
