// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_season.sql

package sqlcgen

import (
	"context"
)

const findPlayerSeasonByID = `-- name: FindPlayerSeasonByID :one
SELECT id, player_id, club_season_id, from_round_id, to_round_id
FROM afl.player_season
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerSeasonByIDRow struct {
	ID           int32
	PlayerID     int32
	ClubSeasonID int32
	FromRoundID  *int32
	ToRoundID    *int32
}

func (q *Queries) FindPlayerSeasonByID(ctx context.Context, id int32) (FindPlayerSeasonByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerSeasonByID, id)
	var i FindPlayerSeasonByIDRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.ClubSeasonID,
		&i.FromRoundID,
		&i.ToRoundID,
	)
	return i, err
}

const findPlayersByPlayerSeasonIDs = `-- name: FindPlayersByPlayerSeasonIDs :many
SELECT ps.id AS player_season_id, p.id AS player_id, p.name AS player_name
FROM afl.player_season ps
JOIN afl.player p ON p.id = ps.player_id
WHERE ps.id = ANY($1::int[]) AND ps.deleted_at IS NULL
`

type FindPlayersByPlayerSeasonIDsRow struct {
	PlayerSeasonID int32
	PlayerID       int32
	PlayerName     string
}

func (q *Queries) FindPlayersByPlayerSeasonIDs(ctx context.Context, playerSeasonIds []int32) ([]FindPlayersByPlayerSeasonIDsRow, error) {
	rows, err := q.db.Query(ctx, findPlayersByPlayerSeasonIDs, playerSeasonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayersByPlayerSeasonIDsRow{}
	for rows.Next() {
		var i FindPlayersByPlayerSeasonIDsRow
		if err := rows.Scan(&i.PlayerSeasonID, &i.PlayerID, &i.PlayerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
