// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package sqlcgen

import (
	"context"
)

const findPlayerByID = `-- name: FindPlayerByID :one
SELECT id, name, COALESCE(club_id, 0) AS club_id
FROM afl.player
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerByIDRow struct {
	ID     int32
	Name   string
	ClubID int32
}

func (q *Queries) FindPlayerByID(ctx context.Context, id int32) (FindPlayerByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerByID, id)
	var i FindPlayerByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.ClubID)
	return i, err
}

const findPlayersByClubID = `-- name: FindPlayersByClubID :many
SELECT DISTINCT p.id, p.name, COALESCE(p.club_id, 0) AS club_id
FROM afl.player p
LEFT JOIN afl.player_season ps ON ps.player_id = p.id AND ps.deleted_at IS NULL
LEFT JOIN afl.club_season cs ON ps.club_season_id = cs.id AND cs.deleted_at IS NULL
WHERE (p.club_id = $1 OR cs.club_id = $1) AND p.deleted_at IS NULL
ORDER BY p.name
`

type FindPlayersByClubIDRow struct {
	ID     int32
	Name   string
	ClubID int32
}

func (q *Queries) FindPlayersByClubID(ctx context.Context, clubID *int32) ([]FindPlayersByClubIDRow, error) {
	rows, err := q.db.Query(ctx, findPlayersByClubID, clubID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayersByClubIDRow{}
	for rows.Next() {
		var i FindPlayersByClubIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ClubID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
