// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_match.sql

package sqlcgen

import (
	"context"
)

const findByeStatusBatch = `-- name: FindByeStatusBatch :many
SELECT
  ps.id AS player_season_id,
  EXISTS (
    SELECT 1 FROM afl.bye b
    WHERE b.round_id = $1
      AND b.club_season_id = ps.club_season_id
      AND b.deleted_at IS NULL
  ) AS has_bye,
  EXISTS (
    SELECT 1
    FROM afl.player_match pm
    JOIN afl.club_match cm ON cm.id = pm.club_match_id AND cm.deleted_at IS NULL
    JOIN afl.match m ON m.id = cm.match_id AND m.deleted_at IS NULL
    WHERE pm.player_season_id = ps.id
      AND pm.deleted_at IS NULL
      AND m.round_id = (
        SELECT r.id
        FROM afl.match m2
        JOIN afl.club_match cm2 ON cm2.match_id = m2.id AND cm2.deleted_at IS NULL
        JOIN afl.round r ON r.id = m2.round_id AND r.deleted_at IS NULL
        WHERE cm2.club_season_id = ps.club_season_id
          AND r.id < $1
          AND m2.deleted_at IS NULL
          AND m2.data_status = 'final'
          AND NOT EXISTS (
            SELECT 1 FROM afl.bye b2
            WHERE b2.round_id = r.id
              AND b2.club_season_id = ps.club_season_id
              AND b2.deleted_at IS NULL
          )
        ORDER BY r.id DESC
        LIMIT 1
      )
  ) AS played_last
FROM afl.player_season ps
WHERE ps.id = ANY($2::int[])
  AND ps.deleted_at IS NULL
`

type FindByeStatusBatchParams struct {
	RoundID         int32
	PlayerSeasonIds []int32
}

type FindByeStatusBatchRow struct {
	PlayerSeasonID int32
	HasBye         bool
	PlayedLast     bool
}

// For each player_season_id, returns whether their club has a bye in the given
// round, and whether they played in their club's most recent non-bye final match
// before that round.
func (q *Queries) FindByeStatusBatch(ctx context.Context, arg FindByeStatusBatchParams) ([]FindByeStatusBatchRow, error) {
	rows, err := q.db.Query(ctx, findByeStatusBatch, arg.RoundID, arg.PlayerSeasonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindByeStatusBatchRow{}
	for rows.Next() {
		var i FindByeStatusBatchRow
		if err := rows.Scan(&i.PlayerSeasonID, &i.HasBye, &i.PlayedLast); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findFinalStatusBySeasonIDsAndRoundID = `-- name: FindFinalStatusBySeasonIDsAndRoundID :many
SELECT
  ps.id AS player_season_id,
  CASE WHEN pm.id IS NOT NULL THEN 'played' ELSE 'dnp' END::text AS status
FROM afl.player_season ps
JOIN afl.club_match cm ON cm.club_season_id = ps.club_season_id AND cm.deleted_at IS NULL
JOIN afl.match m ON m.id = cm.match_id
  AND m.round_id = $1
  AND m.data_status = 'final'
  AND m.deleted_at IS NULL
LEFT JOIN afl.player_match pm ON pm.player_season_id = ps.id
  AND pm.club_match_id = cm.id
  AND pm.deleted_at IS NULL
WHERE ps.id = ANY($2::int[])
  AND ps.deleted_at IS NULL
`

type FindFinalStatusBySeasonIDsAndRoundIDParams struct {
	RoundID         int32
	PlayerSeasonIds []int32
}

type FindFinalStatusBySeasonIDsAndRoundIDRow struct {
	PlayerSeasonID int32
	Status         string
}

// For each player_season_id whose club has a match in the given round that is
// already final, returns "played" (a player_match row exists) or "dnp" (it
// doesn't). Players whose club's match in that round isn't final yet (or has
// no match at all, e.g. a bye) are omitted — callers must not infer DNP for
// them until this query includes them.
func (q *Queries) FindFinalStatusBySeasonIDsAndRoundID(ctx context.Context, arg FindFinalStatusBySeasonIDsAndRoundIDParams) ([]FindFinalStatusBySeasonIDsAndRoundIDRow, error) {
	rows, err := q.db.Query(ctx, findFinalStatusBySeasonIDsAndRoundID, arg.RoundID, arg.PlayerSeasonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindFinalStatusBySeasonIDsAndRoundIDRow{}
	for rows.Next() {
		var i FindFinalStatusBySeasonIDsAndRoundIDRow
		if err := rows.Scan(&i.PlayerSeasonID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayerMatchByID = `-- name: FindPlayerMatchByID :one
SELECT pm.id, pm.club_match_id, pm.player_season_id,
       pm.kicks, pm.handballs, pm.marks, pm.hitouts, pm.tackles, pm.goals, pm.behinds,
       m.data_status
FROM afl.player_match pm
JOIN afl.club_match cm ON cm.id = pm.club_match_id AND cm.deleted_at IS NULL
JOIN afl.match m ON m.id = cm.match_id AND m.deleted_at IS NULL
WHERE pm.id = $1 AND pm.deleted_at IS NULL
`

type FindPlayerMatchByIDRow struct {
	ID             int32
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
	DataStatus     string
}

func (q *Queries) FindPlayerMatchByID(ctx context.Context, id int32) (FindPlayerMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerMatchByID, id)
	var i FindPlayerMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClubMatchID,
		&i.PlayerSeasonID,
		&i.Kicks,
		&i.Handballs,
		&i.Marks,
		&i.Hitouts,
		&i.Tackles,
		&i.Goals,
		&i.Behinds,
		&i.DataStatus,
	)
	return i, err
}

const findPlayerMatchesByClubMatchID = `-- name: FindPlayerMatchesByClubMatchID :many
SELECT pm.id, pm.club_match_id, pm.player_season_id,
       pm.kicks, pm.handballs, pm.marks, pm.hitouts, pm.tackles, pm.goals, pm.behinds,
       m.data_status
FROM afl.player_match pm
JOIN afl.club_match cm ON cm.id = pm.club_match_id AND cm.deleted_at IS NULL
JOIN afl.match m ON m.id = cm.match_id AND m.deleted_at IS NULL
WHERE pm.club_match_id = $1 AND pm.deleted_at IS NULL
ORDER BY pm.id
`

type FindPlayerMatchesByClubMatchIDRow struct {
	ID             int32
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
	DataStatus     string
}

func (q *Queries) FindPlayerMatchesByClubMatchID(ctx context.Context, clubMatchID int32) ([]FindPlayerMatchesByClubMatchIDRow, error) {
	rows, err := q.db.Query(ctx, findPlayerMatchesByClubMatchID, clubMatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerMatchesByClubMatchIDRow{}
	for rows.Next() {
		var i FindPlayerMatchesByClubMatchIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubMatchID,
			&i.PlayerSeasonID,
			&i.Kicks,
			&i.Handballs,
			&i.Marks,
			&i.Hitouts,
			&i.Tackles,
			&i.Goals,
			&i.Behinds,
			&i.DataStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayerMatchesByIDs = `-- name: FindPlayerMatchesByIDs :many
SELECT pm.id, pm.club_match_id, pm.player_season_id,
       pm.kicks, pm.handballs, pm.marks, pm.hitouts, pm.tackles, pm.goals, pm.behinds,
       m.data_status
FROM afl.player_match pm
JOIN afl.club_match cm ON cm.id = pm.club_match_id AND cm.deleted_at IS NULL
JOIN afl.match m ON m.id = cm.match_id AND m.deleted_at IS NULL
WHERE pm.id = ANY($1::int[]) AND pm.deleted_at IS NULL
ORDER BY pm.id
`

type FindPlayerMatchesByIDsRow struct {
	ID             int32
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
	DataStatus     string
}

func (q *Queries) FindPlayerMatchesByIDs(ctx context.Context, ids []int32) ([]FindPlayerMatchesByIDsRow, error) {
	rows, err := q.db.Query(ctx, findPlayerMatchesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerMatchesByIDsRow{}
	for rows.Next() {
		var i FindPlayerMatchesByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubMatchID,
			&i.PlayerSeasonID,
			&i.Kicks,
			&i.Handballs,
			&i.Marks,
			&i.Hitouts,
			&i.Tackles,
			&i.Goals,
			&i.Behinds,
			&i.DataStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayerMatchesByPlayerSeasonID = `-- name: FindPlayerMatchesByPlayerSeasonID :many
SELECT pm.id, pm.club_match_id, pm.player_season_id,
       pm.kicks, pm.handballs, pm.marks, pm.hitouts, pm.tackles, pm.goals, pm.behinds,
       m.data_status
FROM afl.player_match pm
JOIN afl.club_match cm ON cm.id = pm.club_match_id AND cm.deleted_at IS NULL
JOIN afl.match m ON m.id = cm.match_id AND m.deleted_at IS NULL
WHERE pm.player_season_id = $1 AND pm.deleted_at IS NULL
ORDER BY pm.id
`

type FindPlayerMatchesByPlayerSeasonIDRow struct {
	ID             int32
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
	DataStatus     string
}

func (q *Queries) FindPlayerMatchesByPlayerSeasonID(ctx context.Context, playerSeasonID int32) ([]FindPlayerMatchesByPlayerSeasonIDRow, error) {
	rows, err := q.db.Query(ctx, findPlayerMatchesByPlayerSeasonID, playerSeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerMatchesByPlayerSeasonIDRow{}
	for rows.Next() {
		var i FindPlayerMatchesByPlayerSeasonIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubMatchID,
			&i.PlayerSeasonID,
			&i.Kicks,
			&i.Handballs,
			&i.Marks,
			&i.Hitouts,
			&i.Tackles,
			&i.Goals,
			&i.Behinds,
			&i.DataStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayerMatchesBySeasonIDsAndRoundID = `-- name: FindPlayerMatchesBySeasonIDsAndRoundID :many
SELECT pm.id, pm.club_match_id, pm.player_season_id,
       pm.kicks, pm.handballs, pm.marks, pm.hitouts, pm.tackles, pm.goals, pm.behinds,
       m.data_status
FROM afl.player_match pm
JOIN afl.club_match cm ON cm.id = pm.club_match_id AND cm.deleted_at IS NULL
JOIN afl.match m ON m.id = cm.match_id AND m.deleted_at IS NULL
WHERE pm.player_season_id = ANY($1::int[])
  AND m.round_id = $2
  AND pm.deleted_at IS NULL
ORDER BY pm.id
`

type FindPlayerMatchesBySeasonIDsAndRoundIDParams struct {
	PlayerSeasonIds []int32
	RoundID         int32
}

type FindPlayerMatchesBySeasonIDsAndRoundIDRow struct {
	ID             int32
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
	DataStatus     string
}

func (q *Queries) FindPlayerMatchesBySeasonIDsAndRoundID(ctx context.Context, arg FindPlayerMatchesBySeasonIDsAndRoundIDParams) ([]FindPlayerMatchesBySeasonIDsAndRoundIDRow, error) {
	rows, err := q.db.Query(ctx, findPlayerMatchesBySeasonIDsAndRoundID, arg.PlayerSeasonIds, arg.RoundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerMatchesBySeasonIDsAndRoundIDRow{}
	for rows.Next() {
		var i FindPlayerMatchesBySeasonIDsAndRoundIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubMatchID,
			&i.PlayerSeasonID,
			&i.Kicks,
			&i.Handballs,
			&i.Marks,
			&i.Hitouts,
			&i.Tackles,
			&i.Goals,
			&i.Behinds,
			&i.DataStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerSeasonAveragesBatch = `-- name: GetPlayerSeasonAveragesBatch :many
SELECT
  pm.player_season_id,
  AVG(pm.goals)::float8     AS avg_goals,
  AVG(pm.kicks)::float8     AS avg_kicks,
  AVG(pm.handballs)::float8 AS avg_handballs,
  AVG(pm.marks)::float8     AS avg_marks,
  AVG(pm.tackles)::float8   AS avg_tackles,
  AVG(pm.hitouts)::float8   AS avg_hitouts
FROM afl.player_match pm
JOIN afl.club_match cm ON cm.id = pm.club_match_id AND cm.deleted_at IS NULL
JOIN afl.match m ON m.id = cm.match_id AND m.deleted_at IS NULL
WHERE pm.player_season_id = ANY($1::int[])
  AND pm.deleted_at IS NULL
  AND m.data_status = 'final'
  AND m.start_dt < (
    SELECT MIN(m2.start_dt)
    FROM afl.match m2
    WHERE m2.round_id = $2 AND m2.deleted_at IS NULL
  )
GROUP BY pm.player_season_id
`

type GetPlayerSeasonAveragesBatchParams struct {
	PlayerSeasonIds []int32
	RoundID         int32
}

type GetPlayerSeasonAveragesBatchRow struct {
	PlayerSeasonID int32
	AvgGoals       float64
	AvgKicks       float64
	AvgHandballs   float64
	AvgMarks       float64
	AvgTackles     float64
	AvgHitouts     float64
}

// Returns average stats for each player_season across final matches that took place
// before the given round (by start_dt, since round_id ordering is not guaranteed to be
// chronological). Used to compute bye scores from season-to-date form.
func (q *Queries) GetPlayerSeasonAveragesBatch(ctx context.Context, arg GetPlayerSeasonAveragesBatchParams) ([]GetPlayerSeasonAveragesBatchRow, error) {
	rows, err := q.db.Query(ctx, getPlayerSeasonAveragesBatch, arg.PlayerSeasonIds, arg.RoundID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerSeasonAveragesBatchRow{}
	for rows.Next() {
		var i GetPlayerSeasonAveragesBatchRow
		if err := rows.Scan(
			&i.PlayerSeasonID,
			&i.AvgGoals,
			&i.AvgKicks,
			&i.AvgHandballs,
			&i.AvgMarks,
			&i.AvgTackles,
			&i.AvgHitouts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayerMatch = `-- name: UpsertPlayerMatch :one
INSERT INTO afl.player_match (club_match_id, player_season_id, kicks, handballs, marks, hitouts, tackles, goals, behinds)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (player_season_id, club_match_id)
DO UPDATE SET
    kicks = COALESCE($3, afl.player_match.kicks),
    handballs = COALESCE($4, afl.player_match.handballs),
    marks = COALESCE($5, afl.player_match.marks),
    hitouts = COALESCE($6, afl.player_match.hitouts),
    tackles = COALESCE($7, afl.player_match.tackles),
    goals = COALESCE($8, afl.player_match.goals),
    behinds = COALESCE($9, afl.player_match.behinds),
    updated_at = CURRENT_TIMESTAMP
WHERE afl.player_match.deleted_at IS NULL
RETURNING id, club_match_id, player_season_id, kicks, handballs, marks, hitouts, tackles, goals, behinds
`

type UpsertPlayerMatchParams struct {
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
}

type UpsertPlayerMatchRow struct {
	ID             int32
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
}

func (q *Queries) UpsertPlayerMatch(ctx context.Context, arg UpsertPlayerMatchParams) (UpsertPlayerMatchRow, error) {
	row := q.db.QueryRow(ctx, upsertPlayerMatch,
		arg.ClubMatchID,
		arg.PlayerSeasonID,
		arg.Kicks,
		arg.Handballs,
		arg.Marks,
		arg.Hitouts,
		arg.Tackles,
		arg.Goals,
		arg.Behinds,
	)
	var i UpsertPlayerMatchRow
	err := row.Scan(
		&i.ID,
		&i.ClubMatchID,
		&i.PlayerSeasonID,
		&i.Kicks,
		&i.Handballs,
		&i.Marks,
		&i.Hitouts,
		&i.Tackles,
		&i.Goals,
		&i.Behinds,
	)
	return i, err
}
