// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_season.sql

package sqlcgen

import (
	"context"
)

const findPlayerSeasonByID = `-- name: FindPlayerSeasonByID :one
SELECT id, player_id, club_season_id, from_round_id, to_round_id
FROM afl.player_season
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerSeasonByIDRow struct {
	ID           int32
	PlayerID     int32
	ClubSeasonID int32
	FromRoundID  *int32
	ToRoundID    *int32
}

func (q *Queries) FindPlayerSeasonByID(ctx context.Context, id int32) (FindPlayerSeasonByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerSeasonByID, id)
	var i FindPlayerSeasonByIDRow
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.ClubSeasonID,
		&i.FromRoundID,
		&i.ToRoundID,
	)
	return i, err
}

const findPlayerSeasonsByClubSeasonIDWithPlayer = `-- name: FindPlayerSeasonsByClubSeasonIDWithPlayer :many
SELECT ps.id AS player_season_id, p.id AS player_id, p.name AS player_name, ps.club_season_id
FROM afl.player_season ps
JOIN afl.player p ON p.id = ps.player_id
WHERE ps.club_season_id = $1 AND ps.deleted_at IS NULL AND p.deleted_at IS NULL
`

type FindPlayerSeasonsByClubSeasonIDWithPlayerRow struct {
	PlayerSeasonID int32
	PlayerID       int32
	PlayerName     string
	ClubSeasonID   int32
}

func (q *Queries) FindPlayerSeasonsByClubSeasonIDWithPlayer(ctx context.Context, clubSeasonID int32) ([]FindPlayerSeasonsByClubSeasonIDWithPlayerRow, error) {
	rows, err := q.db.Query(ctx, findPlayerSeasonsByClubSeasonIDWithPlayer, clubSeasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerSeasonsByClubSeasonIDWithPlayerRow{}
	for rows.Next() {
		var i FindPlayerSeasonsByClubSeasonIDWithPlayerRow
		if err := rows.Scan(
			&i.PlayerSeasonID,
			&i.PlayerID,
			&i.PlayerName,
			&i.ClubSeasonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayerSeasonsByIDs = `-- name: FindPlayerSeasonsByIDs :many
SELECT id, player_id, club_season_id, from_round_id, to_round_id
FROM afl.player_season
WHERE id = ANY($1::int[]) AND deleted_at IS NULL
`

type FindPlayerSeasonsByIDsRow struct {
	ID           int32
	PlayerID     int32
	ClubSeasonID int32
	FromRoundID  *int32
	ToRoundID    *int32
}

func (q *Queries) FindPlayerSeasonsByIDs(ctx context.Context, ids []int32) ([]FindPlayerSeasonsByIDsRow, error) {
	rows, err := q.db.Query(ctx, findPlayerSeasonsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerSeasonsByIDsRow{}
	for rows.Next() {
		var i FindPlayerSeasonsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.ClubSeasonID,
			&i.FromRoundID,
			&i.ToRoundID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayerSeasonsBySeasonID = `-- name: FindPlayerSeasonsBySeasonID :many
SELECT ps.id
FROM afl.player_season ps
JOIN afl.club_season cs ON cs.id = ps.club_season_id
JOIN afl.player p ON p.id = ps.player_id
WHERE cs.season_id = $1
  AND ps.deleted_at IS NULL
  AND cs.deleted_at IS NULL
  AND p.deleted_at IS NULL
  AND ($2::text IS NULL OR p.name ILIKE '%' || $2 || '%')
ORDER BY p.name ASC, ps.id ASC
`

type FindPlayerSeasonsBySeasonIDParams struct {
	SeasonID  int32
	NameQuery *string
}

func (q *Queries) FindPlayerSeasonsBySeasonID(ctx context.Context, arg FindPlayerSeasonsBySeasonIDParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, findPlayerSeasonsBySeasonID, arg.SeasonID, arg.NameQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayersByPlayerSeasonIDs = `-- name: FindPlayersByPlayerSeasonIDs :many
SELECT ps.id AS player_season_id, p.id AS player_id, p.name AS player_name
FROM afl.player_season ps
JOIN afl.player p ON p.id = ps.player_id
WHERE ps.id = ANY($1::int[]) AND ps.deleted_at IS NULL
`

type FindPlayersByPlayerSeasonIDsRow struct {
	PlayerSeasonID int32
	PlayerID       int32
	PlayerName     string
}

func (q *Queries) FindPlayersByPlayerSeasonIDs(ctx context.Context, playerSeasonIds []int32) ([]FindPlayersByPlayerSeasonIDsRow, error) {
	rows, err := q.db.Query(ctx, findPlayersByPlayerSeasonIDs, playerSeasonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayersByPlayerSeasonIDsRow{}
	for rows.Next() {
		var i FindPlayersByPlayerSeasonIDsRow
		if err := rows.Scan(&i.PlayerSeasonID, &i.PlayerID, &i.PlayerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
