// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_match.sql

package sqlcgen

import (
	"context"
)

const findPlayerMatchByID = `-- name: FindPlayerMatchByID :one
SELECT id, club_match_id, player_season_id,
       kicks, handballs, marks, hitouts, tackles, goals, behinds
FROM afl.player_match
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerMatchByIDRow struct {
	ID             int32
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
}

func (q *Queries) FindPlayerMatchByID(ctx context.Context, id int32) (FindPlayerMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerMatchByID, id)
	var i FindPlayerMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClubMatchID,
		&i.PlayerSeasonID,
		&i.Kicks,
		&i.Handballs,
		&i.Marks,
		&i.Hitouts,
		&i.Tackles,
		&i.Goals,
		&i.Behinds,
	)
	return i, err
}

const findPlayerMatchesByClubMatchID = `-- name: FindPlayerMatchesByClubMatchID :many
SELECT id, club_match_id, player_season_id,
       kicks, handballs, marks, hitouts, tackles, goals, behinds
FROM afl.player_match
WHERE club_match_id = $1 AND deleted_at IS NULL
`

type FindPlayerMatchesByClubMatchIDRow struct {
	ID             int32
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
}

func (q *Queries) FindPlayerMatchesByClubMatchID(ctx context.Context, clubMatchID int32) ([]FindPlayerMatchesByClubMatchIDRow, error) {
	rows, err := q.db.Query(ctx, findPlayerMatchesByClubMatchID, clubMatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerMatchesByClubMatchIDRow{}
	for rows.Next() {
		var i FindPlayerMatchesByClubMatchIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubMatchID,
			&i.PlayerSeasonID,
			&i.Kicks,
			&i.Handballs,
			&i.Marks,
			&i.Hitouts,
			&i.Tackles,
			&i.Goals,
			&i.Behinds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
