// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_match.sql

package sqlcgen

import (
	"context"
)

const findPlayerMatchByID = `-- name: FindPlayerMatchByID :one
SELECT id, club_match_id, player_season_id,
       kicks, handballs, marks, hitouts, tackles, goals, behinds
FROM afl.player_match
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerMatchByIDRow struct {
	ID             int32
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
}

func (q *Queries) FindPlayerMatchByID(ctx context.Context, id int32) (FindPlayerMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerMatchByID, id)
	var i FindPlayerMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.ClubMatchID,
		&i.PlayerSeasonID,
		&i.Kicks,
		&i.Handballs,
		&i.Marks,
		&i.Hitouts,
		&i.Tackles,
		&i.Goals,
		&i.Behinds,
	)
	return i, err
}

const findPlayerMatchStatsByPlayerSeasonIDs = `-- name: FindPlayerMatchStatsByPlayerSeasonIDs :many
SELECT player_season_id,
       COUNT(*)::INTEGER AS games_played,
       AVG(kicks)::FLOAT8 AS avg_kicks,
       AVG(handballs)::FLOAT8 AS avg_handballs,
       AVG(marks)::FLOAT8 AS avg_marks,
       AVG(hitouts)::FLOAT8 AS avg_hitouts,
       AVG(tackles)::FLOAT8 AS avg_tackles,
       AVG(goals)::FLOAT8 AS avg_goals,
       AVG(behinds)::FLOAT8 AS avg_behinds
FROM afl.player_match
WHERE player_season_id = ANY($1::int[]) AND deleted_at IS NULL
GROUP BY player_season_id
`

type FindPlayerMatchStatsByPlayerSeasonIDsRow struct {
	PlayerSeasonID int32
	GamesPlayed    int32
	AvgKicks       float64
	AvgHandballs   float64
	AvgMarks       float64
	AvgHitouts     float64
	AvgTackles     float64
	AvgGoals       float64
	AvgBehinds     float64
}

func (q *Queries) FindPlayerMatchStatsByPlayerSeasonIDs(ctx context.Context, playerSeasonIds []int32) ([]FindPlayerMatchStatsByPlayerSeasonIDsRow, error) {
	rows, err := q.db.Query(ctx, findPlayerMatchStatsByPlayerSeasonIDs, playerSeasonIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerMatchStatsByPlayerSeasonIDsRow{}
	for rows.Next() {
		var i FindPlayerMatchStatsByPlayerSeasonIDsRow
		if err := rows.Scan(
			&i.PlayerSeasonID,
			&i.GamesPlayed,
			&i.AvgKicks,
			&i.AvgHandballs,
			&i.AvgMarks,
			&i.AvgHitouts,
			&i.AvgTackles,
			&i.AvgGoals,
			&i.AvgBehinds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPlayerMatchesByClubMatchID = `-- name: FindPlayerMatchesByClubMatchID :many
SELECT id, club_match_id, player_season_id,
       kicks, handballs, marks, hitouts, tackles, goals, behinds
FROM afl.player_match
WHERE club_match_id = $1 AND deleted_at IS NULL
`

type FindPlayerMatchesByClubMatchIDRow struct {
	ID             int32
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
}

func (q *Queries) FindPlayerMatchesByClubMatchID(ctx context.Context, clubMatchID int32) ([]FindPlayerMatchesByClubMatchIDRow, error) {
	rows, err := q.db.Query(ctx, findPlayerMatchesByClubMatchID, clubMatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindPlayerMatchesByClubMatchIDRow{}
	for rows.Next() {
		var i FindPlayerMatchesByClubMatchIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClubMatchID,
			&i.PlayerSeasonID,
			&i.Kicks,
			&i.Handballs,
			&i.Marks,
			&i.Hitouts,
			&i.Tackles,
			&i.Goals,
			&i.Behinds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayerMatch = `-- name: UpsertPlayerMatch :one
INSERT INTO afl.player_match (club_match_id, player_season_id, kicks, handballs, marks, hitouts, tackles, goals, behinds)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (player_season_id, club_match_id)
DO UPDATE SET
    kicks = COALESCE($3, afl.player_match.kicks),
    handballs = COALESCE($4, afl.player_match.handballs),
    marks = COALESCE($5, afl.player_match.marks),
    hitouts = COALESCE($6, afl.player_match.hitouts),
    tackles = COALESCE($7, afl.player_match.tackles),
    goals = COALESCE($8, afl.player_match.goals),
    behinds = COALESCE($9, afl.player_match.behinds),
    updated_at = CURRENT_TIMESTAMP
WHERE afl.player_match.deleted_at IS NULL
RETURNING id, club_match_id, player_season_id, kicks, handballs, marks, hitouts, tackles, goals, behinds
`

type UpsertPlayerMatchParams struct {
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
}

type UpsertPlayerMatchRow struct {
	ID             int32
	ClubMatchID    int32
	PlayerSeasonID int32
	Kicks          *int32
	Handballs      *int32
	Marks          *int32
	Hitouts        *int32
	Tackles        *int32
	Goals          *int32
	Behinds        *int32
}

func (q *Queries) UpsertPlayerMatch(ctx context.Context, arg UpsertPlayerMatchParams) (UpsertPlayerMatchRow, error) {
	row := q.db.QueryRow(ctx, upsertPlayerMatch,
		arg.ClubMatchID,
		arg.PlayerSeasonID,
		arg.Kicks,
		arg.Handballs,
		arg.Marks,
		arg.Hitouts,
		arg.Tackles,
		arg.Goals,
		arg.Behinds,
	)
	var i UpsertPlayerMatchRow
	err := row.Scan(
		&i.ID,
		&i.ClubMatchID,
		&i.PlayerSeasonID,
		&i.Kicks,
		&i.Handballs,
		&i.Marks,
		&i.Hitouts,
		&i.Tackles,
		&i.Goals,
		&i.Behinds,
	)
	return i, err
}
