// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player_season.sql

package sqlcgen

import (
	"context"
)

const findPlayerSeasonByID = `-- name: FindPlayerSeasonByID :one
SELECT id, player_id, club_season_id
FROM afl.player_season
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerSeasonByIDRow struct {
	ID           int32
	PlayerID     int32
	ClubSeasonID int32
}

func (q *Queries) FindPlayerSeasonByID(ctx context.Context, id int32) (FindPlayerSeasonByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerSeasonByID, id)
	var i FindPlayerSeasonByIDRow
	err := row.Scan(&i.ID, &i.PlayerID, &i.ClubSeasonID)
	return i, err
}
