// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: player.sql

package sqlcgen

import (
	"context"
)

const findPlayerByID = `-- name: FindPlayerByID :one
SELECT id, name
FROM afl.player
WHERE id = $1 AND deleted_at IS NULL
`

type FindPlayerByIDRow struct {
	ID   int32
	Name string
}

func (q *Queries) FindPlayerByID(ctx context.Context, id int32) (FindPlayerByIDRow, error) {
	row := q.db.QueryRow(ctx, findPlayerByID, id)
	var i FindPlayerByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const searchPlayersByName = `-- name: SearchPlayersByName :many
SELECT id, name
FROM afl.player
WHERE name ILIKE '%' || $1 || '%' AND deleted_at IS NULL
ORDER BY name
LIMIT 20
`

type SearchPlayersByNameRow struct {
	ID   int32
	Name string
}

func (q *Queries) SearchPlayersByName(ctx context.Context, query *string) ([]SearchPlayersByNameRow, error) {
	rows, err := q.db.Query(ctx, searchPlayersByName, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlayersByNameRow{}
	for rows.Next() {
		var i SearchPlayersByNameRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
