// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	FindAllClubs(ctx context.Context) ([]FindAllClubsRow, error)
	FindAllSeasons(ctx context.Context) ([]FindAllSeasonsRow, error)
	FindByeByRoundAndClub(ctx context.Context, arg FindByeByRoundAndClubParams) (FindByeByRoundAndClubRow, error)
	// For each player_season_id, returns whether their club has a bye in the given
	// round, and whether they played in their club's most recent non-bye final match
	// before that round.
	FindByeStatusBatch(ctx context.Context, arg FindByeStatusBatchParams) ([]FindByeStatusBatchRow, error)
	FindByesByRoundID(ctx context.Context, roundID int32) ([]FindByesByRoundIDRow, error)
	FindByesByRoundIDWithClub(ctx context.Context, roundID int32) ([]FindByesByRoundIDWithClubRow, error)
	FindClubByID(ctx context.Context, id int32) (FindClubByIDRow, error)
	FindClubMatchByID(ctx context.Context, id int32) (FindClubMatchByIDRow, error)
	FindClubMatchesByMatchID(ctx context.Context, matchID int32) ([]FindClubMatchesByMatchIDRow, error)
	FindClubSeasonByID(ctx context.Context, id int32) (FindClubSeasonByIDRow, error)
	FindClubSeasonsBySeasonID(ctx context.Context, seasonID int32) ([]FindClubSeasonsBySeasonIDRow, error)
	FindClubsByIDs(ctx context.Context, ids []int32) ([]FindClubsByIDsRow, error)
	FindDataopsMatchSourceByMatchID(ctx context.Context, arg FindDataopsMatchSourceByMatchIDParams) (FindDataopsMatchSourceByMatchIDRow, error)
	FindDataopsPlayerSource(ctx context.Context, arg FindDataopsPlayerSourceParams) (int32, error)
	FindFinalMatchesBySeasonID(ctx context.Context, seasonID int32) ([]FindFinalMatchesBySeasonIDRow, error)
	// Picks the player_season belonging to the most chronologically recent AFL
	// season the player has data for, based on the latest match start_dt within
	// that season (afl.season.id ordering is not chronological).
	FindLatestPlayerSeasonByPlayerID(ctx context.Context, playerID int32) (int32, error)
	FindMatchByID(ctx context.Context, id int32) (FindMatchByIDRow, error)
	FindMatchesByIDs(ctx context.Context, ids []int32) ([]FindMatchesByIDsRow, error)
	FindMatchesByRoundID(ctx context.Context, roundID int32) ([]FindMatchesByRoundIDRow, error)
	FindPlayerByID(ctx context.Context, id int32) (FindPlayerByIDRow, error)
	FindPlayerMatchByID(ctx context.Context, id int32) (FindPlayerMatchByIDRow, error)
	FindPlayerMatchesByClubMatchID(ctx context.Context, clubMatchID int32) ([]FindPlayerMatchesByClubMatchIDRow, error)
	FindPlayerMatchesByIDs(ctx context.Context, ids []int32) ([]FindPlayerMatchesByIDsRow, error)
	FindPlayerMatchesByPlayerSeasonID(ctx context.Context, playerSeasonID int32) ([]FindPlayerMatchesByPlayerSeasonIDRow, error)
	FindPlayerMatchesBySeasonIDsAndRoundID(ctx context.Context, arg FindPlayerMatchesBySeasonIDsAndRoundIDParams) ([]FindPlayerMatchesBySeasonIDsAndRoundIDRow, error)
	FindPlayerSeasonByID(ctx context.Context, id int32) (FindPlayerSeasonByIDRow, error)
	FindPlayerSeasonsByClubSeasonIDWithPlayer(ctx context.Context, clubSeasonID int32) ([]FindPlayerSeasonsByClubSeasonIDWithPlayerRow, error)
	FindPlayerSeasonsByIDs(ctx context.Context, ids []int32) ([]FindPlayerSeasonsByIDsRow, error)
	FindPlayerSeasonsBySeasonID(ctx context.Context, arg FindPlayerSeasonsBySeasonIDParams) ([]int32, error)
	FindPlayersByIDs(ctx context.Context, ids []int32) ([]FindPlayersByIDsRow, error)
	FindPlayersByIDsWithClub(ctx context.Context, ids []int32) ([]FindPlayersByIDsWithClubRow, error)
	FindPlayersByPlayerSeasonIDs(ctx context.Context, playerSeasonIds []int32) ([]FindPlayersByPlayerSeasonIDsRow, error)
	FindRoundByID(ctx context.Context, id int32) (FindRoundByIDRow, error)
	FindRoundIDByClubMatchID(ctx context.Context, id int32) (int32, error)
	FindRoundsBySeasonID(ctx context.Context, seasonID int32) ([]FindRoundsBySeasonIDRow, error)
	FindSeasonByID(ctx context.Context, id int32) (FindSeasonByIDRow, error)
	// Returns average stats for each player_season across final matches that took place
	// before the given round (by start_dt, since round_id ordering is not guaranteed to be
	// chronological). Used to compute bye scores from season-to-date form.
	GetPlayerSeasonAveragesBatch(ctx context.Context, arg GetPlayerSeasonAveragesBatchParams) ([]GetPlayerSeasonAveragesBatchRow, error)
	InsertPlayer(ctx context.Context, name string) (InsertPlayerRow, error)
	InsertPlayerSeason(ctx context.Context, arg InsertPlayerSeasonParams) (InsertPlayerSeasonRow, error)
	SearchPlayersByName(ctx context.Context, query *string) ([]SearchPlayersByNameRow, error)
	UpdateClubMatchRushedBehinds(ctx context.Context, arg UpdateClubMatchRushedBehindsParams) error
	UpdateClubMatchScore(ctx context.Context, arg UpdateClubMatchScoreParams) error
	UpdateClubSeason(ctx context.Context, arg UpdateClubSeasonParams) error
	UpdateMatchDataStatus(ctx context.Context, arg UpdateMatchDataStatusParams) error
	UpdateMatchResult(ctx context.Context, arg UpdateMatchResultParams) error
	UpsertBye(ctx context.Context, arg UpsertByeParams) (UpsertByeRow, error)
	UpsertDataopsMatchSource(ctx context.Context, arg UpsertDataopsMatchSourceParams) error
	UpsertDataopsPlayerSource(ctx context.Context, arg UpsertDataopsPlayerSourceParams) error
	UpsertPlayerMatch(ctx context.Context, arg UpsertPlayerMatchParams) (UpsertPlayerMatchRow, error)
	UpsertPlayerSeason(ctx context.Context, arg UpsertPlayerSeasonParams) (UpsertPlayerSeasonRow, error)
}

var _ Querier = (*Queries)(nil)
