// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: round.sql

package sqlcgen

import (
	"context"
)

const findLatestRound = `-- name: FindLatestRound :one
SELECT r.id, r.name, r.season_id
FROM afl.round r
JOIN afl.season s ON s.id = r.season_id AND s.deleted_at IS NULL
WHERE r.deleted_at IS NULL
ORDER BY s.id DESC, r.id DESC
LIMIT 1
`

type FindLatestRoundRow struct {
	ID       int32
	Name     string
	SeasonID int32
}

func (q *Queries) FindLatestRound(ctx context.Context) (FindLatestRoundRow, error) {
	row := q.db.QueryRow(ctx, findLatestRound)
	var i FindLatestRoundRow
	err := row.Scan(&i.ID, &i.Name, &i.SeasonID)
	return i, err
}

const findRoundByID = `-- name: FindRoundByID :one
SELECT id, name, season_id
FROM afl.round
WHERE id = $1 AND deleted_at IS NULL
`

type FindRoundByIDRow struct {
	ID       int32
	Name     string
	SeasonID int32
}

func (q *Queries) FindRoundByID(ctx context.Context, id int32) (FindRoundByIDRow, error) {
	row := q.db.QueryRow(ctx, findRoundByID, id)
	var i FindRoundByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.SeasonID)
	return i, err
}

const findRoundsBySeasonID = `-- name: FindRoundsBySeasonID :many
SELECT r.id, r.name, r.season_id
FROM afl.round r
LEFT JOIN afl.match m ON m.round_id = r.id AND m.deleted_at IS NULL
WHERE r.season_id = $1 AND r.deleted_at IS NULL
GROUP BY r.id, r.name, r.season_id
ORDER BY MIN(m.start_dt) NULLS LAST, r.id
`

type FindRoundsBySeasonIDRow struct {
	ID       int32
	Name     string
	SeasonID int32
}

func (q *Queries) FindRoundsBySeasonID(ctx context.Context, seasonID int32) ([]FindRoundsBySeasonIDRow, error) {
	rows, err := q.db.Query(ctx, findRoundsBySeasonID, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRoundsBySeasonIDRow{}
	for rows.Next() {
		var i FindRoundsBySeasonIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SeasonID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findRoundsWithMatchBoundsBySeasonID = `-- name: FindRoundsWithMatchBoundsBySeasonID :many
SELECT
    r.id,
    r.name,
    r.season_id,
    COALESCE(MIN(m.start_dt), '0001-01-01T00:00:00Z'::timestamptz) AS first_match_dt,
    COALESCE(MAX(m.start_dt), '0001-01-01T00:00:00Z'::timestamptz) AS last_match_dt
FROM afl.round r
JOIN afl.match m ON m.round_id = r.id AND m.deleted_at IS NULL
WHERE r.season_id = $1 AND r.deleted_at IS NULL
GROUP BY r.id, r.name, r.season_id
ORDER BY MIN(m.start_dt)
`

type FindRoundsWithMatchBoundsBySeasonIDRow struct {
	ID           int32
	Name         string
	SeasonID     int32
	FirstMatchDt interface{}
	LastMatchDt  interface{}
}

func (q *Queries) FindRoundsWithMatchBoundsBySeasonID(ctx context.Context, seasonID int32) ([]FindRoundsWithMatchBoundsBySeasonIDRow, error) {
	rows, err := q.db.Query(ctx, findRoundsWithMatchBoundsBySeasonID, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindRoundsWithMatchBoundsBySeasonIDRow{}
	for rows.Next() {
		var i FindRoundsWithMatchBoundsBySeasonIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SeasonID,
			&i.FirstMatchDt,
			&i.LastMatchDt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
