package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"xffl/services/ffl/internal/application"
	"xffl/services/ffl/internal/application/dataops"
	"xffl/services/ffl/internal/domain"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// ParseFFLTeamSubmission is the resolver for the parseFFLTeamSubmission field.
func (r *mutationResolver) ParseFFLTeamSubmission(ctx context.Context, input ParseFFLTeamSubmissionInput) (*ParseFFLTeamSubmissionResult, error) {
	clubSeasonID, err := fromID(input.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return nil, err
	}
	_ = clubMatchID // passed back to client for use in confirmFFLTeamSubmission

	playerSeasons, err := r.Queries.GetPlayerSeasons(ctx, clubSeasonID)
	if err != nil {
		return nil, fmt.Errorf("fetch squad: %w", err)
	}

	aflIDToPlayerSeasonID := make(map[int]int, len(playerSeasons))
	for _, ps := range playerSeasons {
		p, err := r.Queries.GetPlayerForPlayerSeason(ctx, ps.ID)
		if err != nil {
			return nil, err
		}
		aflIDToPlayerSeasonID[p.AFLPlayerID] = ps.ID
	}

	candidates, err := r.DataOps.LookupCandidates(ctx, aflIDToPlayerSeasonID)
	if err != nil {
		return nil, fmt.Errorf("lookup candidates: %w", err)
	}

	result, err := r.DataOps.ParseTeamSubmission(ctx, dataops.ParseTeamSubmissionParams{
		ClubSeasonID: clubSeasonID,
		TeamName:     input.TeamName,
		Post:         input.Post,
	}, playerSeasons, candidates)
	if err != nil {
		return nil, err
	}

	resolvedGQL := make([]*ResolvedPlayer, len(result.ResolvedPlayers))
	for i, rp := range result.ResolvedPlayers {
		var psID *string
		var resolvedName, resolvedClub *string
		if rp.PlayerSeasonID != 0 {
			id := toID(rp.PlayerSeasonID)
			psID = &id
			name := rp.BestMatch.Candidate.Name
			resolvedName = &name
			club := rp.BestMatch.Candidate.Club
			resolvedClub = &club
		}
		resolvedGQL[i] = &ResolvedPlayer{
			ParsedName:          rp.Parsed.Name,
			ClubHint:            rp.Parsed.ClubHint,
			ResolvedName:        resolvedName,
			ResolvedClub:        resolvedClub,
			Position:            rp.Parsed.Position,
			BackupPositions:     rp.Parsed.BackupPositions,
			InterchangePosition: rp.Parsed.InterchangePosition,
			Score:               rp.Parsed.Score,
			Notes:               rp.Parsed.Notes,
			PlayerSeasonID:      psID,
			Confidence:          rp.BestMatch.Confidence,
		}
	}

	needsReview := make([]int, len(result.NeedsReview))
	copy(needsReview, result.NeedsReview)

	return &ParseFFLTeamSubmissionResult{
		ResolvedPlayers: resolvedGQL,
		NeedsReview:     needsReview,
	}, nil
}

// ConfirmFFLTeamSubmission is the resolver for the confirmFFLTeamSubmission field.
func (r *mutationResolver) ConfirmFFLTeamSubmission(ctx context.Context, input ConfirmFFLTeamSubmissionInput) ([]*FFLPlayerMatch, error) {
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return nil, err
	}

	resolved := make([]dataops.ResolvedPlayer, 0, len(input.Players))
	for _, p := range input.Players {
		psID, err := fromID(p.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		parsed := application.ParsedPlayerRow{
			Position: p.Position,
			Score:    p.Score,
		}
		if p.BackupPositions != nil {
			parsed.BackupPositions = *p.BackupPositions
		}
		if p.InterchangePosition != nil {
			parsed.InterchangePosition = *p.InterchangePosition
		}
		resolved = append(resolved, dataops.ResolvedPlayer{
			Parsed:         parsed,
			PlayerSeasonID: psID,
			Confident:      true,
		})
	}

	pms, err := r.DataOps.ImportRoundTeams(ctx, dataops.ImportRoundTeamsParams{
		ClubMatchID:     clubMatchID,
		ResolvedPlayers: resolved,
	})
	if err != nil {
		var byeErr application.ByeIneligibleError
		if errors.As(err, &byeErr) {
			return nil, &gqlerror.Error{
				Message: byeErr.Error(),
				Extensions: map[string]any{
					"code":           "BYE_INELIGIBLE",
					"playerSeasonId": strconv.Itoa(byeErr.PlayerSeasonID),
				},
			}
		}
		return nil, err
	}

	result := make([]*FFLPlayerMatch, len(pms))
	for i, pm := range pms {
		player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		result[i] = convertPlayerMatch(pm, player)
	}
	return result, nil
}

// MarkFFLTeamFinal is the resolver for the markFFLTeamFinal field.
func (r *mutationResolver) MarkFFLTeamFinal(ctx context.Context, input MarkFFLTeamFinalInput) (bool, error) {
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return false, err
	}
	matchID, err := fromID(input.MatchID)
	if err != nil {
		return false, err
	}
	roundID, err := fromID(input.RoundID)
	if err != nil {
		return false, err
	}
	if err := r.DataOps.MarkTeamFinal(ctx, dataops.MarkTeamFinalParams{
		ClubMatchID: clubMatchID,
		MatchID:     matchID,
		RoundID:     roundID,
	}); err != nil {
		return false, err
	}
	return true, nil
}

// MarkFFLTeamSubmitted is the resolver for the markFFLTeamSubmitted field.
func (r *mutationResolver) MarkFFLTeamSubmitted(ctx context.Context, input MarkFFLTeamFinalInput) (bool, error) {
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return false, err
	}
	matchID, err := fromID(input.MatchID)
	if err != nil {
		return false, err
	}
	roundID, err := fromID(input.RoundID)
	if err != nil {
		return false, err
	}
	if err := r.DataOps.MarkTeamSubmitted(ctx, dataops.MarkTeamFinalParams{
		ClubMatchID: clubMatchID,
		MatchID:     matchID,
		RoundID:     roundID,
	}); err != nil {
		return false, err
	}
	return true, nil
}

// IngestFFLForumPage is the resolver for the ingestFFLForumPage field.
func (r *mutationResolver) IngestFFLForumPage(ctx context.Context, input IngestFFLForumPageInput) (*FFLPreviewedPage, error) {
	posts := make([]dataops.CapturedPost, 0, len(input.Posts))
	for _, p := range input.Posts {
		ts := ""
		if p.Timestamp != nil {
			ts = *p.Timestamp
		}
		posts = append(posts, dataops.CapturedPost{PostID: p.PostID, Author: p.Author, Timestamp: ts, HTML: p.HTML})
	}
	page := r.Captures.Ingest(ctx, dataops.CapturedPageParams{
		Season:     input.Season,
		RoundTitle: input.RoundTitle,
		TopicID:    input.TopicID,
		Posts:      posts,
	})
	return toPreviewedPage(page), nil
}

// ClearFFLForumCaptures is the resolver for the clearFFLForumCaptures field.
func (r *mutationResolver) ClearFFLForumCaptures(ctx context.Context) (bool, error) {
	r.Captures.Clear()
	return true, nil
}

// BuildFFLSeason is the resolver for the buildFFLSeason field.
func (r *mutationResolver) BuildFFLSeason(ctx context.Context, input BuildFFLSeasonInput) (*FFLBuiltSeason, error) {
	aflSeasonID, err := fromID(input.AflSeasonID)
	if err != nil {
		return nil, err
	}
	clubIDs := make([]int, len(input.ClubIds))
	for i, id := range input.ClubIds {
		v, err := fromID(id)
		if err != nil {
			return nil, err
		}
		clubIDs[i] = v
	}
	built, err := r.Builder.BuildSeason(ctx, dataops.BuildSeasonParams{
		SeasonName:  input.SeasonName,
		RulesID:     input.RulesID,
		AFLSeasonID: aflSeasonID,
		ClubIDs:     clubIDs,
	})
	if err != nil {
		return nil, err
	}
	css := make([]*FFLBuiltClubSeason, len(built.ClubSeasons))
	for i, cs := range built.ClubSeasons {
		css[i] = &FFLBuiltClubSeason{ClubName: cs.ClubName, ClubSeasonID: toID(cs.ClubSeasonID)}
	}
	return &FFLBuiltSeason{SeasonID: toID(built.SeasonID), RulesID: built.RulesID, ClubSeasons: css}, nil
}

// SaveFFLFixtures is the resolver for the saveFFLFixtures field.
func (r *mutationResolver) SaveFFLFixtures(ctx context.Context, input SaveFFLFixturesInput) (bool, error) {
	seasonID, err := fromID(input.SeasonID)
	if err != nil {
		return false, err
	}
	rounds := make([]dataops.RoundSpec, len(input.Rounds))
	for i, ri := range input.Rounds {
		spec := dataops.RoundSpec{
			Name:       ri.Name,
			AFLRoundID: 0,
			Type:       domain.RoundTypeMinor,
		}
		if ri.RoundID != nil && *ri.RoundID != "" {
			id, err := fromID(*ri.RoundID)
			if err != nil {
				return false, err
			}
			spec.RoundID = &id
		}
		if spec.AFLRoundID, err = fromID(ri.AflRoundID); err != nil {
			return false, err
		}
		if ri.RoundType != nil && *ri.RoundType != "" {
			spec.Type = domain.RoundType(*ri.RoundType)
		}
		for _, mi := range ri.Matches {
			ids := make([]int, len(mi.ClubSeasonIds))
			for j, id := range mi.ClubSeasonIds {
				cs, err := fromID(id)
				if err != nil {
					return false, err
				}
				ids[j] = cs
			}
			spec.Matches = append(spec.Matches, dataops.MatchSpec{
				Style:         domain.ParseMatchStyle(mi.Style),
				ClubSeasonIDs: ids,
			})
		}
		rounds[i] = spec
	}
	if err := r.Builder.SaveFixtures(ctx, seasonID, rounds); err != nil {
		return false, err
	}
	return true, nil
}

// ParseFFLSquadThread is the resolver for the parseFFLSquadThread field.
func (r *mutationResolver) ParseFFLSquadThread(ctx context.Context, input ParseFFLSquadThreadInput) (*ParseFFLSquadThreadResult, error) {
	aflSeasonID, err := fromID(input.AflSeasonID)
	if err != nil {
		return nil, err
	}

	result, err := r.DataOps.ParseSquadThreadForSeason(ctx, aflSeasonID, input.Thread)
	if err != nil {
		return nil, err
	}

	squads := make([]*ResolvedSquad, len(result.Squads))
	for i, sq := range result.Squads {
		members := make([]*ResolvedSquadMember, len(sq.Members))
		for j, m := range sq.Members {
			var aflPSID, resolvedName, resolvedClub *string
			if m.AFLPlayerSeasonID != 0 {
				id := toID(m.AFLPlayerSeasonID)
				aflPSID = &id
				name := m.BestMatch.Candidate.Name
				resolvedName = &name
				club := m.BestMatch.Candidate.Club
				resolvedClub = &club
			}
			members[j] = &ResolvedSquadMember{
				Rank:              m.Parsed.Rank,
				ParsedName:        m.Parsed.Name,
				ClubHint:          m.Parsed.ClubHint,
				CostCents:         m.Parsed.CostCents,
				ResolvedName:      resolvedName,
				ResolvedClub:      resolvedClub,
				AflPlayerSeasonID: aflPSID,
				Confidence:        m.BestMatch.Confidence,
			}
		}
		needsReview := make([]int, len(sq.NeedsReview))
		copy(needsReview, sq.NeedsReview)
		squads[i] = &ResolvedSquad{ClubName: sq.ClubName, Members: members, NeedsReview: needsReview}
	}

	return &ParseFFLSquadThreadResult{Squads: squads}, nil
}

// ImportFFLSquad is the resolver for the importFFLSquad field.
func (r *mutationResolver) ImportFFLSquad(ctx context.Context, input ImportFFLSquadInput) ([]*FFLPlayerSeason, error) {
	clubSeasonID, err := fromID(input.ClubSeasonID)
	if err != nil {
		return nil, err
	}

	var fromRoundID *int
	if input.FromRoundID != nil && *input.FromRoundID != "" {
		id, err := fromID(*input.FromRoundID)
		if err != nil {
			return nil, err
		}
		fromRoundID = &id
	}

	members := make([]dataops.ResolvedSquadMember, 0, len(input.Members))
	for _, m := range input.Members {
		aflPSID, err := fromID(m.AflPlayerSeasonID)
		if err != nil {
			return nil, err
		}
		members = append(members, dataops.ResolvedSquadMember{
			Parsed:            application.ParsedSquadMember{Name: m.Name, CostCents: m.CostCents},
			AFLPlayerSeasonID: aflPSID,
			Confident:         true,
		})
	}

	added, err := r.DataOps.ImportSquad(ctx, dataops.ImportSquadParams{
		ClubSeasonID: clubSeasonID,
		FromRoundID:  fromRoundID,
		Members:      members,
	})
	if err != nil {
		return nil, err
	}

	result := make([]*FFLPlayerSeason, len(added))
	for i, ps := range added {
		player, err := r.Queries.GetPlayerForPlayerSeason(ctx, ps.ID)
		if err != nil {
			return nil, err
		}
		result[i] = convertPlayerSeason(ps, player)
	}
	return result, nil
}

// ParseFFLFixtureSheet is the resolver for the parseFFLFixtureSheet field.
func (r *mutationResolver) ParseFFLFixtureSheet(ctx context.Context, input ParseFFLFixtureSheetInput) (*ParseFFLFixtureSheetResult, error) {
	parsed, err := r.Builder.ParseFixtureSheet(ctx, input.Sheet)
	if err != nil {
		return nil, err
	}
	rounds := make([]*ParsedFixtureRound, len(parsed))
	for i, pr := range parsed {
		fixtures := make([]*ParsedFixture, len(pr.Fixtures))
		for j, fx := range pr.Fixtures {
			fixtures[j] = &ParsedFixture{
				HomeClub:  fx.HomeClub,
				HomeScore: fx.HomeScore,
				AwayClub:  fx.AwayClub,
				AwayScore: fx.AwayScore,
			}
		}
		rounds[i] = &ParsedFixtureRound{Round: pr.Round, Label: pr.Label, Fixtures: fixtures}
	}
	return &ParseFFLFixtureSheetResult{Rounds: rounds}, nil
}

// ImportFFLFixtures is the resolver for the importFFLFixtures field.
func (r *mutationResolver) ImportFFLFixtures(ctx context.Context, input ImportFFLFixturesInput) (*ImportFFLFixturesResult, error) {
	seasonID, err := fromID(input.SeasonID)
	if err != nil {
		return nil, err
	}
	rounds := make([]dataops.FixtureImportRound, len(input.Rounds))
	for i, ri := range input.Rounds {
		aflRoundID, err := fromID(ri.AflRoundID)
		if err != nil {
			return nil, err
		}
		roundType := domain.RoundTypeMinor
		if ri.RoundType != nil && *ri.RoundType != "" {
			roundType = domain.RoundType(*ri.RoundType)
		}
		fixtures := make([]application.ParsedFixture, len(ri.Fixtures))
		for j, fx := range ri.Fixtures {
			fixtures[j] = application.ParsedFixture{
				HomeClub:  fx.HomeClub,
				HomeScore: fx.HomeScore,
				AwayClub:  fx.AwayClub,
				AwayScore: fx.AwayScore,
			}
		}
		rounds[i] = dataops.FixtureImportRound{
			Name:       ri.Name,
			AFLRoundID: aflRoundID,
			Type:       roundType,
			Fixtures:   fixtures,
		}
	}

	res, err := r.Builder.ImportFixtures(ctx, dataops.ImportFixturesParams{SeasonID: seasonID, Rounds: rounds})
	if err != nil {
		return nil, err
	}
	unresolved := res.Unresolved
	if unresolved == nil {
		unresolved = []string{}
	}
	return &ImportFFLFixturesResult{
		RoundsCreated: res.RoundsCreated,
		ScoresWritten: res.ScoresWritten,
		Unresolved:    unresolved,
	}, nil
}

// FflCapturedPages is the resolver for the fflCapturedPages field.
func (r *queryResolver) FflCapturedPages(ctx context.Context) ([]*FFLPreviewedPage, error) {
	pages := r.Captures.Pages()
	out := make([]*FFLPreviewedPage, 0, len(pages))
	for _, pg := range pages {
		out = append(out, toPreviewedPage(pg))
	}
	return out, nil
}

// FflRulesEras is the resolver for the fflRulesEras field.
func (r *queryResolver) FflRulesEras(ctx context.Context) ([]*FFLRulesEra, error) {
	rules := domain.AllRules()
	out := make([]*FFLRulesEra, len(rules))
	for i, rule := range rules {
		out[i] = &FFLRulesEra{ID: rule.ID, Label: rule.Describe()}
	}
	return out, nil
}

// FflSeasonFixtures is the resolver for the fflSeasonFixtures field.
func (r *queryResolver) FflSeasonFixtures(ctx context.Context, seasonID string) ([]*FFLFixtureRound, error) {
	sID, err := fromID(seasonID)
	if err != nil {
		return nil, err
	}
	rounds, err := r.Builder.LoadFixtures(ctx, sID)
	if err != nil {
		return nil, err
	}
	out := make([]*FFLFixtureRound, len(rounds))
	for i, rnd := range rounds {
		matches := make([]*FFLFixtureMatch, len(rnd.Matches))
		for j, m := range rnd.Matches {
			ids := make([]string, len(m.ClubSeasonIDs))
			for k, cs := range m.ClubSeasonIDs {
				ids[k] = toID(cs)
			}
			matches[j] = &FFLFixtureMatch{Style: string(m.Style), ClubSeasonIds: ids}
		}
		out[i] = &FFLFixtureRound{
			RoundID:    toID(rnd.RoundID),
			Name:       rnd.Name,
			AflRoundID: toID(rnd.AFLRoundID),
			RoundType:  string(rnd.Type),
			Locked:     rnd.Locked,
			Matches:    matches,
		}
	}
	return out, nil
}
