package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"xffl/services/ffl/internal/application"
	"xffl/services/ffl/internal/application/dataops"
	"xffl/services/ffl/internal/domain"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// ParseFFLTeamSubmission is the resolver for the parseFFLTeamSubmission field.
func (r *mutationResolver) ParseFFLTeamSubmission(ctx context.Context, input ParseFFLTeamSubmissionInput) (*ParseFFLTeamSubmissionResult, error) {
	clubSeasonID, err := fromID(input.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return nil, err
	}
	_ = clubMatchID // passed back to client for use in confirmFFLTeamSubmission

	playerSeasons, err := r.Queries.GetPlayerSeasons(ctx, clubSeasonID)
	if err != nil {
		return nil, fmt.Errorf("fetch squad: %w", err)
	}

	aflIDToPlayerSeasonID := make(map[int]int, len(playerSeasons))
	for _, ps := range playerSeasons {
		p, err := r.Queries.GetPlayerForPlayerSeason(ctx, ps.ID)
		if err != nil {
			return nil, err
		}
		aflIDToPlayerSeasonID[p.AFLPlayerID] = ps.ID
	}

	candidates, err := r.DataOps.LookupCandidates(ctx, aflIDToPlayerSeasonID)
	if err != nil {
		return nil, fmt.Errorf("lookup candidates: %w", err)
	}

	result, err := r.DataOps.ParseTeamSubmission(ctx, dataops.ParseTeamSubmissionParams{
		ClubSeasonID: clubSeasonID,
		TeamName:     input.TeamName,
		Post:         input.Post,
	}, playerSeasons, candidates)
	if err != nil {
		return nil, err
	}

	resolvedGQL := make([]*ResolvedPlayer, len(result.ResolvedPlayers))
	for i, rp := range result.ResolvedPlayers {
		var psID *string
		var resolvedName, resolvedClub *string
		if rp.PlayerSeasonID != 0 {
			id := toID(rp.PlayerSeasonID)
			psID = &id
			name := rp.BestMatch.Candidate.Name
			resolvedName = &name
			club := rp.BestMatch.Candidate.Club
			resolvedClub = &club
		}
		resolvedGQL[i] = &ResolvedPlayer{
			ParsedName:          rp.Parsed.Name,
			ClubHint:            rp.Parsed.ClubHint,
			ResolvedName:        resolvedName,
			ResolvedClub:        resolvedClub,
			Position:            rp.Parsed.Position,
			BackupPositions:     rp.Parsed.BackupPositions,
			InterchangePosition: rp.Parsed.InterchangePosition,
			Score:               rp.Parsed.Score,
			Notes:               rp.Parsed.Notes,
			PlayerSeasonID:      psID,
			Confidence:          rp.BestMatch.Confidence,
		}
	}

	needsReview := make([]int, len(result.NeedsReview))
	copy(needsReview, result.NeedsReview)

	return &ParseFFLTeamSubmissionResult{
		ResolvedPlayers: resolvedGQL,
		NeedsReview:     needsReview,
	}, nil
}

// ConfirmFFLTeamSubmission is the resolver for the confirmFFLTeamSubmission field.
func (r *mutationResolver) ConfirmFFLTeamSubmission(ctx context.Context, input ConfirmFFLTeamSubmissionInput) ([]*FFLPlayerMatch, error) {
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return nil, err
	}

	resolved := make([]dataops.ResolvedPlayer, 0, len(input.Players))
	for _, p := range input.Players {
		psID, err := fromID(p.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		parsed := application.ParsedPlayerRow{
			Position: p.Position,
			Score:    p.Score,
		}
		if p.BackupPositions != nil {
			parsed.BackupPositions = *p.BackupPositions
		}
		if p.InterchangePosition != nil {
			parsed.InterchangePosition = *p.InterchangePosition
		}
		resolved = append(resolved, dataops.ResolvedPlayer{
			Parsed:         parsed,
			PlayerSeasonID: psID,
			Confident:      true,
		})
	}

	pms, err := r.DataOps.ImportRoundTeams(ctx, dataops.ImportRoundTeamsParams{
		ClubMatchID:     clubMatchID,
		ResolvedPlayers: resolved,
	})
	if err != nil {
		var byeErr application.ByeIneligibleError
		if errors.As(err, &byeErr) {
			return nil, &gqlerror.Error{
				Message: byeErr.Error(),
				Extensions: map[string]any{
					"code":           "BYE_INELIGIBLE",
					"playerSeasonId": strconv.Itoa(byeErr.PlayerSeasonID),
				},
			}
		}
		return nil, err
	}

	result := make([]*FFLPlayerMatch, len(pms))
	for i, pm := range pms {
		player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		result[i] = convertPlayerMatch(pm, player)
	}
	return result, nil
}

// MarkFFLTeamFinal is the resolver for the markFFLTeamFinal field.
func (r *mutationResolver) MarkFFLTeamFinal(ctx context.Context, input MarkFFLTeamFinalInput) (bool, error) {
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return false, err
	}
	matchID, err := fromID(input.MatchID)
	if err != nil {
		return false, err
	}
	roundID, err := fromID(input.RoundID)
	if err != nil {
		return false, err
	}
	if err := r.DataOps.MarkTeamFinal(ctx, dataops.MarkTeamFinalParams{
		ClubMatchID: clubMatchID,
		MatchID:     matchID,
		RoundID:     roundID,
	}); err != nil {
		return false, err
	}
	return true, nil
}

// MarkFFLTeamSubmitted is the resolver for the markFFLTeamSubmitted field.
func (r *mutationResolver) MarkFFLTeamSubmitted(ctx context.Context, input MarkFFLTeamFinalInput) (bool, error) {
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return false, err
	}
	matchID, err := fromID(input.MatchID)
	if err != nil {
		return false, err
	}
	roundID, err := fromID(input.RoundID)
	if err != nil {
		return false, err
	}
	if err := r.DataOps.MarkTeamSubmitted(ctx, dataops.MarkTeamFinalParams{
		ClubMatchID: clubMatchID,
		MatchID:     matchID,
		RoundID:     roundID,
	}); err != nil {
		return false, err
	}
	return true, nil
}

// IngestFFLForumPage is the resolver for the ingestFFLForumPage field.
func (r *mutationResolver) IngestFFLForumPage(ctx context.Context, input IngestFFLForumPageInput) (*FFLPreviewedPage, error) {
	posts := make([]dataops.CapturedPost, 0, len(input.Posts))
	for _, p := range input.Posts {
		ts := ""
		if p.Timestamp != nil {
			ts = *p.Timestamp
		}
		posts = append(posts, dataops.CapturedPost{PostID: p.PostID, Author: p.Author, Timestamp: ts, HTML: p.HTML})
	}
	page := r.Captures.Ingest(ctx, dataops.CapturedPageParams{
		Season:     input.Season,
		RoundTitle: input.RoundTitle,
		TopicID:    input.TopicID,
		Posts:      posts,
	})
	return toPreviewedPage(page), nil
}

// ClearFFLForumCaptures is the resolver for the clearFFLForumCaptures field.
func (r *mutationResolver) ClearFFLForumCaptures(ctx context.Context) (bool, error) {
	r.Captures.Clear()
	return true, nil
}

// BuildFFLSeason is the resolver for the buildFFLSeason field.
func (r *mutationResolver) BuildFFLSeason(ctx context.Context, input BuildFFLSeasonInput) (*FFLBuiltSeason, error) {
	aflSeasonID, err := fromID(input.AflSeasonID)
	if err != nil {
		return nil, err
	}
	clubIDs := make([]int, len(input.ClubIds))
	for i, id := range input.ClubIds {
		v, err := fromID(id)
		if err != nil {
			return nil, err
		}
		clubIDs[i] = v
	}
	built, err := r.Builder.BuildSeason(ctx, dataops.BuildSeasonParams{
		SeasonName:  input.SeasonName,
		RulesID:     input.RulesID,
		AFLSeasonID: aflSeasonID,
		ClubIDs:     clubIDs,
	})
	if err != nil {
		return nil, err
	}
	css := make([]*FFLBuiltClubSeason, len(built.ClubSeasons))
	for i, cs := range built.ClubSeasons {
		css[i] = &FFLBuiltClubSeason{ClubName: cs.ClubName, ClubSeasonID: toID(cs.ClubSeasonID)}
	}
	return &FFLBuiltSeason{SeasonID: toID(built.SeasonID), RulesID: built.RulesID, ClubSeasons: css}, nil
}

// SaveFFLFixtures is the resolver for the saveFFLFixtures field.
func (r *mutationResolver) SaveFFLFixtures(ctx context.Context, input SaveFFLFixturesInput) (bool, error) {
	seasonID, err := fromID(input.SeasonID)
	if err != nil {
		return false, err
	}
	rounds := make([]dataops.RoundSpec, len(input.Rounds))
	for i, ri := range input.Rounds {
		spec := dataops.RoundSpec{
			Name:       ri.Name,
			AFLRoundID: 0,
			Type:       domain.RoundTypeMinor,
		}
		if ri.RoundID != nil && *ri.RoundID != "" {
			id, err := fromID(*ri.RoundID)
			if err != nil {
				return false, err
			}
			spec.RoundID = &id
		}
		if spec.AFLRoundID, err = fromID(ri.AflRoundID); err != nil {
			return false, err
		}
		if ri.RoundType != nil && *ri.RoundType != "" {
			spec.Type = domain.RoundType(*ri.RoundType)
		}
		for _, f := range ri.Fixtures {
			home, err := fromID(f.HomeClubSeasonID)
			if err != nil {
				return false, err
			}
			away, err := fromID(f.AwayClubSeasonID)
			if err != nil {
				return false, err
			}
			spec.Fixtures = append(spec.Fixtures, dataops.FixtureSpec{HomeClubSeasonID: home, AwayClubSeasonID: away})
		}
		for _, b := range ri.Byes {
			cs, err := fromID(b)
			if err != nil {
				return false, err
			}
			spec.Byes = append(spec.Byes, cs)
		}
		rounds[i] = spec
	}
	if err := r.Builder.SaveFixtures(ctx, seasonID, rounds); err != nil {
		return false, err
	}
	return true, nil
}

// FflCapturedPages is the resolver for the fflCapturedPages field.
func (r *queryResolver) FflCapturedPages(ctx context.Context) ([]*FFLPreviewedPage, error) {
	pages := r.Captures.Pages()
	out := make([]*FFLPreviewedPage, 0, len(pages))
	for _, pg := range pages {
		out = append(out, toPreviewedPage(pg))
	}
	return out, nil
}

// FflRulesEras is the resolver for the fflRulesEras field.
func (r *queryResolver) FflRulesEras(ctx context.Context) ([]*FFLRulesEra, error) {
	rules := domain.AllRules()
	out := make([]*FFLRulesEra, len(rules))
	for i, rule := range rules {
		out[i] = &FFLRulesEra{ID: rule.ID, Label: rule.Describe()}
	}
	return out, nil
}

// FflSeasonFixtures is the resolver for the fflSeasonFixtures field.
func (r *queryResolver) FflSeasonFixtures(ctx context.Context, seasonID string) ([]*FFLFixtureRound, error) {
	sID, err := fromID(seasonID)
	if err != nil {
		return nil, err
	}
	rounds, err := r.Builder.LoadFixtures(ctx, sID)
	if err != nil {
		return nil, err
	}
	out := make([]*FFLFixtureRound, len(rounds))
	for i, rnd := range rounds {
		fixtures := make([]*FFLFixturePairing, len(rnd.Fixtures))
		for j, f := range rnd.Fixtures {
			fixtures[j] = &FFLFixturePairing{
				HomeClubSeasonID: toID(f.HomeClubSeasonID),
				AwayClubSeasonID: toID(f.AwayClubSeasonID),
			}
		}
		byes := make([]string, len(rnd.Byes))
		for j, b := range rnd.Byes {
			byes[j] = toID(b)
		}
		out[i] = &FFLFixtureRound{
			RoundID:    toID(rnd.RoundID),
			Name:       rnd.Name,
			AflRoundID: toID(rnd.AFLRoundID),
			RoundType:  string(rnd.Type),
			Locked:     rnd.Locked,
			Fixtures:   fixtures,
			Byes:       byes,
		}
	}
	return out, nil
}
