package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
)

// FindAFLPlayerMatchByID is the resolver for the findAFLPlayerMatchByID field.
// FFL is not the owner of AFLPlayerMatch; return a stub so the router can fetch from the AFL subgraph.
func (r *entityResolver) FindAFLPlayerMatchByID(ctx context.Context, id string) (*AFLPlayerMatch, error) {
	return &AFLPlayerMatch{ID: id}, nil
}

// FindAFLPlayerSeasonByID is the resolver for the findAFLPlayerSeasonByID field.
// FFL is not the owner of AFLPlayerSeason; return a stub so the router can fetch from the AFL subgraph.
func (r *entityResolver) FindAFLPlayerSeasonByID(ctx context.Context, id string) (*AFLPlayerSeason, error) {
	return &AFLPlayerSeason{ID: id}, nil
}

// FindAFLSeasonByID is the resolver for the findAFLSeasonByID field.
// FFL is not the owner of AFLSeason; return a stub so the router can fetch from the AFL subgraph.
func (r *entityResolver) FindAFLSeasonByID(ctx context.Context, id string) (*AFLSeason, error) {
	return &AFLSeason{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
