// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type AFLPlayerMatch struct {
	ID string `json:"id"`
}

func (AFLPlayerMatch) IsEntity() {}

type AFLPlayerSeason struct {
	ID string `json:"id"`
}

func (AFLPlayerSeason) IsEntity() {}

type AFLSeason struct {
	ID string `json:"id"`
}

func (AFLSeason) IsEntity() {}

type AddFFLPlayerToSeasonInput struct {
	PlayerID     string `json:"playerId"`
	ClubSeasonID string `json:"clubSeasonId"`
}

type AddFFLSquadPlayerInput struct {
	AflPlayerID   string `json:"aflPlayerId"`
	AflPlayerName string `json:"aflPlayerName"`
	ClubSeasonID  string `json:"clubSeasonId"`
}

type CalculateFFLFantasyScoreInput struct {
	PlayerMatchID string `json:"playerMatchId"`
	Goals         int    `json:"goals"`
	Kicks         int    `json:"kicks"`
	Handballs     int    `json:"handballs"`
	Marks         int    `json:"marks"`
	Tackles       int    `json:"tackles"`
	Hitouts       int    `json:"hitouts"`
}

type ConfirmFFLTeamSubmissionInput struct {
	ClubMatchID string                     `json:"clubMatchId"`
	Players     []*ConfirmedFFLPlayerInput `json:"players"`
}

type ConfirmedFFLPlayerInput struct {
	PlayerSeasonID      string  `json:"playerSeasonId"`
	Position            string  `json:"position"`
	BackupPositions     *string `json:"backupPositions,omitempty"`
	InterchangePosition *string `json:"interchangePosition,omitempty"`
	Score               *int    `json:"score,omitempty"`
}

type CreateFFLPlayerInput struct {
	Name        string `json:"name"`
	AflPlayerID string `json:"aflPlayerId"`
}

type FFLClub struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type FFLClubMatch struct {
	ID            string            `json:"id"`
	Club          *FFLClub          `json:"club"`
	Score         int               `json:"score"`
	PlayerMatches []*FFLPlayerMatch `json:"playerMatches"`
}

type FFLClubSeason struct {
	ID         string                     `json:"id"`
	Club       *FFLClub                   `json:"club"`
	Season     *FFLSeason                 `json:"season"`
	Played     int                        `json:"played"`
	Won        int                        `json:"won"`
	Lost       int                        `json:"lost"`
	Drawn      int                        `json:"drawn"`
	For        int                        `json:"for"`
	Against    int                        `json:"against"`
	Percentage float64                    `json:"percentage"`
	Players    *FFLPlayerSeasonConnection `json:"players"`
}

type FFLMatch struct {
	ID            string        `json:"id"`
	Venue         *string       `json:"venue,omitempty"`
	StartTime     *string       `json:"startTime,omitempty"`
	Result        *string       `json:"result,omitempty"`
	Round         *FFLRound     `json:"round"`
	HomeClubMatch *FFLClubMatch `json:"homeClubMatch,omitempty"`
	AwayClubMatch *FFLClubMatch `json:"awayClubMatch,omitempty"`
}

type FFLPlayer struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	AflPlayerID string `json:"aflPlayerId"`
}

type FFLPlayerMatch struct {
	ID                  string          `json:"id"`
	PlayerSeasonID      string          `json:"playerSeasonId"`
	Player              *FFLPlayer      `json:"player"`
	Position            *string         `json:"position,omitempty"`
	Status              *string         `json:"status,omitempty"`
	BackupPositions     *string         `json:"backupPositions,omitempty"`
	InterchangePosition *string         `json:"interchangePosition,omitempty"`
	Score               int             `json:"score"`
	AflPlayerMatchID    *string         `json:"aflPlayerMatchId,omitempty"`
	AflPlayerMatch      *AFLPlayerMatch `json:"aflPlayerMatch,omitempty"`
}

type FFLPlayerSeason struct {
	ID                string           `json:"id"`
	Player            *FFLPlayer       `json:"player"`
	ClubSeasonID      string           `json:"clubSeasonId"`
	AflPlayerSeasonID *string          `json:"aflPlayerSeasonId,omitempty"`
	AflPlayerSeason   *AFLPlayerSeason `json:"aflPlayerSeason,omitempty"`
}

type FFLPlayerSeasonConnection struct {
	Nodes    []*FFLPlayerSeason `json:"nodes"`
	PageInfo *PageInfo          `json:"pageInfo"`
}

type FFLPlayerSeasonFilter struct {
	Active *bool `json:"active,omitempty"`
}

type FFLRound struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	AflRoundID *string     `json:"aflRoundId,omitempty"`
	Season     *FFLSeason  `json:"season"`
	Matches    []*FFLMatch `json:"matches"`
}

type FFLSeason struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Ladder    []*FFLClubSeason `json:"ladder"`
	Rounds    []*FFLRound      `json:"rounds"`
	AflSeason *AFLSeason       `json:"aflSeason,omitempty"`
}

type FFLTeamPlayerInput struct {
	PlayerSeasonID      string  `json:"playerSeasonId"`
	Position            string  `json:"position"`
	BackupPositions     *string `json:"backupPositions,omitempty"`
	InterchangePosition *string `json:"interchangePosition,omitempty"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
	TotalCount  *int    `json:"totalCount,omitempty"`
}

type ParseFFLTeamSubmissionInput struct {
	ClubSeasonID string `json:"clubSeasonId"`
	ClubMatchID  string `json:"clubMatchId"`
	TeamName     string `json:"teamName"`
	Post         string `json:"post"`
}

type ParseFFLTeamSubmissionResult struct {
	ResolvedPlayers []*ResolvedPlayer `json:"resolvedPlayers"`
	NeedsReview     []int             `json:"needsReview"`
}

type Query struct {
}

type ResolvedPlayer struct {
	ParsedName          string  `json:"parsedName"`
	ClubHint            string  `json:"clubHint"`
	ResolvedName        *string `json:"resolvedName,omitempty"`
	ResolvedClub        *string `json:"resolvedClub,omitempty"`
	Position            string  `json:"position"`
	BackupPositions     string  `json:"backupPositions"`
	InterchangePosition string  `json:"interchangePosition"`
	Score               *int    `json:"score,omitempty"`
	Notes               string  `json:"notes"`
	PlayerSeasonID      *string `json:"playerSeasonId,omitempty"`
	Confidence          float64 `json:"confidence"`
}

type SetFFLTeamInput struct {
	ClubMatchID string                `json:"clubMatchId"`
	Players     []*FFLTeamPlayerInput `json:"players"`
}

type UpdateFFLPlayerInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
