// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type AddFFLPlayerToSeasonInput struct {
	PlayerID     string `json:"playerId"`
	ClubSeasonID string `json:"clubSeasonId"`
}

type AddFFLRosterPlayerInput struct {
	AflPlayerID   string `json:"aflPlayerId"`
	AflPlayerName string `json:"aflPlayerName"`
	ClubSeasonID  string `json:"clubSeasonId"`
}

type CalculateFFLFantasyScoreInput struct {
	PlayerMatchID string `json:"playerMatchId"`
	Goals         int    `json:"goals"`
	Kicks         int    `json:"kicks"`
	Handballs     int    `json:"handballs"`
	Marks         int    `json:"marks"`
	Tackles       int    `json:"tackles"`
	Hitouts       int    `json:"hitouts"`
}

type CreateFFLPlayerInput struct {
	Name        string `json:"name"`
	AflPlayerID string `json:"aflPlayerId"`
}

type FFLClub struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type FFLClubMatch struct {
	ID            string            `json:"id"`
	Club          *FFLClub          `json:"club"`
	Score         int               `json:"score"`
	PlayerMatches []*FFLPlayerMatch `json:"playerMatches"`
}

type FFLClubSeason struct {
	ID         string            `json:"id"`
	Club       *FFLClub          `json:"club"`
	Played     int               `json:"played"`
	Won        int               `json:"won"`
	Lost       int               `json:"lost"`
	Drawn      int               `json:"drawn"`
	For        int               `json:"for"`
	Against    int               `json:"against"`
	Percentage float64           `json:"percentage"`
	Roster     []*FFLRosterEntry `json:"roster"`
}

type FFLLineupPlayerInput struct {
	PlayerSeasonID      string  `json:"playerSeasonId"`
	Position            string  `json:"position"`
	BackupPositions     *string `json:"backupPositions,omitempty"`
	InterchangePosition *string `json:"interchangePosition,omitempty"`
}

type FFLMatch struct {
	ID            string        `json:"id"`
	Venue         *string       `json:"venue,omitempty"`
	StartTime     *string       `json:"startTime,omitempty"`
	Result        *string       `json:"result,omitempty"`
	HomeClubMatch *FFLClubMatch `json:"homeClubMatch,omitempty"`
	AwayClubMatch *FFLClubMatch `json:"awayClubMatch,omitempty"`
}

type FFLPlayer struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	AflPlayerID string `json:"aflPlayerId"`
}

type FFLPlayerMatch struct {
	ID                  string     `json:"id"`
	PlayerSeasonID      string     `json:"playerSeasonId"`
	Player              *FFLPlayer `json:"player"`
	Position            *string    `json:"position,omitempty"`
	Status              *string    `json:"status,omitempty"`
	BackupPositions     *string    `json:"backupPositions,omitempty"`
	InterchangePosition *string    `json:"interchangePosition,omitempty"`
	Score               int        `json:"score"`
}

type FFLPlayerSeason struct {
	ID           string `json:"id"`
	PlayerID     string `json:"playerId"`
	ClubSeasonID string `json:"clubSeasonId"`
}

type FFLRosterEntry struct {
	PlayerSeasonID    string     `json:"playerSeasonId"`
	Player            *FFLPlayer `json:"player"`
	AflPlayerSeasonID *string    `json:"aflPlayerSeasonId,omitempty"`
}

type FFLRound struct {
	ID      string      `json:"id"`
	Name    string      `json:"name"`
	Season  *FFLSeason  `json:"season"`
	Matches []*FFLMatch `json:"matches"`
}

type FFLSeason struct {
	ID     string           `json:"id"`
	Name   string           `json:"name"`
	Ladder []*FFLClubSeason `json:"ladder"`
	Rounds []*FFLRound      `json:"rounds"`
}

type Mutation struct {
}

type Query struct {
}

type SetFFLLineupInput struct {
	ClubMatchID string                  `json:"clubMatchId"`
	Players     []*FFLLineupPlayerInput `json:"players"`
}

type UpdateFFLPlayerInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
