package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"strconv"
	"xffl/services/ffl/internal/application"
	"xffl/services/ffl/internal/domain"

	"github.com/vektah/gqlparser/v2/gqlerror"
)

// AddFFLPlayerToSeason is the resolver for the addFFLPlayerToSeason field.
func (r *mutationResolver) AddFFLPlayerToSeason(ctx context.Context, input AddFFLPlayerToSeasonInput) (*FFLPlayerSeason, error) {
	clubSeasonID, err := fromID(input.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	aflPlayerSeasonID, err := fromID(input.AflPlayerSeasonID)
	if err != nil {
		return nil, err
	}
	var fromRoundID *int
	if input.FromRoundID != nil {
		id, err := fromID(*input.FromRoundID)
		if err != nil {
			return nil, err
		}
		fromRoundID = &id
	}
	ps, err := r.Commands.AddPlayerToSeason(ctx, clubSeasonID, aflPlayerSeasonID, fromRoundID, input.CostCents)
	if err != nil {
		return nil, err
	}
	player, err := r.Queries.GetPlayerForPlayerSeason(ctx, ps.ID)
	if err != nil {
		return nil, err
	}
	return convertPlayerSeason(ps, player), nil
}

// RemoveFFLPlayerFromSeason is the resolver for the removeFFLPlayerFromSeason field.
func (r *mutationResolver) RemoveFFLPlayerFromSeason(ctx context.Context, input RemoveFFLPlayerFromSeasonInput) (bool, error) {
	parsed, err := fromID(input.ID)
	if err != nil {
		return false, err
	}
	roundID, err := fromID(input.ToRoundID)
	if err != nil {
		return false, err
	}
	if err := r.Commands.RemovePlayerFromSeason(ctx, parsed, roundID); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateFFLPlayerSeason is the resolver for the updateFFLPlayerSeason field.
func (r *mutationResolver) UpdateFFLPlayerSeason(ctx context.Context, input UpdateFFLPlayerSeasonInput) (*FFLPlayerSeason, error) {
	id, err := fromID(input.ID)
	if err != nil {
		return nil, err
	}
	ps, err := r.Commands.UpdatePlayerSeasonDetails(ctx, id, input.Notes)
	if err != nil {
		return nil, err
	}
	player, err := r.Queries.GetPlayerForPlayerSeason(ctx, ps.ID)
	if err != nil {
		return nil, err
	}
	return convertPlayerSeason(ps, player), nil
}

// CalculateFFLFantasyScore is the resolver for the calculateFFLFantasyScore field.
func (r *mutationResolver) CalculateFFLFantasyScore(ctx context.Context, input CalculateFFLFantasyScoreInput) (*FFLPlayerMatch, error) {
	pmID, err := fromID(input.PlayerMatchID)
	if err != nil {
		return nil, err
	}
	stats := domain.AFLStats{
		Goals:     input.Goals,
		Kicks:     input.Kicks,
		Handballs: input.Handballs,
		Marks:     input.Marks,
		Tackles:   input.Tackles,
		Hitouts:   input.Hitouts,
	}
	pm, err := r.Commands.CalculateFantasyScore(ctx, pmID, stats)
	if err != nil {
		return nil, err
	}
	player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
	if err != nil {
		return nil, err
	}
	return convertPlayerMatch(pm, player), nil
}

// SetFFLTeam is the resolver for the setFFLTeam field.
func (r *mutationResolver) SetFFLTeam(ctx context.Context, input SetFFLTeamInput) ([]*FFLPlayerMatch, error) {
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return nil, err
	}
	entries := make([]application.SetTeamEntry, len(input.Players))
	for i, p := range input.Players {
		psID, err := fromID(p.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		entries[i] = application.SetTeamEntry{
			PlayerSeasonID:      psID,
			Position:            p.Position,
			BackupPositions:     p.BackupPositions,
			InterchangePosition: p.InterchangePosition,
			DisplayOrder:        p.DisplayOrder,
		}
	}
	pms, err := r.Commands.SetTeam(ctx, application.SetTeamParams{ClubMatchID: clubMatchID, Entries: entries})
	if err != nil {
		var byeErr application.ByeIneligibleError
		if errors.As(err, &byeErr) {
			return nil, &gqlerror.Error{
				Message: byeErr.Error(),
				Extensions: map[string]any{
					"code":           "BYE_INELIGIBLE",
					"playerSeasonId": strconv.Itoa(byeErr.PlayerSeasonID),
				},
			}
		}
		return nil, err
	}
	result := make([]*FFLPlayerMatch, len(pms))
	for i, pm := range pms {
		player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		result[i] = convertPlayerMatch(pm, player)
	}
	return result, nil
}

// RecalculateFFLLadder is the resolver for the recalculateFFLLadder field.
func (r *mutationResolver) RecalculateFFLLadder(ctx context.Context, seasonID string) (bool, error) {
	id, err := fromID(seasonID)
	if err != nil {
		return false, err
	}
	if err := r.Commands.RecalculateFflLadder(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// RecalculateFFLClubMatchScore is the resolver for the recalculateFFLClubMatchScore field.
func (r *mutationResolver) RecalculateFFLClubMatchScore(ctx context.Context, clubMatchID string) (int, error) {
	id, err := fromID(clubMatchID)
	if err != nil {
		return 0, err
	}
	score, err := r.Commands.RecalculateScore(ctx, id)
	if err != nil {
		return 0, err
	}
	return score, nil
}

// DeclareFFLSubstitutions is the resolver for the declareFFLSubstitutions field.
func (r *mutationResolver) DeclareFFLSubstitutions(ctx context.Context, input DeclareFFLSubstitutionsInput) ([]*FFLPlayerMatch, error) {
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return nil, err
	}

	subs := make([]domain.SubPairing, 0, len(input.Subs))
	for _, pair := range input.Subs {
		replaced, err := fromID(pair.ReplacedPmID)
		if err != nil {
			return nil, err
		}
		replacing, err := fromID(pair.ReplacingPmID)
		if err != nil {
			return nil, err
		}
		subs = append(subs, domain.SubPairing{ReplacedPMID: replaced, ReplacingPMID: replacing})
	}

	var interchange *domain.SubPairing
	if input.Interchange != nil {
		replaced, err := fromID(input.Interchange.ReplacedPmID)
		if err != nil {
			return nil, err
		}
		replacing, err := fromID(input.Interchange.ReplacingPmID)
		if err != nil {
			return nil, err
		}
		interchange = &domain.SubPairing{ReplacedPMID: replaced, ReplacingPMID: replacing}
	}

	pms, err := r.Commands.DeclareSubs(ctx, clubMatchID, subs, interchange)
	if err != nil {
		return nil, err
	}
	result := make([]*FFLPlayerMatch, len(pms))
	for i, pm := range pms {
		player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		result[i] = convertPlayerMatch(pm, player)
	}
	return result, nil
}

// ReorderFFLPlayerMatch is the resolver for the reorderFFLPlayerMatch field.
func (r *mutationResolver) ReorderFFLPlayerMatch(ctx context.Context, id string, direction FFLReorderDirection) ([]*FFLPlayerMatch, error) {
	pmID, err := fromID(id)
	if err != nil {
		return nil, err
	}
	dir := application.ReorderDirection(direction)
	pms, err := r.Commands.ReorderPlayerMatch(ctx, pmID, dir)
	if err != nil {
		return nil, err
	}
	result := make([]*FFLPlayerMatch, len(pms))
	for i, pm := range pms {
		player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		result[i] = convertPlayerMatch(pm, player)
	}
	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
