package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"xffl/services/ffl/internal/application"
	"xffl/services/ffl/internal/domain"
)

// CreateFFLPlayer is the resolver for the createFFLPlayer field.
func (r *mutationResolver) CreateFFLPlayer(ctx context.Context, input CreateFFLPlayerInput) (*FFLPlayer, error) {
	aflPlayerID, err := fromID(input.AflPlayerID)
	if err != nil {
		return nil, err
	}
	p, err := r.Commands.CreatePlayer(ctx, input.Name, aflPlayerID)
	if err != nil {
		return nil, err
	}
	return convertPlayer(p), nil
}

// UpdateFFLPlayer is the resolver for the updateFFLPlayer field.
func (r *mutationResolver) UpdateFFLPlayer(ctx context.Context, input UpdateFFLPlayerInput) (*FFLPlayer, error) {
	id, err := fromID(input.ID)
	if err != nil {
		return nil, err
	}
	p, err := r.Commands.UpdatePlayer(ctx, id, input.Name)
	if err != nil {
		return nil, err
	}
	return convertPlayer(p), nil
}

// DeleteFFLPlayer is the resolver for the deleteFFLPlayer field.
func (r *mutationResolver) DeleteFFLPlayer(ctx context.Context, id string) (bool, error) {
	parsed, err := fromID(id)
	if err != nil {
		return false, err
	}
	if err := r.Commands.DeletePlayer(ctx, parsed); err != nil {
		return false, err
	}
	return true, nil
}

// AddFFLPlayerToSeason is the resolver for the addFFLPlayerToSeason field.
func (r *mutationResolver) AddFFLPlayerToSeason(ctx context.Context, input AddFFLPlayerToSeasonInput) (*FFLPlayerSeason, error) {
	playerID, err := fromID(input.PlayerID)
	if err != nil {
		return nil, err
	}
	clubSeasonID, err := fromID(input.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	ps, err := r.Commands.AddPlayerToSeason(ctx, playerID, clubSeasonID)
	if err != nil {
		return nil, err
	}
	return convertPlayerSeason(ps), nil
}

// RemoveFFLPlayerFromSeason is the resolver for the removeFFLPlayerFromSeason field.
func (r *mutationResolver) RemoveFFLPlayerFromSeason(ctx context.Context, id string) (bool, error) {
	parsed, err := fromID(id)
	if err != nil {
		return false, err
	}
	if err := r.Commands.RemovePlayerFromSeason(ctx, parsed); err != nil {
		return false, err
	}
	return true, nil
}

// CalculateFFLFantasyScore is the resolver for the calculateFFLFantasyScore field.
func (r *mutationResolver) CalculateFFLFantasyScore(ctx context.Context, input CalculateFFLFantasyScoreInput) (*FFLPlayerMatch, error) {
	pmID, err := fromID(input.PlayerMatchID)
	if err != nil {
		return nil, err
	}
	stats := domain.AFLStats{
		Goals:     input.Goals,
		Kicks:     input.Kicks,
		Handballs: input.Handballs,
		Marks:     input.Marks,
		Tackles:   input.Tackles,
		Hitouts:   input.Hitouts,
	}
	pm, err := r.Commands.CalculateFantasyScore(ctx, pmID, stats)
	if err != nil {
		return nil, err
	}
	player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
	if err != nil {
		return nil, err
	}
	return convertPlayerMatch(pm, player), nil
}

// SetFFLLineup is the resolver for the setFFLLineup field.
func (r *mutationResolver) SetFFLLineup(ctx context.Context, input SetFFLLineupInput) ([]*FFLPlayerMatch, error) {
	clubMatchID, err := fromID(input.ClubMatchID)
	if err != nil {
		return nil, err
	}
	entries := make([]application.SetLineupEntry, len(input.Players))
	for i, p := range input.Players {
		psID, err := fromID(p.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		entries[i] = application.SetLineupEntry{
			PlayerSeasonID:      psID,
			Position:            p.Position,
			BackupPositions:     p.BackupPositions,
			InterchangePosition: p.InterchangePosition,
		}
	}
	pms, err := r.Commands.SetLineup(ctx, clubMatchID, entries)
	if err != nil {
		return nil, err
	}
	result := make([]*FFLPlayerMatch, len(pms))
	for i, pm := range pms {
		player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		result[i] = convertPlayerMatch(pm, player)
	}
	return result, nil
}

// AddFFLRosterPlayer is the resolver for the addFFLRosterPlayer field.
func (r *mutationResolver) AddFFLRosterPlayer(ctx context.Context, input AddFFLRosterPlayerInput) (*FFLPlayerSeason, error) {
	aflPlayerID, err := fromID(input.AflPlayerID)
	if err != nil {
		return nil, err
	}
	clubSeasonID, err := fromID(input.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	ps, err := r.Commands.AddAFLPlayerToRoster(ctx, aflPlayerID, input.AflPlayerName, clubSeasonID)
	if err != nil {
		return nil, err
	}
	return convertPlayerSeason(ps), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
