package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
)

// PlayerMatches is the resolver for the playerMatches field.
func (r *fFLClubMatchResolver) PlayerMatches(ctx context.Context, obj *FFLClubMatch) ([]*FFLPlayerMatch, error) {
	cmID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	pms, err := r.Queries.GetPlayerMatches(ctx, cmID)
	if err != nil {
		return nil, err
	}
	loaders := LoadersFromCtx(ctx)
	result := make([]*FFLPlayerMatch, len(pms))
	for i, pm := range pms {
		player, err := loaders.PlayerByPlayerSeasonID.Load(ctx, pm.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		result[i] = convertPlayerMatch(pm, *player)
	}
	return result, nil
}

// Players is the resolver for the players field.
func (r *fFLClubSeasonResolver) Players(ctx context.Context, obj *FFLClubSeason, first *int, after *string, filter *FFLPlayerSeasonFilter) (*FFLPlayerSeasonConnection, error) {
	csID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	playerSeasons, err := r.Queries.GetPlayerSeasons(ctx, csID)
	if err != nil {
		return nil, err
	}
	loaders := LoadersFromCtx(ctx)
	nodes := make([]*FFLPlayerSeason, len(playerSeasons))
	for i, ps := range playerSeasons {
		player, err := loaders.PlayerByPlayerSeasonID.Load(ctx, ps.ID)
		if err != nil {
			return nil, err
		}
		nodes[i] = convertPlayerSeason(ps, *player)
	}
	total := len(nodes)
	return &FFLPlayerSeasonConnection{
		Nodes:    nodes,
		PageInfo: &PageInfo{HasNextPage: false, TotalCount: &total},
	}, nil
}

// HomeClubMatch is the resolver for the homeClubMatch field.
func (r *fFLMatchResolver) HomeClubMatch(ctx context.Context, obj *FFLMatch) (*FFLClubMatch, error) {
	matchID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	match, err := LoadersFromCtx(ctx).MatchByID.Load(ctx, matchID)
	if err != nil {
		return nil, err
	}
	if match.Home.ID == 0 {
		return nil, nil
	}
	cm, err := r.Queries.GetClubMatch(ctx, match.Home.ID)
	if err != nil {
		return nil, err
	}
	club, err := r.Queries.GetClubForClubSeason(ctx, cm.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	return convertClubMatch(cm, club), nil
}

// AwayClubMatch is the resolver for the awayClubMatch field.
func (r *fFLMatchResolver) AwayClubMatch(ctx context.Context, obj *FFLMatch) (*FFLClubMatch, error) {
	matchID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	match, err := LoadersFromCtx(ctx).MatchByID.Load(ctx, matchID)
	if err != nil {
		return nil, err
	}
	if match.Away.ID == 0 {
		return nil, nil
	}
	cm, err := r.Queries.GetClubMatch(ctx, match.Away.ID)
	if err != nil {
		return nil, err
	}
	club, err := r.Queries.GetClubForClubSeason(ctx, cm.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	return convertClubMatch(cm, club), nil
}

// PlayerSeason is the resolver for the playerSeason field.
func (r *fFLPlayerMatchResolver) PlayerSeason(ctx context.Context, obj *FFLPlayerMatch) (*FFLPlayerSeason, error) {
	psID, err := fromID(obj.PlayerSeasonID)
	if err != nil {
		return nil, err
	}
	ps, err := r.Queries.GetPlayerSeasonByID(ctx, psID)
	if err != nil {
		return nil, err
	}
	loaders := LoadersFromCtx(ctx)
	player, err := loaders.PlayerByPlayerSeasonID.Load(ctx, psID)
	if err != nil {
		return nil, err
	}
	return convertPlayerSeason(ps, *player), nil
}

// AflPlayerMatchID is the resolver for the aflPlayerMatchId field.
func (r *fFLPlayerMatchResolver) AflPlayerMatchID(ctx context.Context, obj *FFLPlayerMatch) (*string, error) {
	return obj.AflPlayerMatchID, nil
}

// AflPlayerMatch is the resolver for the aflPlayerMatch field.
// Returns a stub with the AFL entity ID; the router fetches full data from the AFL subgraph.
func (r *fFLPlayerMatchResolver) AflPlayerMatch(ctx context.Context, obj *FFLPlayerMatch) (*AFLPlayerMatch, error) {
	if obj.AflPlayerMatchID == nil {
		return nil, nil
	}
	return &AFLPlayerMatch{ID: *obj.AflPlayerMatchID}, nil
}

// AflPlayerSeason is the resolver for the aflPlayerSeason field.
// Returns a stub with the AFL entity ID; the router fetches full data from the AFL subgraph.
func (r *fFLPlayerSeasonResolver) AflPlayerSeason(ctx context.Context, obj *FFLPlayerSeason) (*AFLPlayerSeason, error) {
	if obj.AflPlayerSeasonID == nil {
		return nil, nil
	}
	return &AFLPlayerSeason{ID: *obj.AflPlayerSeasonID}, nil
}

// AflRound is the resolver for the aflRound field.
func (r *fFLRoundResolver) AflRound(ctx context.Context, obj *FFLRound) (*AFLRound, error) {
	if obj.AflRoundID == nil {
		return nil, nil
	}
	return &AFLRound{ID: *obj.AflRoundID}, nil
}

// Season is the resolver for the season field.
func (r *fFLRoundResolver) Season(ctx context.Context, obj *FFLRound) (*FFLSeason, error) {
	roundID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	round, err := r.Queries.GetRound(ctx, roundID)
	if err != nil {
		return nil, err
	}
	season, err := r.Queries.GetSeason(ctx, round.SeasonID)
	if err != nil {
		return nil, err
	}
	return convertSeason(season), nil
}

// Matches is the resolver for the matches field.
func (r *fFLRoundResolver) Matches(ctx context.Context, obj *FFLRound) ([]*FFLMatch, error) {
	roundID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	matches, err := r.Queries.GetMatches(ctx, roundID)
	if err != nil {
		return nil, err
	}
	return convertMatches(matches), nil
}

// Ladder is the resolver for the ladder field.
func (r *fFLSeasonResolver) Ladder(ctx context.Context, obj *FFLSeason) ([]*FFLClubSeason, error) {
	seasonID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	clubSeasons, err := r.Queries.GetClubSeasons(ctx, seasonID)
	if err != nil {
		return nil, err
	}
	season, err := r.Queries.GetSeason(ctx, seasonID)
	if err != nil {
		return nil, err
	}
	loaders := LoadersFromCtx(ctx)
	result := make([]*FFLClubSeason, len(clubSeasons))
	for i, cs := range clubSeasons {
		club, err := loaders.ClubByID.Load(ctx, cs.ClubID)
		if err != nil {
			return nil, err
		}
		result[i] = convertClubSeason(cs, *club, season)
	}
	return result, nil
}

// Rounds is the resolver for the rounds field.
func (r *fFLSeasonResolver) Rounds(ctx context.Context, obj *FFLSeason) ([]*FFLRound, error) {
	seasonID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	rounds, err := r.Queries.GetRounds(ctx, seasonID)
	if err != nil {
		return nil, err
	}
	return convertRounds(rounds), nil
}

// AflSeason is the resolver for the aflSeason field.
func (r *fFLSeasonResolver) AflSeason(ctx context.Context, obj *FFLSeason) (*AFLSeason, error) {
	id, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	season, err := r.Queries.GetSeason(ctx, id)
	if err != nil {
		return nil, err
	}
	if season.AFLSeasonID == nil {
		return nil, nil
	}
	return &AFLSeason{ID: toID(*season.AFLSeasonID)}, nil
}

// FflSeasons is the resolver for the fflSeasons field.
func (r *queryResolver) FflSeasons(ctx context.Context) ([]*FFLSeason, error) {
	seasons, err := r.Queries.GetSeasons(ctx)
	if err != nil {
		return nil, err
	}
	return convertSeasons(seasons), nil
}

// FflSeason is the resolver for the fflSeason field.
func (r *queryResolver) FflSeason(ctx context.Context, id string) (*FFLSeason, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, err
	}
	season, err := r.Queries.GetSeason(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return convertSeason(season), nil
}

// FflRound is the resolver for the fflRound field.
func (r *queryResolver) FflRound(ctx context.Context, id string) (*FFLRound, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, err
	}
	round, err := r.Queries.GetRound(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return convertRound(round), nil
}

// FflMatch is the resolver for the fflMatch field.
func (r *queryResolver) FflMatch(ctx context.Context, id string) (*FFLMatch, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, err
	}
	match, err := r.Queries.GetMatch(ctx, parsed)
	if err != nil {
		return nil, err
	}
	round, err := r.Queries.GetRound(ctx, match.RoundID)
	if err != nil {
		return nil, err
	}
	fflMatch := convertMatch(match)
	fflMatch.Round = convertRound(round)
	return fflMatch, nil
}

// FflClubs is the resolver for the fflClubs field.
func (r *queryResolver) FflClubs(ctx context.Context) ([]*FFLClub, error) {
	clubs, err := r.Queries.GetClubs(ctx)
	if err != nil {
		return nil, err
	}
	return convertClubs(clubs), nil
}

// FflClub is the resolver for the fflClub field.
func (r *queryResolver) FflClub(ctx context.Context, id string) (*FFLClub, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, err
	}
	club, err := r.Queries.GetClub(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return convertClub(club), nil
}

// FflClubSeason is the resolver for the fflClubSeason field.
func (r *queryResolver) FflClubSeason(ctx context.Context, seasonID string, clubID string) (*FFLClubSeason, error) {
	sID, err := fromID(seasonID)
	if err != nil {
		return nil, err
	}
	cID, err := fromID(clubID)
	if err != nil {
		return nil, err
	}
	cs, err := r.Queries.GetClubSeasonByClubAndSeason(ctx, cID, sID)
	if err != nil {
		return nil, err
	}
	club, err := r.Queries.GetClubForClubSeason(ctx, cs.ID)
	if err != nil {
		return nil, err
	}
	season, err := r.Queries.GetSeason(ctx, sID)
	if err != nil {
		return nil, err
	}
	return convertClubSeason(cs, club, season), nil
}

// FflPlayers is the resolver for the fflPlayers field.
func (r *queryResolver) FflPlayers(ctx context.Context) ([]*FFLPlayer, error) {
	players, err := r.Queries.GetPlayers(ctx)
	if err != nil {
		return nil, err
	}
	return convertPlayers(players), nil
}

// FflPlayer is the resolver for the fflPlayer field.
func (r *queryResolver) FflPlayer(ctx context.Context, id string) (*FFLPlayer, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, err
	}
	player, err := r.Queries.GetPlayer(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return convertPlayer(player), nil
}

// FflRoundByAflRound is the resolver for the fflRoundByAflRound field.
func (r *queryResolver) FflRoundByAflRound(ctx context.Context, aflRoundID string) (*FFLRound, error) {
	id, err := fromID(aflRoundID)
	if err != nil {
		return nil, err
	}
	round, err := r.Queries.GetRoundByAFLRoundID(ctx, id)
	if err != nil {
		return nil, err
	}
	if round == nil {
		return nil, nil
	}
	return convertRound(*round), nil
}

// FFLClubMatch returns FFLClubMatchResolver implementation.
func (r *Resolver) FFLClubMatch() FFLClubMatchResolver { return &fFLClubMatchResolver{r} }

// FFLClubSeason returns FFLClubSeasonResolver implementation.
func (r *Resolver) FFLClubSeason() FFLClubSeasonResolver { return &fFLClubSeasonResolver{r} }

// FFLMatch returns FFLMatchResolver implementation.
func (r *Resolver) FFLMatch() FFLMatchResolver { return &fFLMatchResolver{r} }

// FFLPlayerMatch returns FFLPlayerMatchResolver implementation.
func (r *Resolver) FFLPlayerMatch() FFLPlayerMatchResolver { return &fFLPlayerMatchResolver{r} }

// FFLPlayerSeason returns FFLPlayerSeasonResolver implementation.
func (r *Resolver) FFLPlayerSeason() FFLPlayerSeasonResolver { return &fFLPlayerSeasonResolver{r} }

// FFLRound returns FFLRoundResolver implementation.
func (r *Resolver) FFLRound() FFLRoundResolver { return &fFLRoundResolver{r} }

// FFLSeason returns FFLSeasonResolver implementation.
func (r *Resolver) FFLSeason() FFLSeasonResolver { return &fFLSeasonResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type fFLClubMatchResolver struct{ *Resolver }
type fFLClubSeasonResolver struct{ *Resolver }
type fFLMatchResolver struct{ *Resolver }
type fFLPlayerMatchResolver struct{ *Resolver }
type fFLPlayerSeasonResolver struct{ *Resolver }
type fFLRoundResolver struct{ *Resolver }
type fFLSeasonResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
