package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
)

// PlayerMatches is the resolver for the playerMatches field.
func (r *fFLClubMatchResolver) PlayerMatches(ctx context.Context, obj *FFLClubMatch) ([]*FFLPlayerMatch, error) {
	cmID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	pms, err := r.Queries.GetPlayerMatches(ctx, cmID)
	if err != nil {
		return nil, err
	}
	result := make([]*FFLPlayerMatch, len(pms))
	for i, pm := range pms {
		player, err := r.Queries.GetPlayerForPlayerSeason(ctx, pm.PlayerSeasonID)
		if err != nil {
			return nil, err
		}
		result[i] = convertPlayerMatch(pm, player)
	}
	return result, nil
}

// HomeClubMatch is the resolver for the homeClubMatch field.
func (r *fFLMatchResolver) HomeClubMatch(ctx context.Context, obj *FFLMatch) (*FFLClubMatch, error) {
	matchID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	match, err := r.Queries.GetMatch(ctx, matchID)
	if err != nil {
		return nil, err
	}
	if match.Home.ID == 0 {
		return nil, nil
	}
	cm, err := r.Queries.GetClubMatch(ctx, match.Home.ID)
	if err != nil {
		return nil, err
	}
	club, err := r.Queries.GetClubForClubSeason(ctx, cm.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	return convertClubMatch(cm, club), nil
}

// AwayClubMatch is the resolver for the awayClubMatch field.
func (r *fFLMatchResolver) AwayClubMatch(ctx context.Context, obj *FFLMatch) (*FFLClubMatch, error) {
	matchID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	match, err := r.Queries.GetMatch(ctx, matchID)
	if err != nil {
		return nil, err
	}
	if match.Away.ID == 0 {
		return nil, nil
	}
	cm, err := r.Queries.GetClubMatch(ctx, match.Away.ID)
	if err != nil {
		return nil, err
	}
	club, err := r.Queries.GetClubForClubSeason(ctx, cm.ClubSeasonID)
	if err != nil {
		return nil, err
	}
	return convertClubMatch(cm, club), nil
}

// Season is the resolver for the season field.
func (r *fFLRoundResolver) Season(ctx context.Context, obj *FFLRound) (*FFLSeason, error) {
	roundID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	round, err := r.Queries.GetRound(ctx, roundID)
	if err != nil {
		return nil, err
	}
	season, err := r.Queries.GetSeason(ctx, round.SeasonID)
	if err != nil {
		return nil, err
	}
	return convertSeason(season), nil
}

// Matches is the resolver for the matches field.
func (r *fFLRoundResolver) Matches(ctx context.Context, obj *FFLRound) ([]*FFLMatch, error) {
	roundID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	matches, err := r.Queries.GetMatches(ctx, roundID)
	if err != nil {
		return nil, err
	}
	return convertMatches(matches), nil
}

// Ladder is the resolver for the ladder field.
func (r *fFLSeasonResolver) Ladder(ctx context.Context, obj *FFLSeason) ([]*FFLClubSeason, error) {
	seasonID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	clubSeasons, err := r.Queries.GetClubSeasons(ctx, seasonID)
	if err != nil {
		return nil, err
	}
	result := make([]*FFLClubSeason, len(clubSeasons))
	for i, cs := range clubSeasons {
		club, err := r.Queries.GetClubForClubSeason(ctx, cs.ID)
		if err != nil {
			return nil, err
		}
		result[i] = convertClubSeason(cs, club)
	}
	return result, nil
}

// Rounds is the resolver for the rounds field.
func (r *fFLSeasonResolver) Rounds(ctx context.Context, obj *FFLSeason) ([]*FFLRound, error) {
	seasonID, err := fromID(obj.ID)
	if err != nil {
		return nil, err
	}
	rounds, err := r.Queries.GetRounds(ctx, seasonID)
	if err != nil {
		return nil, err
	}
	return convertRounds(rounds), nil
}

// FflClubs is the resolver for the fflClubs field.
func (r *queryResolver) FflClubs(ctx context.Context) ([]*FFLClub, error) {
	clubs, err := r.Queries.GetClubs(ctx)
	if err != nil {
		return nil, err
	}
	return convertClubs(clubs), nil
}

// FflClub is the resolver for the fflClub field.
func (r *queryResolver) FflClub(ctx context.Context, id string) (*FFLClub, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, err
	}
	club, err := r.Queries.GetClub(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return convertClub(club), nil
}

// FflPlayers is the resolver for the fflPlayers field.
func (r *queryResolver) FflPlayers(ctx context.Context) ([]*FFLPlayer, error) {
	players, err := r.Queries.GetPlayers(ctx)
	if err != nil {
		return nil, err
	}
	return convertPlayers(players), nil
}

// FflPlayer is the resolver for the fflPlayer field.
func (r *queryResolver) FflPlayer(ctx context.Context, id string) (*FFLPlayer, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, err
	}
	player, err := r.Queries.GetPlayer(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return convertPlayer(player), nil
}

// FflSeasons is the resolver for the fflSeasons field.
func (r *queryResolver) FflSeasons(ctx context.Context) ([]*FFLSeason, error) {
	seasons, err := r.Queries.GetSeasons(ctx)
	if err != nil {
		return nil, err
	}
	return convertSeasons(seasons), nil
}

// FflSeason is the resolver for the fflSeason field.
func (r *queryResolver) FflSeason(ctx context.Context, id string) (*FFLSeason, error) {
	parsed, err := fromID(id)
	if err != nil {
		return nil, err
	}
	season, err := r.Queries.GetSeason(ctx, parsed)
	if err != nil {
		return nil, err
	}
	return convertSeason(season), nil
}

// FflLatestRound is the resolver for the fflLatestRound field.
func (r *queryResolver) FflLatestRound(ctx context.Context) (*FFLRound, error) {
	round, err := r.Queries.GetLatestRound(ctx)
	if err != nil {
		return nil, err
	}
	return convertRound(round), nil
}

// FFLClubMatch returns FFLClubMatchResolver implementation.
func (r *Resolver) FFLClubMatch() FFLClubMatchResolver { return &fFLClubMatchResolver{r} }

// FFLMatch returns FFLMatchResolver implementation.
func (r *Resolver) FFLMatch() FFLMatchResolver { return &fFLMatchResolver{r} }

// FFLRound returns FFLRoundResolver implementation.
func (r *Resolver) FFLRound() FFLRoundResolver { return &fFLRoundResolver{r} }

// FFLSeason returns FFLSeasonResolver implementation.
func (r *Resolver) FFLSeason() FFLSeasonResolver { return &fFLSeasonResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type fFLClubMatchResolver struct{ *Resolver }
type fFLMatchResolver struct{ *Resolver }
type fFLRoundResolver struct{ *Resolver }
type fFLSeasonResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
